### ISSUE TITLE
Add POST method and /properties/archived resource

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#105]
PUT /properties/id 
Toggles the archive variable for a property 

Add boul Archived to property model 
Add a PUT method to property resource 
PUT method finds property by id 
If the property exists the method sets Archived value = True if Archived is false
If Archived = false set value to True

**Comment by DaveTrost** [comment]
Branch with changes in progress is [put-properties](https://github.com/codeforpdx/dwellinglybackend/tree/put-properties)

Status:
- [x] Modify database tables in data.db to include a column for "archived"
- [x] Add boolean Archived to property model
- [x] PUT method finds property by id
- [x] If the property exists the method sets Archived value = True (if Archived is false) or False (if Archived was true)

**Comment by DaveTrost** [comment]
I submitted a [PR](https://github.com/codeforpdx/dwellinglybackend/pull/9) for this item. It seems an anti-pattern to use a PUT operation to force a property to toggle its state. Should there maybe be a route specifically for archival (PUT /properties/archive/{name})?

**Comment by DaveTrost** [comment]
Updated implementation plan based on convo with Hugh

POST /properties/archive/id
Toggles the archive variable for a property

Add bool Archived to property model
Add a class for property-archival and add a POST method to that resource
POST method finds property by id
If the property exists, set Archived = True

**Comment by DaveTrost** [comment]
The [PR](https://github.com/codeforpdx/dwellinglybackend/pull/12) containing this work is from archive-properties to development

New work:
- [x] simplify logic in property class
- [x] new route for /properties/archive/<id>
- [x] resource for this path enables a POST method
- [x] POST method finds property by id & sets Archived = True

**Comment by DaveTrost** [comment]
[The PR for this work ](https://github.com/codeforpdx/dwellinglybackend/pull/12) is updated to handle the case of a property becoming un-archived.

- property's "archived" value can go from true -> false
