### ISSUE TITLE
ADD Archived to User Resource/Model

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#106]
Add Boul Archived to User Model 

Add PUT method to /users/id endpoint
Put method finds user 
if user 
Toggle Archived True/False

Update Login Method 
Add conditional for Archived variable 
if Archived Return not valid user

**Comment by DaveTrost** [comment]
This work is completed with implementation based on the approach used for property archival. [PR can be found here](https://github.com/codeforpdx/dwellinglybackend/pull/13):

Tasks:
- [x] Add Archived property to the User Model
- [x] Add PUT method to /users/archive/id endpoint
- [x] PUT method finds user and toggle the "archived" property between True and False
- [x] Update Login Method to disallow login for archived users. Return "not valid user"

More Tasks (I followed this helpful reference resource for [Expiring tokens in Flask](https://codereview.stackexchange.com/questions/209582/expiring-jwt-tokens-in-flask)):
- [x] Add new RevokedTokens model to store JWT ID's (JTI's) that have been invalidated
- [x] Configure app to use JWT blacklisting and create the "token_in_blacklist_loader" function 
- [x] When a user is archived, add their current JTI to the RevokedTokens table
