### ISSUE TITLE
Create Staff Member sidebar

### ISSUE THREAD

**Issue by dougmakingstuff** [codeforpdx/dwellingly-app#12]
Create sidebar with appropriate links for Staff Member, displayed when user logs in under this kind of account.

Links include:
* Search Property Managers
* Search my tenants
* Search all tenants
* Preferences
* Out-of-Office
* Logout

**Comment by dougmakingstuff** [comment]
Related to #10 and #11

**Comment by ajquintero** [comment]
I can work on this
