### ISSUE TITLE
User Model/Resource: Find by role

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#120]
Post request to find users in database which match role 
will need to return ALL users that match the role (this will probably change as we scale)
Will need a new User Model method name find_by_role which returns all the the users which match the role 
The end point will be a POST which requires a string of "Userrole" 
JWT claims required
The Endpoint should be exposed as /users/role

**Comment by DaveTrost** [comment]
PR is here: https://github.com/codeforpdx/dwellinglybackend/pull/15

**Comment by DaveTrost** [comment]
DO NOT MERGE until code changes in #106 are merged
