### ISSUE TITLE
add firstName & lastName to User Model (user.py)

### ISSUE THREAD

**Issue by skrabacher** [codeforpdx/dwellingly-app#129]
Front end form mock-up has a First and Last name fields. Please add firstName and lastName to user model on the back end.

**Comment by DaveTrost** [comment]
I'm on it

**Comment by DaveTrost** [comment]
Hugh, I'm going to take a stab at filling out the details on this one. Please review and modify as needed ...

- Add firstName and lastName to user model
- remove the `username` property from user model
- use email address for login purposes. This aligns with the requirement that no 2 users can have the same email address
  - build `find_by_email` method in User model 
  - change UserLogin resource to use `find_by_email`
  - change UserRegister resource to use `find_by_email`
- update user model information in the README
- seed the database with default users
- add information to README about default users and login information
