### ISSUE TITLE
FRONTEND: Create Add New Tenant Page

### ISSUE THREAD

**Issue by heaversm** [codeforpdx/dwellingly-app#130]
**Purpose**
What will this feature provide?
Adds the ability to create a new tenant like on pages 11 and 12 of the mockups
https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view

**Proposed Solution**

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Should be able to set First Name, Last Name, and Phone number in a form
- [ ] Should be able to assign one or more JOIN Staff members to the tenant
- [ ] Should be able to assign a property to the tenant
- [ ] Should be able to describe the Unit for the tenant in another form

**Additional context**
![image](https://user-images.githubusercontent.com/8600792/92525200-402ad400-f1d8-11ea-8cdc-b62540e3be48.png)

**Comment by Chris-Boe** [comment]
Hey @heaversm ! Hope you've been doing well, we miss you in meetings!
If this is in progress, let us know but I'll unassign you for now so someone else can pick it up.
Stay healthy and safe out there!
