### ISSUE TITLE
FRONTEND: Add non-admin dashboard to front end

### ISSUE THREAD

**Issue by skrabacher** [codeforpdx/dwellingly-app#131]
It's not in the mockups yet but it will be a compilation of some of the widgets on the current admin dashboard, and made available to non-admins

**Comment by Chris-Boe** [comment]
It looks like we have some mobile mockups here https://drive.google.com/file/d/1wGLQI6d5-RK59E4P65wdotAXdNsSstRR/view?usp=sharing that we could get started on building. As far as the desktop versions of these we can do some brainstorming with @michellelsfong !

**Comment by michellelsfong** [comment]
Yeah! I have to miss this week, but let's discuss next week if that works for yall. :-)

**Comment by htharker42** [comment]
issue is no longer needed - closing
