### ISSUE TITLE
Branding: Update Logo

### ISSUE THREAD

**Issue by dougmakingstuff** [codeforpdx/dwellingly-app#14]
There is no logo in the product. We need to add the Dwellingly logo where appropriate.

**Comment by richardbmx** [comment]
@dougmakingstuff Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by bobbymart1n** [comment]
The new Dwelling.ly logo is in the feature/login-screen branch under `/assets/images/dwellingly-logo`
