### ISSUE TITLE
BACKEND: Add a CLI for Flask 

### ISSUE THREAD

**Issue by DaveTrost** [codeforpdx/dwellingly-app#161]
Look into using [flask-script](https://flask-script.readthedocs.io/en/latest/) or [Flask-CLI](https://flask.palletsprojects.com/en/1.1.x/cli/) for more automation around seeding the database (and other developer tasks?)

**Comment by jeremyrader** [comment]
@DaveTrost I'd love to work on this. Do you have any examples of what you'd like to see?

**Comment by DaveTrost** [comment]
Hi @jeremyrader! This is not something I've done before. Please work on this! 
BTW, the dwellingly-join channel in the Code for PDX Slack group is a great place to get answers to questions like this, including the context of an issue! (aka: I opened this issue in a record-keeping role, as opposed to a subject matter expert role!)
Edit: when you get going on this, please assign yourself to the task and move it to the to-do column of the [sprint](https://github.com/codeforpdx/dwellingly-app/projects/4#card-36842040)

**Comment by mswanson-me** [comment]
I might be interested in this issue also. @jeremyrader, are you working on this?
