### ISSUE TITLE
Integrate Dashboard/Request for Access with the Backend 

### ISSUE THREAD

**Issue by DaveTrost** [codeforpdx/dwellingly-app#163]
The dashboard page has a list for new users who don't have their access level assigned yet. These users will be triaged by an admin and their access will then be established. (Otherwise, newly registered users have their access set to "pending")

- Find users with pending access by: POST /users/role and provide a body with "userrole": "pending"
- If the admin selects "DECLINE" and then "YES", delete the user by id with: DELETE /user/<id>
  - Repeat the step to find users with pending access and use that data to refresh the list
- If the admin selects "ADD", go to the "Request for Access" page

**Comment by chrisandrewca** [comment]
Hi @DaveTrost , I picked this one up if that's alright. There's some branches going for this work -- [app ](https://github.com/codeforpdx/dwellingly-app/tree/cc/req-access-%23163)/ [db](https://github.com/codeforpdx/dwellinglybackend)

**Comment by DaveTrost** [comment]
Hey @chrisandrewca, that sounds great! My plan was to put enough detail into the issue so anyone could work on it. Let me know if you have any questions.

**Comment by DaveTrost** [comment]
Hi @chrisandrewca, Nice work on the front end here! You should join us on our project night video calls so you can share status updates and find more areas to jump in and work. There's a Slack channel as well. I will send you an email with more info.
