### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#179]
The client would like us to add a footer with the following text. 
Made with love by Amplified By Design and Code For PDX. 
Please include links to each organization
https://www.amplifiedbydesign.com/
https://www.codeforpdx.org/

**Comment by mgrienauer** [comment]
Should the footer span the entire viewport or just the dashboard? It looks like it has dashboard BEM classes already so I'm assuming just the dashboard? Also, are bulma helper classes not being passed down automatically? Should I be importing any bulma classes I need within the component?
