### ISSUE TITLE
 Remove .vscode folder

### ISSUE THREAD

**Issue by mxzinke** [codeforpdx/dwellingly-app#180]
`.vscode` folder contains settings for VS-Code users. You can remove them by adding them in the `.gitignore` file.

**Comment by Chris-Boe** [comment]
This is good to have for VS Code contributors to get some formatting/coding conventions applied to their VS Code automatically workspace, so I'd vote we keep it since it does no harm!

**Comment by Chris-Boe** [comment]
Just did a survey and we're going to keep it around since we have many VS Code users.
Thanks though!
