### ISSUE TITLE
Fix Proxy requests for various endpoints

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#199]
recent update now causing issues with backend on localhost. Update endpoints to address issue.

Error reads: 
Proxy error: Could not proxy request /api/users/role from localhost:3000 to http://localhost:5000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED)

occurs for following endpoints. 
/api/refresh
/api/tenants

**Comment by DaveTrost** [comment]
This maybe is not a problem anymore. 
@htharker42 - can you update this issue and close if needed?
