### ISSUE TITLE
FrontEnd: Create Emergency Contact- Bug fix - 

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#206]
when "Add New Phone Number" is selected to add an additional number, container height is not dynamically adjusted and buttons to submit phone number are pushed below the footer.

**Comment by marcusjensen15** [comment]
Hey Hugh,

I believe I've fixed it. Please check out my code as this is my first pull request on the project aside from the README. My goal was to be as minimally invasive as possible when fixing this bug.

branch is called: emergency-contact-bug-fix

One thing I did that I'm not completely sure is kosher: I added a 'let' variable titled 'resize' at the top of addEmergencyContact.js which is accessible to all of the constants below. This was what I found to be the DRYest way to apply styling to all of the necessary fields on the "Add New Phone Number" click.

Thanks, and if this isn't up to standard please let me know what I can fix :)

**Comment by Chris-Boe** [comment]
Fixed also by issue #231
