### ISSUE TITLE
Notes from 06/27/2019 Meetup!

### ISSUE THREAD

**Issue by augustinevt** [codeforpdx/dwellingly-app#21]
<h1 align="center">🎉 :heart:  PEOPLE FIRST SOFTWARE DESIGN :heart: 🎉 </h1>

## Planning Todos:
- Ask Bobby about the branches
- if Bobby doesn't know we can look through the branches to see if it's worth merging them
- if merging the branches is too complex or not worth it, start with main and spin off a new "Develop" branch

## Code Todos:

- isolate all the auth components
    - update an issue with small descriptions

- explore the branches to see if the recent ones (feature/reducer-tests and feature/staff-list) have significant value.

# Important Notes and Questions

  #### should we bring some/all of the questions below up with Hugh?

  #### figure out first slice for the code stuff

  #### make contact with the people the app is serving

  #### maybe create an accessible slack channel for everyone to see/participate in discussions with Join?
    
  ### questions we should answer:
- should we define scaling?
- who are we building this for?

    - what is the deployment plan?
      - who is paying for it?
        - are we trying to stay in free-tier?
        
      - who is going to maintain the finished app?
      - Where are we hosting the components? AWS, Google, Digital Ocean?

    - what is the end functionality/purpose?

    - Why did they choose Firebase?
      - was it a security / scoping concern?
      - should we bring up the potential of staying with firebase at least Auth?
      - can we get access to the firebase account?

    - security concerns
      - what are the vulnerabilities on an application level?
      - who is responsible for security vulnerabilities? (cfpdx or join?)
  
    - how can we get better access to the visual design assets?
      - via Figma?

    - can we establish contact with Join or Amplify?
      - Join
        - who is responsible for this initiative (on their side)?
        - will they maintain?
        
      - Amplified by Design
        - bobby 
          - from Amplified by Design
          - built some of the app
        (can we get access to the firebase account?: see above)
     - sydney
        - from Amplified by Design
        - designed UX / UI for the app

OTHER NOTES!

- If they (?) don't have maintainers, we should rely on connecting services instead of building our own service components...

- especially in terms of scaling and expense(!!)

**Comment by kdv24** [comment]
@htharker42 and @bobbymart1n,  a group of us working on dwelling.ly's front end met today and identified some questions we'd love input on.  I think slack or a Wednesday meeting might be an easier place to have conversation around these topics/questions, but want to share what we're thinking. Thanks!
