### ISSUE TITLE
GET /tenants is not admin protected

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#219]
We need to put a @admin_required attribute on that resource

**Comment by marcusjensen15** [comment]
Hey Chris! Are you working on this, or should I have a go at it?

If so, I'm not totally sure what you mean by this. I noticed there isn't a '/tenants' route living in App.js. 

Are you referring to creating a <PrivateRoute> for '/tenants' just like the other routes in app.js?

(just realized this might be a backend task)

**Comment by Chris-Boe** [comment]
This is a backend task! 😄 and totally realized I assigned myself when i made the issue but didn't mean to! It is free to pick up for anyone

**Comment by NickSchimek** [comment]
It looks like this is done. Should this ticket be closed?

**Comment by cecillesalazar** [comment]
Yep, sure should be! Thanks for the catch 👍
