### ISSUE TITLE
Backend: expand data exposed in /tickets/ endpoint

### ISSUE THREAD

**Issue by mswanson-me** [codeforpdx/dwellingly-app#226]
The frontend tickets dashboard module needs information about age of tickets and 'staleness' of tickets. Since the datetime info coming from the backend is formatted, it is difficult to calculate deltas on the frontend. Please update the /tickets/ endpoint to expose the following data points for each ticket:

Time since ticket creation
Time since ticket claimed
Time since last note on ticket

Please use seconds as unit of measure. If clarification is needed, please tag @mswanson-me 

This issue is blocking issue #201 

To Do:
- [x] modify the "updated" property in the ticket model. It is a date string that updates when the ticket's **status** changes
- [x] create a "minsPastUpdate" property in the ticket model. It is an integer that represents the number of minutes that have passed since the status was last updated

**Comment by mswanson-me** [comment]
Maybe even a better solution would be to simply provide all currently existing timestamps to the frontend without formatting them. Then any math needed can be done in the frontend, and timestamps can be formatted prior to rendering. This solution would require **no new data points** to be exposed.

**Comment by DaveTrost** [comment]
Here are the needs for ticket views and reports from the front end:
1. count unseen tickets
2. for each ticket, display the date when it was moved to its current state
3. calculate for how long a ticket has been in "new" status (in hours/minutes)
4. calculate for how long a ticket has been in "in progress" status (in days)
5. calculate if the "opened" date of a ticket falls within a range of dates

Here are the current ticket fields
- opened: a timestamp string
- updated: a timestamp string that updates when the ticket changes in **any** way
- status: a string that indicates "new", "in progress", or "closed"

Here are the proposed ticket fields
- opened: a date string (needed for item 5)
- status: a string that indicates "new", "in progress", or "closed" (needed for items 1, 2, 3 & 4)
- statusUpdated: a date string that updates when the ticket's status changes (needed for items 2 & 4)
- secondsInStatus: an integer that represents the number of seconds between _now_ and statusUpdated (needed for item 3)

**Comment by DaveTrost** [comment]
I'm having a hard time getting accurate ticket times in seconds. The date stamp stored in the db is in HH:MM format, so any measurement made in seconds will be inherently inaccurate by up to 59 seconds. So, I propose a time format that uses minutes. Although the Javascript default is use seconds for times, the front end doesn't actually need anything more accurate than hours, and with the JSON field name changed to "minsPastUpdate", I hope it is clear enough.

@mswanson-me - how does this sound?

**Comment by DaveTrost** [comment]
@mswanson-me hey I made a PR for this. If you pull down my branch on the backend, you can test with the new code. Please let me know how it works and if further changes are needed
