### ISSUE TITLE
add multiple tenants 

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#236]
Allow for multiple tenants on a property. 
will need to change property.tenantsID to [1,2,3]
update return statements to iterate through tenants and provide information.

**Comment by dbridenbeck** [comment]
@htharker42 Hey Hugh!

From what I'm seeing, we can't store a list in SQLite directly, and would need to create another table to store the list of tenantIDs, and then make a relationship between it and the property.

I don't quite have my sea-legs yet with Flask and SQLite, can you confirm if I'm barking up the right tree here?

Another alternative I thought of is creating a one-to-many relationship between tenants and a property. I've been playing around with that but am having a hard time returning the related tenants as JSON with PropertyModel.json()
