### ISSUE TITLE
Frontend: Reusable Component - Title & Pen Icon

### ISSUE THREAD

**Issue by dbridenbeck** [codeforpdx/dwellingly-app#242]
**Purpose**
- Create a reusable component that can be used for pages where there is a Title and Pen Icon displayed
- This would handle the styling for the title and pen icon, and also track the state of if the pen icon is clicked

**Proposed Solution**
- Create a new component in /src/components
- Style the Title and pen icon to match the Figma docs
- set useState to something like `const [isEditing, setEditingStatus] = useState(false);` to track the state of if the edit button has been clicked
- conditionally change the background of the pen icon to a blue if isEditing is true, and grey if false
- export the component, isEditing and setEditingStatus so that other components can access and update the editing state (e.g. - on submit, or if the cancel button is clicked, isEditing will need to be set to false)

**Acceptance Criteria**
- Title and Pen icon should closely resemble the style of the figma docs
- A great test case to ensure this works would be to implement this component into `/src/views/manager/index.js`. here's an idea on how to do this:
        1. replace everything `<div className="title__container">` and everything inside it with your brand new Title & Pen component
        2. remove useState and handleEditToggle function
        3. export isEditing from the Title & Pen component and pass it to `<ToggleEditTable />`
        4. export setEditingStatus from Title & Pen component and use it in onFormikSubmit and onCancelClick

In the above test case, the /manage/managers/:id route should work as follows:
    - Clicking pen icon should toggle the editable form, make the pen icon blue, and disable re-clicking the pen icon
    - Submitting the form or clicking the "Cancel" button should re-enable the pen icon, and revert back into a non-editable table

**Mockup Screenshot or Page Number**
Can be see on page 30, 9, 10, 13, 17, 22, and many others! Green border indicates the component in question.
![Screen Shot 2020-07-06 at 4 22 01 PM](https://user-images.githubusercontent.com/49624436/86666047-0dc8e480-bfa5-11ea-9a9e-746202411090.png)

**Additional context**
- none that I can think of!

**Comment by SeHarlan** [comment]
On it! Hopefully will be done in a day or two.

**Comment by SeHarlan** [comment]
Component has been created and placed in Mangers and Emergency Contacts views. Right now the state is set in a custom hook (can be called with <const {isEditing, setEditingStatus} = useEditingStatus()>.
useEditingStatus must be imported by name from "/components/TitleAndPen".
This could also be done using locally scoped state, either way the state and setter must be passed to the main component.
