### ISSUE TITLE
FRONTEND: Create Mobile Friendly Login/Create User Page

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#244]
See [FIGMA Designs](https://drive.google.com/file/d/1wGLQI6d5-RK59E4P65wdotAXdNsSstRR/view?usp=sharing) for design guidelines. Under header LogIn Create Account Best if opened in PDF viewer. 

- Use existing routes if new routes mobile specific routes are needed use the /m/routename convention 
- For Existing pages use css [media breakpoints](https://www.w3schools.com/howto/howto_css_media_query_breakpoints.asp) to specify the different formats 

- [x] Create Login View

- [x] Create Account View

- [ ] Create Account Confirmation Alert 

- [x] Forgot Password View

- [x] Privacy Policy View

- [x] Terms and Conditions View 

If needed, a group can approach this topic. 

![image](https://user-images.githubusercontent.com/32914953/86998998-727f6d00-c166-11ea-82f0-2daf479b8cac.png)
![image](https://user-images.githubusercontent.com/32914953/86999043-86c36a00-c166-11ea-9177-9a3dd9eafc96.png)

Good night, and good luck.

**Comment by marcusjensen15** [comment]
Tackled Login View in Pull Request #249 . Awaiting review. 

Also, I can make 'Login with Google' into a component if it would be helpful.

**Comment by Chris-Boe** [comment]
Let's try to make pages as responsive as possible so there's no need for a separate "desktop" and "mobile" view. Our Header and main-container (wrapped around every route in App.js so it applies to everything) are already responsive, so for most of these we can just use the normal page with some small changes to the content's styling

**Comment by Chris-Boe** [comment]
Closing this and breaking out the last piece as a new issue
