### ISSUE TITLE
BACKEND: Update backend seed data to match relationship between tables and create additional edge cases

### ISSUE THREAD

**Issue by sokampdx** [codeforpdx/dwellingly-app#250]
Currently, the data/seedData.py has some dummy data but some of them are not reflecting the real relationship between property manager, property and tenants. 

e.g.
First property id 1 point to tenants id 3
`    newProperty = PropertyModel(name="test1", address="123 NE FLanders St", city="Portland", state="OR", zipcode="97207", propertyManager=5, tenants=3, dateAdded="2020-04-12", archived=0)
`
but tenant id 3 point back to property id 2
`    newTenant = TenantModel(firstName="Starvin", lastName="Artist", phone="123-123-1111", propertyID=2, staffIDs=[])
`

Additionally, we could add additional edge case such as property without tenants, tenants without property.

**Comment by gussmith23** [comment]
New to the project, first issue, so excuse the questions.

Looks like the original comment is out of date at the moment:

> e.g.
> First property id 1 point to tenants id 3
> `newProperty = PropertyModel(name="test1", address="123 NE FLanders St", city="Portland", state="OR", zipcode="97207", propertyManager=5, tenants=3, dateAdded="2020-04-12", archived=0)`
> but tenant id 3 point back to property id 2
> `newTenant = TenantModel(firstName="Starvin", lastName="Artist", phone="123-123-1111", propertyID=2, staffIDs=[])`

Current PropertyModels don't seem to point to tenants anymore, though:
```   python
newProperty = PropertyModel(name="test1", address="123 NE FLanders St", unit="5", city="Portland", state="OR", zipcode="97207", propertyManager=5, dateAdded="2020-04-12", archived=0)
```

Looks like some recent changes have fixed some of the discrepancies. Will continue familiarizing myself.

**Comment by gussmith23** [comment]
See the linked issue. There are [two TODO comments](https://github.com/codeforpdx/dwellinglybackend/pull/92/files#diff-677d3b8d01d4bddb3163c41368b40593R169-R178) inserted in that issue which include at least two fixes that should be made in the PR for this issue. I need to stop working on this for the day, but I will continue working on this in the future. Someone else can pick it up too -- just comment here!
