### ISSUE TITLE
FRONTEND: Fix Filter Collapsible on Tickets page

### ISSUE THREAD

**Issue by zfregin** [codeforpdx/dwellingly-app#263]
The container for the Collapsible component gets cut off when expanded. Adjust CSS styling to prevent overlap

**Comment by Chris-Boe** [comment]
Can you post a screenshot? This is what I see, it seems alright 
![image](https://user-images.githubusercontent.com/8600792/89726238-16aa3d00-d9cd-11ea-9177-6ca44431c76e.png)
