### ISSUE TITLE
FRONTEND: Toast Notification

### ISSUE THREAD

**Issue by zfregin** [codeforpdx/dwellingly-app#264]
Utilize a Toast library for generating toast notifications. Some Toast examples shown on pages 33 and 63 of the design mockup

**Comment by Chris-Boe** [comment]
We use a homemade wrapper around (react-toastify)[https://www.npmjs.com/package/react-toastify#toast] at my work that I like, if we want to use true, hovering toasts. The ones in the mockup look more like just a notification div (it pushes the content in the main-container down to fit it) but I think toasts would look better!

**Comment by Chris-Boe** [comment]
@michellelsfong @htharker42 , how do we feel about a notification div like in the mockup or hovering toast messages (click the gif below)?
![image](https://user-images.githubusercontent.com/8600792/90089951-94c15900-dcd7-11ea-92f4-879456ebc131.png)

https://user-images.githubusercontent.com/5574267/35336500-e58f35b6-0118-11e8-800b-2da6594fc700.gif

**Comment by michellelsfong** [comment]
I think the toast makes sense! If Hugh agrees, I can send you a reference for how it could animate.
