### ISSUE TITLE
Environment Variable Undefined

### ISSUE THREAD

**Issue by zfregin** [codeforpdx/dwellingly-app#266]
The `REACT_APP_API_URL` environment variable is undefined.

Variable appears to be set in `static.json` but when logging `process.env.REACT_APP_API_URL` to console it is undefined. Variable is referenced in `src/views/managers.js`, and `src/views/manager/index.js` but function not getting called

**Comment by Chris-Boe** [comment]
Hey Zach! It was recently changed to `REACT_APP_PROXY` in PR #255. So now when you want to make a request, you won't need to reference that variable directly, just have `/api/{endpoint}` in the URL parameter alone like this:

`axios.get("/api/properties", { headers: {"Authorization" : `Bearer ${context.user.accessJwt}`} })`

**Comment by zfregin** [comment]
Awesome, closing this
