### ISSUE TITLE
BACKEND: implement lease id relation on tenant model

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#270]
@htharker42 I came across this commented out code here: https://github.com/codeforpdx/dwellinglybackend/blame/93dc593c0c5b068c49a2d7822222dbf57911e697/models/tenant.py#L13

Is this something that needs to be implemented?

**Comment by htharker42** [comment]
@NickSchimek Yes, We need to connect the Lease Model to the Tenant Model
