### ISSUE TITLE
Add CreatedDate to User model

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#272]
**Purpose**
One use of this is on the Dashboard, where it shows the "New Property Managers" area for #202 

**Proposed Solution**
Add the CreatedDate to the User model on the backend, and have API calls that get Users return that information:
https://github.com/codeforpdx/dwellinglybackend/blob/development/models/user.py

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [x] Add CreatedDate to model
- [x] Have CreatedDate get automatically filled in when the user is signed up (Q for @htharker42: Or maybe when they are promoted to Property Manager and given access?)
- [x] Update Seed data
- [x] Make sure it gets sent back to the UI

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.
Any of the dashboard mockups have this section
![image](https://user-images.githubusercontent.com/8600792/90594925-83c58b80-e1a0-11ea-813f-3891d1da2fe5.png)

**Additional context**

**Comment by NickSchimek** [comment]
It looks like this has been implemented in https://github.com/codeforpdx/dwellinglybackend/pull/91
