### ISSUE TITLE
BACKEND: Allow user lookup by email

### ISSUE THREAD

**Issue by dbridenbeck** [codeforpdx/dwellingly-app#277]
**Purpose**
Allow users to be looked up by email. This is needed for the Forgot Password page (page 24 of figma docs)

**Proposed Solution**
Create a POST method for the User resource, and if "email" is provided in the payload, do `UserModel.find_by_email()`

**Acceptance Criteria**
- [ ] Should be able to hit /api/user/ with a payload of {"email": "user1@dwellingly.com" and get a JSON response for that user's details
- [ ] Should implement tests to ensure this route works as expected

**Mockup Screenshot or Page Number**
Page 24 of figma docs:
![Screen Shot 2020-08-20 at 3 52 21 PM](https://user-images.githubusercontent.com/49624436/90833555-2561ef80-e2fd-11ea-9426-0c5fd019789f.png)

**Comment by asharonbaltazar** [comment]
Hello,

Isn't this a security risk, allowing random users to look up emails?

**Comment by dbridenbeck** [comment]
@asharonbaltazar good call. This was a somewhat poorly written ticket of mine. Hugh did a more thorough write up, with better context on #289 

@NickSchimek is doing the lions share of the work on this (or so I believe!) and is implementing it in a better way than I described above. Reach out to him if you have more questions! :)

**Comment by asharonbaltazar** [comment]
Hey, I'd love to contribute, actually looking at other open source projects for issues. Is there anything frontend related I can do?

**Comment by dbridenbeck** [comment]
@asharonbaltazar have you come to a weekly meeting for Code for PDX yet? If not, @htharker42 can help get you on the slack channel where it might be easier to help figure out what needs attention. We're currently in a push to get a lot of things done by this Saturday, so your help would be appreciated I'm sure! :)

**Comment by asharonbaltazar** [comment]
Great, waiting for the Slack invite

**Comment by NickSchimek** [comment]
completed codeforpdx/dwellinglybackend#87
