### ISSUE TITLE
BACKEND: Hash passwords

### ISSUE THREAD

**Issue by dbridenbeck** [codeforpdx/dwellingly-app#280]
**Purpose**
We should hash our passwords before storing or updating them in the DB!

**Proposed Solution**
- Sounds like we're going to use Flask-bcrypt to do hashing
- Will need to make sure that the `UserRegister` resource's POST and `User` resource's PATCH implement password hashing
- Will also need to update the `UserLogin` resource's POST to validate the user's password matches the hashed password in the db

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] When creating a new user, their password in the DB should be a hashed password, not actual text
- [ ] When updating a new user's password their password should also be hashed when saved in the DB
- [ ] You should still be able to login as usual

**Mockup Screenshot or Page Number**
None applicable!

**Additional context**
Let me know if I missed a step on what we need to consider when implementing this feature! I'm fairly new at bcrypt, so any perspective is welcome :)

**Comment by asharonbaltazar** [comment]
I can try my hand at this. I've hashed passwords before

**Comment by cecillesalazar** [comment]
@asharonbaltazar - I've already started it - I've used bcrypt before - but for javascript and not flask. Happy to either pair or push up what I have if you really want to give it a go 👍

**Comment by asharonbaltazar** [comment]
@cecillesalazar that's okay, then. I'll find something else to do!
