### ISSUE TITLE
FRONTEND: Connect Dashboard Modules to Backend

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#281]
**Purpose**
Connect Widgets to backend data

**Proposed Solution**
Created endpoint to send back data which matches existing structure used by dashboard modules/widgets

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Populates all three widgets with correct information 
- [ ] Data Format Matches design 

**Mockup Screenshot or Page Number**
![image](https://user-images.githubusercontent.com/32914953/90989416-774d8400-e54e-11ea-96a6-4fc3acec3c61.png)

**Additional context**
Will need to be done in conjunction with back-end update. 
API endpoint /widgets

**Comment by asharonbaltazar** [comment]
I feel like I can do this, but I'd like more information about the API endpoints I'd be hitting and how to access them.
