### ISSUE TITLE
FRONTEND: Edit button on "Create an Account" to navigate back to login interface

### ISSUE THREAD

**Issue by yhafez** [codeforpdx/dwellingly-app#295]
**Purpose**
What will this feature provide?
When users click "Create an Account", they are directed to an interface with a sign up form and a button to "Log In with Google". Currently, there is no way to navigate back to the login interface from the "Create an Account" interface.

Since the "Log In with Google" button is not currently enabled to connect to Google, it can be repurposed to just say "login" and allow users to navigate back to the general login interface where they have the option to log in normally or through Google.

**Proposed Solution**
If you have an idea on how to implement this feature, please share!

Navigate to ./src/views/signup.js and change "Log In with Google" to just "Log In", adjusting the classname accordingly. Add an "onClick" property to the button pointing to a "handleClick" function and create such a function which would navigate the user back to the login page.

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] "Log In with Google" button is changed to just say "Log In"
- [ ] The Google icon is removed from the button
- [ ] Clicking the button successfully navigates the user back to the login page (the "/login" route)

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

There's no page in the FIGMA docs for the "Create an Account" page. The current page looks like this:

<img width="583" alt="Screen Shot 2020-09-04 at 8 08 34 PM" src="https://user-images.githubusercontent.com/60084578/92296789-03679000-eeed-11ea-97d8-e3f1852883a9.png">

**Additional context**
N/A

**Comment by asharonbaltazar** [comment]
Hello, can I try my hand at this?

**Comment by yhafez** [comment]
Of course! I went ahead and assigned you to the issue. Feel free to message me on Slack if you need help or have any questions :)

**Comment by asharonbaltazar** [comment]
Pull request is pending.
