### ISSUE TITLE
BACKEND: Add route for GET requests to /api/users

### ISSUE THREAD

**Issue by yhafez** [codeforpdx/dwellingly-app#296]
**Purpose**
What will this feature provide?
Get requests to localhost:5000/api/users currently returns a 404 page not found error. The backend readme specifies that this route should return a list of all users when a request from a user with a role of "dev" is made to it. This will allow us to use the user data to populate the dashboard.

Additionally, seed data should be created or changed to include a user with the value of "dev" assigned to their "role" key.  

**Proposed Solution**
If you have an idea on how to implement this feature, please share!
I'm not too solid with Python, but I imagine the bearer token should be extracted from the request body and decoded using Json Web Token and the private key. The user id should be extracted from the decoded JWT and a database query should be made to obtain the user data associated with that user id. If the "role" key has a value of "dev", a query should be made to the database to return all users (if we're using SQL, something like `SELECT * FROM users WHERE id=${userId}`) and the result should sent to the front end. If the user's "role" is not dev or if no bearer token is provided, a "unauthorized user" with or "missing credentials error" respectively should be sent instead with status codes of, I believe, 401 (unauthorized) and 400 (bad request) respectively.

I believe the ./data/seedData.py file is where seed data should be updated to include a user with "dev" as their role, and the backend README.md file should be updated to include the new "dev" user's credentials for reference.

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] A GET request to the /api/users route returns a "missing credentials" error if not bearer token is provided in the request header
- [ ] A GET request to the /api/users route should use the bearer token to determine if the user making a request has the role of "dev" and return an unauthorized user error if the user has a different value assigned for "role"
- [ ] A GET request to the /api/users route from a user whose provided bearer token is that of a user with "dev" as their "role" should return a list of all users currently stored in the database
- [ ] Seed data should be changed or added so that developers can use a seed user with a role of "dev" to successfully make such a request
- [ ] Back end Readme should be updated to show the credentials of this user so that developers have a reference to its login credentials

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.
N/A

**Additional context**
N/A

**Comment by htharker42** [comment]
I'll take a look at this tonight

**Comment by jls-github** [comment]
Trying to do https://github.com/codeforpdx/dwellingly-app/issues/305 - if this is still needed, I can do it and then knock out 305 as well.

**Comment by yhafez** [comment]
> Trying to do #305 - if this is still needed, I can do it and then knock out 305 as well.

@jls-github, there ended up being another route for what I needed that wasn't yet in the back-end readme, so this isn't holding up my other issue at this point, but I think from a dev-perspective, being able to access all users with a GET request returning all users stored in the db is really helpful for troubleshooting and seeing what changes are happening in the database, so I'd say go for it! Especially if it'll help you with issue #305

**Comment by jls-github** [comment]
Worked on this in pull request https://github.com/codeforpdx/dwellinglybackend/pull/96 - it won't let me link for some reason though.

**Comment by NickSchimek** [comment]
Closing this as will not implement. See the comments in https://github.com/codeforpdx/dwellinglybackend/pull/96#issuecomment-693025898 for one explanation.

**Comment by NickSchimek** [comment]
> Worked on this in pull request [codeforpdx/dwellinglybackend#96](https://github.com/codeforpdx/dwellinglybackend/pull/96) - it won't let me link for some reason though.

@jls-github I have a PR open to help with linking issues. See https://github.com/codeforpdx/dwellinglybackend/pull/95 on how to do this.
