### ISSUE TITLE
Update Postman and Backend README with correct API endpoints and example requests/responses

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#303]
**Purpose**
Update our information about our API's so that we can easily use them in Postman and reference them in the README

**Proposed Solution**
Follow the existing patterns to update the README API listings. You can find the endpoints and the expected request bodies and responses in the app.py, resources.py, and models.py files.

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Update README in the backend with correct APIs (some current ones may be out of date!)
- [ ] Update the postman collection and then repost the link to it in the backend README

**Additional context**

**Comment by asasha** [comment]
Are auto-documentation tools like [swagger](https://pypi.org/project/flask-swagger/) and [swagger-ui](https://pypi.org/project/flask-swagger-ui/) or [sphinx](https://www.sphinx-doc.org/en/master/) good options for future-proofing this type of ticket? I have used swagger before to success, but it does bloat the code a bit.

**Comment by NickSchimek** [comment]
Does swagger auto-document? I thought you had to do code annotations or have to keep a seperate yaml/json file updated.

FYI: we can get a list of all available routes by running the command `pipenv run flask routes` within the backend directory. It's safe to assume that all actions are restful (I will audit this). I don't think it is important to keep what each route returns in the README as there are many ways to get at that information that will always return the most updated result (Although I'm not suggesting we remove it either). If we wanted to we could create a flask command that will return the JSON representation of any object requested, but I don't think it's worth it at this stage of development. 

My suggestion is that after the MVP is delivered and if the client decides they want more functionality then that would be an appropriate time to look at other solutions for documenting the API.

**Comment by NickSchimek** [comment]
> Update README in the backend with correct APIs (some current ones may be out of date!)

@Chris-Boe I believe this part has been done. As far as the Postman collection link. I'm not sure what you are referring too, and it doesn't sound like a backend issue because we use automated tests instead of postman. If the frontend devs use Postman then perhaps this is a frontend issue? Please re-open if you find any api endpoints that are out of date, and specify which ones need to be updated. Thanks!
