### ISSUE TITLE
Connect JOIN Staff page with backend

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#305]
**Purpose**
A complete JOIN Staff page with data from the backend, seen on page 18 of the mockups

**Proposed Solution**
Do an API call on component mount (`useEffect()`) to get users by role of JOIN Staff (look up Enum in backend), then use a `.map` to format each result into the cards seen on the page

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Should get data from the backend and format it like the current faked data

**Mockup Screenshot or Page Number**
Page 18 (Page is already built out using fake data)
![image](https://user-images.githubusercontent.com/8600792/92681391-5ae96f80-f2e2-11ea-9d5b-17e5470d5179.png)

**Additional context**

**Comment by jls-github** [comment]
Happy to do this - won't this require a GET '/users' index api endpoint first?

**Comment by jls-github** [comment]
Ahh, I see https://github.com/codeforpdx/dwellingly-app/issues/296 is open to make that endpoint actually.

**Comment by jls-github** [comment]
Added the backend endpoint in https://github.com/codeforpdx/dwellinglybackend/pull/110

I'll continue working on this to populate the information in the front end.

TODO: We need to fix the filler data for tenants and tickets. We'll need to open an issue to create the relationship between the models and fill in the data in the json response.

**Comment by jls-github** [comment]
I created a PR that does most of this work (#378).
As noted in the PR notes, we'll need to keep a few things in mind.
1. The roles are still hard coded ints here. We'll want to change that eventually, and there is an issue out to do so.
2. Tickets and tenants are hard coded in the backend at this point. EDIT: I created a new issue for this in #379.
3. There is no staff seed data, only admin.
