### ISSUE TITLE
Enhance email endpoint to send multiple emails

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#308]
## Description

There is "currently" a TODO comment in the Email class stating that 

> #TODO add feature to send to multiple emails

I am creating this issue to replace that comment as I plan to remove it soon. 

@htharker42 Can you expand on the requirements for this feature request.

**Comment by htharker42** [comment]
We don't need to worry about batching emails yet, at least not in this version. I was thinking we would setup an email notification system at some point. The idea being that that the backend would periodically audit the existing tickets and dispatch emails based on how long they hadn't been reviewed, changes, other flags. In this use case, we would need to be able to send a batch of messages.
