### ISSUE TITLE
Notes for September 25th 2019

### ISSUE THREAD

**Issue by augustinevt** [codeforpdx/dwellingly-app#31]
Once the remote API is callable by the javascript client, we want do the following (potentially) :

Break out tickets for constructing the Emergency Number Page (because it is the simplest page that API return data for)

- someone can work on making the sidebar
- someone can work on getting the logo header up
- someone can work on listing the data

We should coordinate these efforts via the github project this ( overviewd by @astuteape ). 

Wade this is Treasure -- we should make status reports like this one here bi-weekly FOR IMPROVED COMMUNICATION :D

**Comment by astuteape** [comment]
Treasure and I worked on both the `master` and `main` branch to try and get things working. At this point, `master` is ahead of `main` by ~600 commits. However, the changes you all made last session that let you move past the auth were branched from `main`. We tried to merge the `august-two` branch to `master` locally to see what happened. Unfortunately, even after fixing a merge conflict, the pages still redirect to /login. @augustinevt, would you be able to look at making changes to `master` that allow us to hit the different routes like you did with `main`? Hope this makes sense, but we can all Slack between meetups too. Thanks for all the work on this.

**Comment by augustinevt** [comment]
Hey @astuteape + @trezp, I just pushed up a [PR for disabling auth on master](https://github.com/codeforpdx/dwellingly-app/pull/33) Sorry for it being so last minute! There is a note about merging to a different branch... let me know what you think but also feel free to merge! Will not be at the meeting tonight unfortunately, but I'll be online so feel free to ping me with anything!
