### ISSUE TITLE
Request for Access Buttons

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#312]
**Describe the bug**
Color of Request of Access Buttons do not match wire frames

**To Reproduce**
1. login as Admin scroll down

**Expected behavior**
![image](https://user-images.githubusercontent.com/32914953/92988939-1ea24480-f485-11ea-8818-27ada8fe3a5a.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/32914953/92988957-32e64180-f485-11ea-8e75-a3b89043d037.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 80.0.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cprice404** [comment]
so this issue is strictly about the color of the buttons?
