### ISSUE TITLE
Add Assign Property Manager Component to Add New Property 

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#314]
**Purpose**
Add Assign Property Manager component to the Add New Property Page. 

**Proposed Solution**
Pull users where role = 2 
populate a dropdown with list of property managers.name
return the property manager as part of the property package 

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ]pulls list of users where role = 2
- [ ]populates dropdown 
- [ ]creates a property with assigned property manager

**Mockup Screenshot or Page Number**
page 15
![image](https://user-images.githubusercontent.com/32914953/92989507-b43fd300-f489-11ea-8d42-15869cb233bc.png)

**Comment by ctb116** [comment]
I pushed a branch called AssignPropertyManager. I'm fairly new to this project so I think I'll need help understanding the api endpoints and getting anything like a key. Such as, I need to get the user in the code block below and then I can filter by role.

Should only one manager be allowed to be selected per property or should it be allowed that multiple managers can be selected?

```
    getManagers = () => {
        axios.get(`${process.env.REACT_APP_API_URL}`)
            .then((response) => {
                console.log(response)
            })
            .catch((error) => {
                alert(error);
                console.log(error);
            })
    };
```

**Comment by mtb116** [comment]
Progress is in the AssignPropertyManager branch: https://github.com/codeforpdx/dwellingly-app/tree/AssignPropertyManager

Having some trouble with context in the addProperty component. It returns as undefined though it is defined and working fine in other components. I am new to working with context so I am happy to keep picking at it but also good if someone wants to step in before the end of Sept.

**Comment by NickSchimek** [comment]
This issue is partially blocked by issue #370

**Comment by mtb116** [comment]
#369 I think this is the same issue. Progress is in branch AssignPropertyManger

Selected managers are being stored by id in an array at the moment.

**Comment by NickSchimek** [comment]
Yes, it looks like they're duplicate issues. @htharker42 @Chris-Boe would you agree?

**Comment by DaveTrost** [comment]
Hi Catherine (@ctb116)
I'm hoping to pick up this issue where you left off with it. I will work with Hugh and Chris tonight during the Dwellingly project meeting to make sure I understand the history here. 
Please reach out on Slack if you want to catch up on this in the future. Maybe we can pair on it this week?

**Comment by NickSchimek** [comment]
@DaveTrost Cathy has an open PR for this - you may want to check that out - I don't think it has been reviewed yet.

**Comment by mtb116** [comment]
Hey @DaveTrost 

I would love to pair up to finish this issue this week. We can address the latest comment from Chris in the PR. I'll reach out on Slack.
