### ISSUE TITLE
Connect Invite on Property Managers page to Backend

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#317]
**Purpose**
Accepts and Email address and send email address to api/email/invite endpoint.

**Proposed Solution**
When invite button is clicked, a component loads to accept the email address. 

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Component loads when Invite button is clicked
- [ ] Email address is accepted and sent to API for processing
- [ ] Clean up formatting to match wireframe

**Mockup Screenshot or Page Number**
![image](https://user-images.githubusercontent.com/32914953/92990016-5b723980-f48d-11ea-9b4e-7250da9f2fe7.png)

**Additional context**
Backend issue #316

**Comment by yhafez** [comment]
Pending completion of issue #316 in order to send input to api route

**Comment by NickSchimek** [comment]
The Add New button invites a user. I'm unclear on what the difference is between the invite button, and the add new button.

**Comment by Chris-Boe** [comment]
Closing this as we're going to remove the button instead of implementing it. The Add New functionality already provides a way to add a new Property Manager
