### ISSUE TITLE
Add password requirements

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#319]
**Purpose**
To add security, we should have some password requirements for users when they create an account or reset/change their password

**Proposed Solution**
Think minimum length, character requirements

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Minimum length of 8 characters
- [ ] At least one number
- [ ] At least one capital and one lowercase letter
- [ ] I'd also recommend at least one special character, but check with @htharker42 if we should
- [ ] These validations should be done on BOTH the backend and frontend

**Mockup Screenshot or Page Number**
This would show up as info and warnings on the Create Account, Reset Password, and Change Password pages

**Comment by NickSchimek** [comment]
We may need to add a validation for the maximum length of the password, both on FE and BE.
The current implementation proposed in PR codeforpdx/dwellinglybackend#104 will ignore any characters beyond the maximum length of 72. See https://github.com/pyca/bcrypt#maximum-password-length for more info.

I'm not sure if limiting the password length to 72 will impact our users. Specifically thinking of users who might use password management tools to generate long unique passwords.

**Comment by NickSchimek** [comment]
It doesn't make sense to have this issue labeled as both frontend and backend, and it looks like this has been completed for the frontend. If this is something we should do in the backend then lets get a backend ticket created to match the frontend validation.
