### ISSUE TITLE
Docker for developer setup

### ISSUE THREAD

**Issue by gussmith23** [codeforpdx/dwellingly-app#320]
**Purpose**
Docker can be used to set up projects for new developers to easily start developing -- you can run one command and get a server w/ hot reloading running in a docker container. See how Seattle's [Conviction Vacation](https://github.com/openseattle/convictionvacation#development-environment-with-docker) project handles this! I heard there was discussion of using Docker to set up the Dwellingly projects. I just wanted to note the fact that Docker can make developer setup a lot easier too, if it's set up in the right way! 

**Proposed Solution**
See [this link](https://github.com/openseattle/convictionvacation#development-environment-with-docker) to see how another project sets up Docker for development.

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ]

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

**Additional context**

**Comment by NickSchimek** [comment]
I'm closing this because docker doesn't solve all issues. And unless we have someone dedicated to keeping it running it can potentially be more maintenance than we can support.

It's also good practice for budding developers to learn how to setup local dev environments on their own machines.
