### ISSUE TITLE
Redo Add Join Staff Member form

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#326]
**Purpose**
A formik form to actually create a new staff member (right now it's sending dummy data)

**Proposed Solution**
Use a formik form to collect the necessary info and send it to the backend.
Should be done after issue #322 

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Add a formik form to match the mockups
- [ ] Add validation to fields
- [ ] Send the info to the /user/invite endpoint on the backend (requires #322 )

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

**Additional context**

**Comment by asharonbaltazar** [comment]
Is it possible to do this without the backend?
