### ISSUE TITLE
Update response statuses for all lease endpoints

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#336]
## Description
Some response endpoints do not return the correct status for that endpoint.

For example. The create endpoint returns 200 when it should be 201.

There are many resources on the web explaining appropriate RESTful status codes.

## Acceptance Criteria

- [ ] Update the integration test to check for the correct status code
- [ ] Update endpoints

You may notice that the response.json response should be updated as well. Fixing that is out of scope of this issue and will be handled in a separate issue.

**Comment by yunnie** [comment]
Attempting to delete a lease that is not in the database currently returns: {'Message': 'Lease Removed from Database'} and status code 200. Should this return a different message indicating that the lease was not found? Something like {'Message': 'Lease Not Found'} along with status code 404?

**Comment by NickSchimek** [comment]
> Attempting to delete a lease that is not in the database currently returns: {'Message': 'Lease Removed from Database'} and status code 200. Should this return a different message indicating that the lease was not found? Something like {'Message': 'Lease Not Found'} along with status code 404?

Thanks for asking. Status code 404 means the page was not found (or the route does not exist in regards to api's). In this case the route does exist but the entity being passed into the route could not be processed (in this case deleted). A 422 (unprocessable entity) would be the correct status code to return.

**Comment by NickSchimek** [comment]
> Something like {'Message': 'Lease Not Found'} along with status code 404?

Yes, except 422 status code is better.
