### ISSUE TITLE
Audit and update all json responses for the lease endpoint

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#337]
## Description
Some json responses are not correct for one or more of the lease endpoints

For example: One json response simply returns `201` status code when it should return an appropriate message or perhaps a JSON representation of the object like the other endpoints.

## Acceptance Criteria

- [ ] Update the integration test to check for the appropriate JSON response
- [ ] Update endpoints

You may notice that the status codes should be updated as well. Fixing that is out of scope of this issue and will be handled in a separate issue.

**Comment by yunnie** [comment]
According to Issue 332, use "message" instead of "Message". Remember to set the option for pyjwt library to return "message" as well.

**Comment by yunnie** [comment]
What should the create end point return? Should it just be a json with the id number, like {'id': 4}? Or would it be a json with the fields in the lease table?

**Comment by NickSchimek** [comment]
> What should the create end point return? Should it just be a json with the id number, like {'id': 4}? Or would it be a json with the fields in the lease table?

I didn't see anything in the docs regarding the creation of a lease. We will probably need to return the created lease at some point.
For now, I think it is fine to do `{'message': 'Lease created successfully'}` - and when we get more information we can update accordingly.
