### ISSUE TITLE
Fix intermittent failing test

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#347]
**Describe the bug**
Sometimes this test passes, and sometimes it fails. See if this can be improved to be more robust.

**To Reproduce**
This is an intermittent failure. So it is difficult to reproduce

The test in question is `tests/integration/test_tickets.py` - `test_tickets_POST`

**Expected behavior**
The test should never fail intermittently

**Screenshots**
<img width="1194" alt="Screen Shot 2020-09-18 at 8 49 56 AM" src="https://user-images.githubusercontent.com/19519317/93539635-5d0b9800-f98c-11ea-8a45-eb7159c89726.png">

**Comment by sokampdx** [comment]
I just created the ticket https://github.com/codeforpdx/dwellingly-app/issues/344 right before you.

**Comment by NickSchimek** [comment]
Thanks! I should've checked before creating this ticket.
