### ISSUE TITLE
TypeError crashes frontend app

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#350]
**Describe the bug**
When clicking tickets on the side nav bar the app crashes due to a type error

TypeError: Cannot read property 'length' of undefined

**To Reproduce**
start servers
Log in as user1
click tickets in side nav-bar

**Expected behavior**
The app should not crash

**Screenshots**
<img width="1055" alt="Screen Shot 2020-09-18 at 1 23 28 PM" src="https://user-images.githubusercontent.com/19519317/93558663-e2a53d00-f9b8-11ea-9283-723d3bc3be4b.png">

**Comment by NickSchimek** [comment]
Update: I'm not able to reproduce this anymore. After I logged the user out. shutdown servers. reseeded db, started servers and logged in. The issue went away. Perhaps this is related to issue #349 - @Chris-Boe do you have any insight on this? Perhaps we should close this ticket for now.

**Comment by NickSchimek** [comment]
Also I was creating resources when playing with the app. It's possible that one of the resources I created caused this error.

**Comment by Chris-Boe** [comment]
I think we can safely close this
