### ISSUE TITLE
Flask-mail is unmaintained for last 6 years

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#351]
We may want to move off of the Flask-mail extension soon. I went to look through their source code and realized it is no longer maintained. It seems there are some forked versions of it out there, along with completely different libraries that could be used. We should find one that is well maintained, easy to use, and preferably popular.

**Comment by NickSchimek** [comment]
There is Flak-Mail <- Notice the capital 'm' which is meant to replace the unmaintained Flask-mail. https://github.com/waynerv/flask-mailman

I think this may be the easiest and possibly best solution as our current implementation should still work without and as a bonus we should have less bugs.

**Comment by NickSchimek** [comment]
The repo for Flask-mail has been deleted, but its still on pypi. 😱 We should migrate soon.

**Comment by htharker42** [comment]
Issue discussed we will be moving to Flask-Mailman
