### ISSUE TITLE
Enable CORS protection for specific origin

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#352]
**Purpose**
Should only allow the frontend domain access to the backends resources. Currently setup to allow a request for a resource from any origin. https://github.com/codeforpdx/dwellinglybackend/blob/development/app.py#L104

This may need to be implemented closer to our first production deployment. Read more about [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

**Proposed Solution**

https://flask-cors.readthedocs.io/en/latest/#resource-specific-cors

**Acceptance Criteria**

- [ ] Should only allow CORS from a specific origin

**Comment by yunnie** [comment]
It looks like CORS is already implemented. I checked the 'app.py' file, and CORS is implemented in the 'def create_app(env)' function.

**Comment by NickSchimek** [comment]
Hmm I don’t think it is enabled though. Once I get back on the computer I
will check it out and let you know.

**Comment by NickSchimek** [comment]
Yes, you are correct that it is already implemented, and it is also already enabled. However, since we are not technically building an API that anyone can access. We only want to allow our frontend to access our resources. 

Currently the CORS implementation allows any request from any origin. Upon instantiation of the CORS object we can tell it to only accept requests from our frontend origin. See https://pypi.org/project/Flask-Cors/#resource-specific-cors - it looks like we can pass in an `origin` parameter to allow requests from the specified list of origins. What do you think?

I think we can implement this via a config VAR. We can leave it open to all origins for dev and test and then specify the frontend origin for production. I think we already have a frontend origin config var that will be setup when we deploy.

**Comment by yunnie** [comment]
That makes perfect sense. Do we know what the frontend origin in production will be?

**Comment by NickSchimek** [comment]
No, not to my knowledge.

**Comment by yunnie** [comment]
It might make more sense to create an origin environmental variable, so that updating to the production origin is not forgotten when it's deployed. What do you think?

**Comment by NickSchimek** [comment]
Sounds good!
