### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'full_name'

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#353]
**Describe the bug**

App fails to create a new property. I suspect there are some association we are not enforcing here. Hence, when the seed data is incorrect missed associations do not raise errors at initialization.

```
    return rentalproperty.json(), 201
  File "~/dwellinglybackend/models/property.py", line 51, in json
    'propertyManagerName': property_manager.full_name(),
AttributeError: 'NoneType' object has no attribute 'full_name'
```

**To Reproduce**

1. Start backend and frontend servers
2. Log in as `user1@dwellingly.org`
3. Visit `add/property`
4. Fill out form
5. submit

**Expected behavior**

It's preferable the app never crashes

**Comment by sokampdx** [comment]
This is probably related to https://github.com/codeforpdx/dwellingly-app/issues/274

**Comment by NickSchimek** [comment]
> This is probably related to #274

274 is a feature request. This bug showed up after implementing that feature for the backend.

**Comment by NickSchimek** [comment]
But yes, it is related in a way. However, I don't think it has anything to do with the implementation of the feature, but rather poor seed data due to FK's being allowed to be null in the db when they probably shouldn't be.

**Comment by NickSchimek** [comment]
Replaced by issue #370 and #369

**Comment by NickSchimek** [comment]
Replaced by issue #370 and #369
