### ISSUE TITLE
Setup/configure a db migration tool

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#362]
**Purpose**

Should use a migration tool to simplify db alterations

**Proposed Solution**

Probably just use flask-migrate https://flask-migrate.readthedocs.io/en/latest/

**Comment by yunnie** [comment]
@NickSchimek, @htharker42 flask_migrate is not as frequently updated as alembic. But it does look like Miguel Grinberg is still giving talks and writing articles on flask migrate. The main advantage of using flask_migrate is ease of use, and that it integrates the alembic command line interface into the flask command line interface. It is relatively straight forward to implement alembic directly to manage the migrations. The main advantage is that alembic is an active project, and looks pretty well maintained. Any preferences?

**Comment by NickSchimek** [comment]
Thanks @yunnie - I have no preference. Ease of use for flask-migrate sounds
a bit interesting. However ease of use might come at a cost too.

Whichever one you think is best.
