### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#364]
## Description

The wiki page looks great. I think it would be good to incorporate the info there into the readme.

This is for the BACKEND repository at https://github.com/codeforpdx/dwellinglybackend

The wiki is at https://github.com/codeforpdx/dwellinglybackend/wiki

**Comment by topan507** [comment]
Good luck..

**Comment by russellneville** [comment]
Incorporated wiki content into README.md
