### ISSUE TITLE
Audit/Fix status codes for Ticket resource

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#365]
## Description

500 status code means internal server error. There is no need to return this code. It is automatically done when there is an internal error and the app crashes.

Remove try and except clauses. Here we are catching all exceptions and returning 500 status code. Flask already has built-in error handling. If an exception is thrown then the proper status code will be returned. 
See other resource endpoints (controllers) for other alternatives

### Acceptance Criteria

- [ ] no more 500 status codes explicitly returned 

### Scope
 - This is scoped to the ticket resource file in the backend https://github.com/codeforpdx/dwellinglybackend/blob/development/resources/tickets.py

**Comment by ujjwal404** [comment]
Hi, I'm new to open source and I would like to work on this during hacktober fest. Can you please assign it to me.

**Comment by NickSchimek** [comment]
It's all yours @ujjwal404

**Comment by ujjwal404** [comment]
Hi @NickSchimek . I've removed all the try and except clauses in tickets.py file in pr #119 . Please have a look and let me know if any change is required. I'm new to github and I don't know why my pr has failed. Can you please help.
