### ISSUE TITLE
Replace hard coded Role ints across FE app

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#372]
## Description

This is to prevent serious bugs. If it's not done already we should define an Enum in one place to extract the correct value for a Role. It doesn't matter if this is in a test file or application code. Replace all hard coded ints with a call to retrieve the correct value from a single source. 

@jls-github identified two places where we are using hard coded ints. 🙇‍♂️ 

## Acceptance criteria

- Replace hardcoded ints in `dashboard.js` currently at line # 35 and 42 with a call to the FE enum.
- Remove any other hard coded ints that you can find.

**Comment by jls-github** [comment]
I'll work on this Thursday night. 

My thought is to create a file that stores a RoleEnum hash, formatted exactly like the backend for consistency, and we'll just import that into each place that we want to identify the role. 

`RoleEnum = {
  PENDING: 0,
  TENANT: 1,
  ...
}`


Is there any best practice on where to keep this file?

**Comment by NickSchimek** [comment]
Let's get input from @Chris-Boe on this. I was under the impression that there was already a Role enum in the FE.

**Comment by jls-github** [comment]
Sounds good.
