### ISSUE TITLE
Update JSON response for indexing Join Staff

### ISSUE THREAD

**Issue by jls-github** [codeforpdx/dwellingly-app#379]
**Purpose**
Currently, our get '/user' endpoint supplies all users of a supplied role with their basic information. However, it does not supply how many tenants and tickets they manage. This is requested from the frontend on the JOIN staff page (see #305) We need to supply this information to the front end through an endpoint.

**Proposed Solution**
The fix would be fairly simple to implement.  We can just add the number of tickets and tenants to the json object returned by the get '/user' endpoint.

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] get '/user' should include the number of tenants and tickets related to each returned user.

**Mockup Screenshot or Page Number**
N/A

**Additional context**
N/A

**Comment by jls-github** [comment]
@NickSchimek Would you recommend a different direction?

**Comment by NickSchimek** [comment]
This sounds like a good solution @jls-github . However, there are some associations missing that need to be put in place first.

Tenants have many tickets. A user (possibly Join staff only) can be assigned a ticket. Currently the user/ticket association and validation does not exist. I'm going to place the blocked label on this for now since we will need to get those associations in place first.

**Comment by NickSchimek** [comment]
> get '/user' should include the number of tenants and tickets related to each returned user

It might be better to send back an array of tenants and tickets for the related staff member. Frontend can easily calculate the size of the array. < - I think that data will be needed for other pages anyway.

**Comment by jls-github** [comment]
Good points, @NickSchimek 
I'll look into creating that association and then editing the endpoint response. Then we should be able to finish up the last couple front end details and finish the issue.

**Comment by NickSchimek** [comment]
@jls-github Feel free to look into it, however please hold off on any implementation as of now. There are some changes I will be introducing to the backend, and if there are not issues for this then it may not be ready to be implemented yet. Ideally the frontend should never be blocked by the backend, because if the frontend and backend agrees on a data structure then the frontend can mock the backend and test out an implementation.

**Comment by NickSchimek** [comment]
It might be better to simply return the numbers. With the new design we can have unique json responses for every request. As far as I know, only JOIN staff can have tenants assigned, not property managers as they have a very limited set of data they can access. My worry is that if we add the reference and update the JSON response now that may accidentally proliferate to other JSON responses that should not that that data.

**Comment by jls-github** [comment]
Okay. I'll wait off on building the associations and changing the endpoint until we are ready.

**Comment by NickSchimek** [comment]
I don’t think the user table has any associations on it yet. Which seems
strange. I will review the reqs later this morning, and see about getting
that issue created. Do u think it would be best to return some dummy data
for now so that you have a full response to work with in the front end?

**Comment by jls-github** [comment]
@NickSchimek That sounds like a good idea. If we supply dummy data in the endpoint, we can finish building the front end feature (This might have been what you meant when you said it isn't good to let the back end block the front end). 

Do you think it is better to return an array of tenants and tickets, or just the amount? My initial inclination would have been to return a number when we inquire about many users, and an array when we inquire about one user. Though, returning an array in both endpoints does give us more flexibility in the future, and it's not exactly difficult to write ".length" 😀

**Comment by NickSchimek** [comment]
Let’s do an amount. Is the ticket amount the number of open tickets?

**Comment by NickSchimek** [comment]
@jls-github It seems the functionality was already implemented to return dummy figures for tenant and tickets in the users response. Is what your needing different than what was done here: codeforpdx/dwellinglybackend/pull/110 ?

**Comment by jls-github** [comment]
@NickSchimek my goodness, you're right! I had forgotten that we had done that! Geez, I'm the one who wrote that PR too.

**Comment by jls-github** [comment]
So we don't need to mock out dummy data at the moment then. We'll just need to implement the actual data when we can. I'll adjust the front end PR and we should be done with it for now.

**Comment by NickSchimek** [comment]
OK. I think we can close this issue then?

> If we supply dummy data in the endpoint, we can finish building the front end feature (This might have been what you meant when you said it isn't good to let the back end block the front end).

No, that's not what I meant. We can talk more about this tomorrow.

**Comment by jls-github** [comment]
> OK. I think we can close this issue then?

We do eventually need to supply the actual data in the endpoint, rather than just filler data. Though, if that is dealt with in an issue elsewhere, we can certainly close this.

**Comment by NickSchimek** [comment]
Closing this as I'm not sure what this is for anymore. If this should be re-opened then please supply more data about what Frontend problem this is solving. I'm not entirely sure we should be retrieving tenants when the frontend requests a specific user. Not all users will have tenants assigned to them, and there are other ways to get a list of tenants assigned to a specific user.

**Comment by NickSchimek** [comment]
Closing this as I'm not sure what this is for anymore. If this should be re-opened then please supply more data about what Frontend problem this is solving. I'm not entirely sure we should be retrieving tenants when the frontend requests a specific user. Not all users will have tenants assigned to them, and there are other ways to get a list of tenants assigned to a specific user.
