### ISSUE TITLE
Seed the db with test users with JOIN STAFF role

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#386]
**Purpose**
What will this feature provide?
More easily test workflows with JOIN STAFF users

**Proposed Solution**
If you have an idea on how to implement this feature, please share!
edit the seedData.py file to add the users

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Should add 3 users of JOIN STAFF role level

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

**Additional context**

**Comment by gussmith23** [comment]
Do join staff fall under any of the existing roles in the role enum? Or they need their own new enum entry?
```python3
class RoleEnum(Enum):
    PENDING = 0
    TENANT = 1
    PROPERTY_MANAGER = 2
    STAFF = 3
    ADMIN = 4
```
Are Join staff == STAFF?

**Comment by gussmith23** [comment]
See the linked draft PR. I'm not sure if this is actually what is needed. Let me know!

**Comment by NickSchimek** [comment]
@gussmith23 
> Are Join staff == STAFF?

Yes. join staff is equal to staff. The draft PR looks good.
