### ISSUE TITLE
Replace all necessary references to `dateUpdated` with `updated_at` and 'created' or 'added' with 'created_at'

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#390]
# Description

The `dateUpdated` field on the Lease Model in the backend is being removed. All models now have an `updated_at` field that will be used going forward to track object update times.

~I found two files that are using the name `dateUpdated` - If necessary replace it with `updated_at`~
 - ~`dwellingly-app/stashed/src/data.js`~
 - ~`dwellingly-app/stashed/src/pages/property-manager-dashboard/DateUpdatedRenderer.jsx`~

Don't worry about any files in the /stashed folder.

**Acceptance criteria**
 - Replaced all `dateUpdated` fields with `updated_at` where relevant.
 - Replaced all 'created' or 'added' fields with 'created_at' where relevant.

**Comment by Chris-Boe** [comment]
~I think this can be closed in lieu of #310 , there will be a PR on that issue that will contain the same necessary work~
Misread this and thought the issue was for the backend 🤦‍♂️
