### ISSUE TITLE
Move database commands off of the db namespace

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#391]
# Description

Eventually we will need to install flask-migrate for database migrations. Flask-migrate will overwrite the db group we currently have setup for creating/reseeding our dev sqlLite database. https://flask-migrate.readthedocs.io/en/latest/#command-reference

 - Setup a new namespace/group to run our commands within so that we don't lose access to them when flask-migrate is installed.

**Comment by yunnie** [comment]
Since we're using Alembic directly, without the flask-migrate wrapper, there isn't a name space conflict. We don't need to move the current 'flask db' commands to another namespace.

**Comment by NickSchimek** [comment]
Excellent! Let's close this issue.
