### ISSUE TITLE
Fix routes properties/name to use an unique identifier

### ISSUE THREAD

**Issue by sokampdx** [codeforpdx/dwellingly-app#395]
**Describe the bug**
The properties/name routes should use id instead of name OR enforce an unique name for PropertyModel
Because, the name is not unique in the PropertyModel and the find_by_name method only return the first row if multiple property has the same name. There is a risk of get/update/delete the wrong property.
https://github.com/codeforpdx/dwellinglybackend/blob/fbff27efaa80ce29d1cf260b14c0fa560b37b5b8/models/property.py#L58

see 
```
# | GET    | `v1/property/:name`  | Gets a single property     |
# | PUT    | `v1/property/:name`  | Updates a single property  |
# | DELETE | `v1/property/:name`  | Deletes a single property  |
```

**Expected behavior**
We should get an unique identifier to ensure an unique property is being get/update/delete.

**Comment by gussmith23** [comment]
I'm working on this! Will post a draft PR in a few minutes.

**Comment by gussmith23** [comment]
@sokampdx pointed out: we don't know what the FE will do if we remove the route to get properties by name. @Chris-Boe Anthony thought you might know. How hard would it be to change the uses of the get-by-name route to a get-by-id route, on the frontend? I can take a look more later this week, too.

**Comment by sokampdx** [comment]
I see it is using in here:
./src//views/Tenant/TenantView.js:109:    const propertyUrl = `/api/properties/${tenant.propertyName}`;

**Comment by Chris-Boe** [comment]
You'll just have to write a PR to change the frontend, and then we'll try to merge them at the same time so development is in a happy state!

**Comment by Chris-Boe** [comment]
We should also make sure "Property Name" is unique in the backend if we haven't done that already. I can't think of a reason to have multiple properties with the same name, it would likely cause confusion

**Comment by gussmith23** [comment]
So I'm trying to break this down into the most simple concrete tasks, mainly because I'm new and trying hard not to break things! Right now I have:
1. Add a properties/id route
2. Modify properties/name route -- remove it? make name unique? make it return a list of matched properties? or maybe leave it as is?
3. In the frontend, modify usages of of the properties/name route -- transition to use properties/id where possible? keep them as using properties/name?

**Comment by gussmith23** [comment]
Talking to @NickSchimek , it sounds like the best course forward is to transition things to using the properties/id route, rather than only making names unique. Question I have is: do we still want to make names unique? It won't be necessary to do so anymore, it seems like.

**Comment by Chris-Boe** [comment]
I think we should replace the properties/name route with a properties/id route and make names unique. That will make sure that users don't accidentally create two identical properties and get them mixed up

**Comment by NickSchimek** [comment]
Yes, I agree with @chrisboe

**Comment by gussmith23** [comment]
Hi all, I've been working on this slowly. I'm hitting an issue where, after enabling unique=True on the name field, some of the tests are failing. I've fixed some of them -- some of them were running test fixtures multiple times, causing the same property to be added multiple times. However, I'm having trouble with this test:
```python
def test_post_property(client, auth_headers, new_property):
    property = new_property.json()
    property['name'] = "new_property"

    """The server should check for the correct credentials when posting a new property"""
    response = client.post("/api/properties", json=property)
    assert response.status_code == 401

    """The server should successfully add a new property"""
    import pdb; pdb.set_trace()
    response = client.post("/api/properties", json=property, headers=auth_headers["admin"])
    assert response.status_code == 201

    """The server should return with an error if a duplicate property is posted"""
    response = client.post("/api/properties", json=property, headers=auth_headers["admin"])
    assert response.get_json() == {'message': 'A property with this name already exists'}
    assert response.status_code == 401
```

It's giving me a uniqueness constraint violation when we should instead be getting a 201. I am trying to debug where the property is getting added the first time. Any thoughts on how I might debug this? It would be ideal if I could see what's going in the database, and when, but I'm not sure if that's possible.

Thanks all!

**Comment by sokampdx** [comment]
@gussmith23 The error you see is because the existing db has a property name test1 from seedData.py and we added another new property that named test1 as well from conftest.py. However, see the comments right above yours. I think both Chris and Nick want to replace the route to use id instead of name.

**Comment by NickSchimek** [comment]
@gussmith23 if you would like to pair on this at anytime then let me know. It is most likely the seedData.py file as Anthony pointed out.

**Comment by gussmith23** [comment]
@sokampdx thanks for the feedback. And yes, I am planning to replace the name route, but also to make name unique -- this error comes up when I make name unique. I could also split those into two PRs if that would be better!

**Comment by NickSchimek** [comment]
However you prefer to do it is fine by me @gussmith23
