### ISSUE TITLE
Allow multiple property managers name listed in manage property page

### ISSUE THREAD

**Issue by sokampdx** [codeforpdx/dwellingly-app#396]
**Purpose**
What will this feature provide?
This is to implement the listing of multiple property manager under a single property in manage/properties page. (see figma p14)

**Proposed Solution**
Maybe we should use the PropertyManager from the json instead of the PropertyManagerName. 
see https://github.com/codeforpdx/dwellingly-app/blob/7529eeac94d8f66d5deb23f4b13ad7ee3df5ffd7/src/views/managers.js#L27
We should create a follow ticket to remove PropertyManagerName in backend when this completed. 

**Acceptance Criteria**
- [ ] allow listing for multiple managers.

**Mockup Screenshot or Page Number**
See Figma p14

**Additional context**
Need to have https://github.com/codeforpdx/dwellinglybackend/pull/131 merged first (#370 )

**Comment by DaveTrost** [comment]
The backend PR codeforpdx/dwellinglybackend#131 has been merged. This functionality is now working. I recommend we close this issue.
