### ISSUE TITLE
Refactor tenant resource

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#398]
**Purpose**
Refactor the tenant resource to use the new db methods `find`, `create`, `update`, `delete`

**Acceptance Criteria**
- [ ] Add the BaseInterfaceTest to the tenant test and create unit tests for all public methods. see [this commit](https://github.com/codeforpdx/dwellinglybackend/blob/31610de13449c002d2394bfa7b2e48a8c12e5b1e/tests/unit/test_lease.py) for an example.
- [ ] Use marshmallow for input validation
- [ ] Use the new db methods to refactor the tenant resource
- [ ] Refactoring may cause some of the tests to become redundant, these tests can be removed. Will most likely need to only test the happy path for each action. (one test per action).

- See the lease files for an example. https://github.com/codeforpdx/dwellinglybackend/blob/31610de13449c002d2394bfa7b2e48a8c12e5b1e/resources/lease.py

**Scope**

Continue to use the .json method for serializing the data.  Implementing marshmallow to use as the serializer will be completed in another ticket

**Comment by yunnie** [comment]
It looks like this has already been completed.

**Comment by NickSchimek** [comment]
Yeah, it looks like it is complete, although I see a couple things in the resource file that need to be changed.

The tenant integration tests need to be refactored/updated still. We can close this issue out and open up two new issues

**Comment by NickSchimek** [comment]
Closing in favor of:
#591
#592
#593
