### ISSUE TITLE
Refactor emergency contact resource

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#399]
**Purpose**
Refactor the Emergency Contact resource to use the new db methods `find`, `create`, `update`, `delete`

**Acceptance Criteria**
- [x] Create schema to use marshmallow for input validation
- [x] Add the BaseInterfaceTest to the Emergency Contact test and create unit tests for all public methods. see [this commit](https://github.com/codeforpdx/dwellinglybackend/blob/31610de13449c002d2394bfa7b2e48a8c12e5b1e/tests/unit/test_lease.py) for an example.
- [x] Add the BaseInterfaceTest to the Contact Number test and create unit tests for all public methods. see [this commit](https://github.com/codeforpdx/dwellinglybackend/blob/31610de13449c002d2394bfa7b2e48a8c12e5b1e/tests/unit/test_lease.py) for an example.
- [x] Use the new db methods to refactor the Emergency Contact resource
- [ ] Refactoring may cause some of the tests to become redundant, these tests can be removed. Will most likely need to only test the happy path for each action. (one test per action).

- See the lease files for an example. https://github.com/codeforpdx/dwellinglybackend/blob/31610de13449c002d2394bfa7b2e48a8c12e5b1e/resources/lease.py

**Scope**

Continue to use the .json method for serializing the data.  Implementing marshmallow to use as the serializer will be completed in another ticket

**Comment by gheelan** [comment]
I'm going to try and take this one on! Think I just need to be added officially before I can assign it to myself.

**Comment by NickSchimek** [comment]
@sokampdx You may be able to do issue #374 at the same time.
