### ISSUE TITLE
FRONTEND: Connect Property Managers page to backend

### ISSUE THREAD

**Issue by dbridenbeck** [codeforpdx/dwellingly-app#401]
**Purpose**
Currently the `/manage/managers` view is using dummy data located in `/src/views/dummyData/` and we should instead be hitting api to get this data from the DB.

**Proposed Solution**
- use axios to hit the `/users/role` api endpoint with a payload of `"userrole": "2"`, where 2 is the enum value for PROPERTY_MANAGER
- use useState to store the result of the API endpoint
- use the reusable `<Modal />` component to display there was an error if the axios call fails
- connect the data stored in useState to the data prop in `<BootstrapTable />` (this may need to be transformed in some way to display data properly)

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] View should display a list of property managers, without using the dummyData file
- [ ] View should be tested at some level (maybe this isn't really that important, but would be a bonus!)
- [ ] When clicking a property manager's name, it should successfully take you to the `/manage/managers/:id` page (see screenshot below)
![Screen Shot 2020-10-21 at 9 16 02 PM](https://user-images.githubusercontent.com/49624436/96824003-a4010900-13e2-11eb-8ba3-6dbe59a9bc28.png)

**Additional context**
- The dummyData exists because back when this view was created the backend didn't provide the right amount of data needed when hitting the `users/role` endpoint

**Comment by DaveTrost** [comment]
~~It looks like this work is complete. Can someone provide a status update?~~
Please ignore this comment. I see now the data is not coming from the API. There is no network call to GET managers when visiting this page.

**Comment by dbridenbeck** [comment]
No worries! I’m almost finished with this. Just need to add some toast notifications and some tests. I should be done with this by the end of the week.

Also, HI DAVE! Missed ya buddy! :)

**Comment by DaveTrost** [comment]
> Also, HI DAVE! Missed ya buddy! :)

Thanks Darren! I missed this crew and I'm glad to be back! We'll have to catch up soon
