### ISSUE TITLE
Create string enum to use as ticket status

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#404]
**Purpose**
The widgets/tickets resource and possibly other places have hard code strings to denote the status of a ticket. 
Replace hard-code strings with enum

A ticket status can be one of the following:

- `New`
- `In Progress`
- `Closed`

**Proposed Solution**
Create a string enum that can be used.

**Acceptance Criteria**
- [ ] Enum is being used in place of hard code strings

**Comment by yunnie** [comment]
Is the intent here to create a string enum in the widgets/tickets resource in the front end? Or an enum in for either the model/tickets or resources/tickets on the backend? Or both?

**Comment by NickSchimek** [comment]
This is specifically for the backend. The main intent is to remove duplicative hard coded strings with a single source point. Wether it is implemented as an enum, constants, or method calls I think is of little importance at this point in time. Although the implementation should probably be placed in the ticket model.
