### ISSUE TITLE
Create fixture for the NotesModel

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#411]
**Purpose**
Fixtures will be used for testing rather than the seeds file. This will help speed up tests and prevent unnecessary test failures due to changing seeds.

**Proposed Solution**
There are already fixtures for lease tenant and property models that can be used as an example.

see PR codeforpdx/dwellinglybackend/pull/135 for an example.

**Acceptance Criteria**

- [ ] Create test for fixture that checks the fixture is created successfully. The test can be placed in `tests/unit/test_note.py`
- [ ] Create Fixture for NoteModel

Blocked by #414

**Comment by yunnie** [comment]
This is out of date. I created [notes figures](https://github.com/codeforpdx/dwellinglybackend/blob/development/tests/factory_fixtures/notes.py) when I created tests for the notes schema.
