### ISSUE TITLE
Create fixture for tickets model

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#414]
**Purpose**
Fixtures will be used for testing rather than the seeds file. This will help speed up tests and prevent unnecessary test failures due to changing seeds.

**Proposed Solution**
There are already fixtures for lease tenant and property models that can be used as an example.

see PR codeforpdx/dwellinglybackend/pull/135 for an example.

**Acceptance Criteria**

- [ ] Create test for fixture that checks the fixture is created successfully. The test can be placed in `tests/unit/test_ticket.py`
- [ ] Create Fixture for TicketModel

~~Blocked by #415  - because current behavior is that a ticket must have an assigned user when created~~

**Comment by whiletrace** [comment]
closed this issue, fixture for tickets model was created in https://github.com/codeforpdx/dwellinglybackend/pull/164

**Comment by NickSchimek** [comment]
Whoops, Thanks @whiletrace - sorry about that. I guess I needed to label issue #413 as blocked by this issue. I thought that PR was a bit too big for the issue, and now I know why.
