### ISSUE TITLE
Update payload for change password form

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#418]
**Purpose**

Currently the change password form is only sending the 'password' field as a payload. It should send the entire form to the backend for processing so that the backend can do its own validation on the form. This will enable us to fix a bug that currently allows a user to change their password without inputting the correct current password.

**Acceptance Criteria**

- [ ] The payload request should include all fields

**Comment by Jam52** [comment]
Hi, could you assign me this issue? thanks.

**Comment by NickSchimek** [comment]
OK. sure. It's all yours.

**Comment by NickSchimek** [comment]
Let's ensure these field names are used in the payload.
```
current_password
new_password
confirm_password
```

**Comment by Jam52** [comment]
Ok, thanks ill give it a go.

**Comment by NickSchimek** [comment]
@Jam52 How is it going on this?

**Comment by Jam52** [comment]
Hi @NickSchimek sorry for the delay, I have been unwell over the last week. Just catching up hopefully have some time today/tomorrow. Best, J

**Comment by NickSchimek** [comment]
Ok. Thanks for the update. I hope you feel better soon.

**Comment by Jam52** [comment]
Hi @NickSchimek the payload already had all three fields but were named:
current
new
confirm

I've updated them as requested and sent a PR. It was interesting learning about formik!

**Comment by NickSchimek** [comment]
@Jam52  - The payload does not have all three fields. The form has all three fields, however the payload is only sending one field. We need all three fields sent. Please see the comment on the PR. Let me know if you have any questions. Thanks
