### ISSUE TITLE
Handle possible db session errors

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#421]
**Describe the bug**
When a db session occurs then the db needs to be explicitly rolled back.
```
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError)
...
(Background on this error at: http://sqlalche.me/e/13/e3q8) (Background on this error at: http://sqlalche.me/e/13/7s2a)
```

**To Reproduce**
You can reproduce within a `flask shell` environment

issue a `save_to_db()` that would cause an exception to be raised at the db level such as unique field violations or any validation error handled at the db level that is not checked at the application level. 

**Expected behavior**
the session is programmatically rolled back and an error is returned to the user.

**Comment by Chris-Boe** [comment]
The db transaction looks like it already gets rolled back, just not the context session in flask. Is this issue just to wrap these 500 errors in a proper error message to the user? Or is it to make every session in flask rollback when the db gets rolled back? (which I don't think we'll need to do since we shouldn't be doing anything further with the session when something fails, it should just stop processing and return a failure to the user)

**Comment by NickSchimek** [comment]
> The db transaction looks like it already gets rolled back, just not the context session in flask.

It looks I didn't word the issue quite right. However, from what I understand:

The db transaction is rolled back, however the session transaction becomes inactive and must be explicitly rolled back. This seems to be referring to the [db session](https://docs.sqlalchemy.org/en/13/orm/session_api.html#sqlalchemy.orm.session.Session) in sqlalchemy, and not pertaining to anything specifically in flask.

The link here: https://docs.sqlalchemy.org/en/13/errors.html#error-7s2a
And here: https://docs.sqlalchemy.org/en/13/faq/sessions.html#faq-session-rollback

Provide some useful information on how every app should wrap the call to `session.flush` and `session.commit` to catch any potential issue. And yes, ultimately we should send an appropriate error message back, and to go the extra mile (if we want), notify the dev team that such an error occurred so that we can see if there is a way to prevent such issues in the future. 

Apparently, we should be doing something like this:
```
try:
    <use session>
    session.commit()
except:
   session.rollback()
   raise
finally:
   session.close()  # optional, depends on use case
```

And here is some more good information on how to create a wrapper around the session that can be used in a scalable way: https://docs.sqlalchemy.org/en/13/orm/session_basics.html#session-faq-whentocreate

I'm not too worried about this for this particular project, but it is something that we should be aware of.

**Comment by aedwardg** [comment]
@NickSchimek is this still an issue?

**Comment by NickSchimek** [comment]
Hey @yunnie We talked about how this is probably not an issue.

We're going to be switching to a new architecture, which will make this type of issue moot.

I'm going to go ahead and close this.
