### ISSUE TITLE
Allow Search on the Tickets page

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#425]
**Purpose**
What will this feature provide?
Allows search by *any* column using the search bar above the tickets grid

**Proposed Solution**
If you have an idea on how to implement this feature, please share!
See the Properties page for ways to do this with the existing Search bar

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Search bar should read "Search by Ticket, Sender, Assignee, Status, or Date"
- [ ] When the search bar is used, it should filter the rows based on the *visible properties* that *contain* the search criteria
- [ ] This should be an onChange event while typing so it filters the results in real-time. When the user erases their search criteria is should reset to the original unfiltered data set.

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

**Additional context**
Please reach out if you have questions!

**Comment by Jam52** [comment]
Hi, could I be assigned to give this a try?

**Comment by NickSchimek** [comment]
@Jam52 Sure, I assigned you the ticket.
