### ISSUE TITLE
Tenants View causes infinite API call loop 

### ISSUE THREAD

**Issue by SeHarlan** [codeforpdx/dwellingly-app#430]
**Describe the bug**
Whenever someone brings up the TenantView component/view an infinite series of API calls is triggered causing the website (and browser) to break.

Seems to be coming from line 110 in the getTenant func.

**To Reproduce**
1. Go to Tenants page
2. Click on any individual Tenant
3. See error in Network tab of dev tools of in backend log

**Expected behavior**
The website doesn't crash but the whole browser becomes unresponsive until you close the window.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Chris-Boe** [comment]
Issue was not on development branch
