### ISSUE TITLE
Dashboard Links

### ISSUE THREAD

**Issue by DaveTrost** [codeforpdx/dwellingly-app#435]
**Purpose**
Link the cards on the dashboard to the detail pages that have been built. 

**Proposed Solution**
There are three cards on the dashboard. Two of these already have small ">" links. These links should go to the appropriate pages (currently, they link back to the dashboard) and the third needs a link added - this appears to be an oversight on the original Figma. Additionally, I think users will expect the entire title line of the card to be clickable as part of the link. And, I wouldn't argue if you made an argument for the entire card to be a clickable link.

**Please make sure you've attempted to meet the following coding standards**
- [ ] Code builds successfully
- [ ] Code has been tested and does not produce errors
- [ ] Code is readable and formatted
- [ ] There isn't any unnecessary commented-out code
- [ ] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

**Mockup Screenshot or Page Number**
Page 4 of the [FIGMA designs](https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view)

**Comment by NickSchimek** [comment]
@pogorobot is working on this.
