### ISSUE TITLE
Manage Tenants Page Updates to Match Figma

### ISSUE THREAD

**Issue by DaveTrost** [codeforpdx/dwellingly-app#437]
**Purpose**
Spit and polish the Tenants Page
- The (Manage) Tenants page has a search capability but it gives an error - `Cannot read property 'length' of undefined`
- The table has a missing column for "JOIN Staff". This should be included in the table for each tenant following the design on page 8 of the [FIGMA designs](https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view)
- The page has a missing toggle function for "show unhoused tenants". See page 8 of the [FIGMA designs](https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view)
- The table has a missing feature: tenants with missing information need to have a bell (alert) icon to the left of their name
- When sorting, the initial sort order should be A-Z. 

**Proposed Solution**
- [ ] Debug and fix the search error. 
- [ ] When the search bar is used, it should filter the rows based on all visible properties that contain the search criteria.
- [ ] This should be an onChange event while typing so the results are filtered in real-time. When the user erases their search criteria (or clicks the "X" on the right hand side of the search bar), it should reset to the original unfiltered data set.
- [ ] Add JOIN Staff information to the table for each tenant
- [ ] The search function includes JOIN Staff text when searching for matching text
- [ ] Add the toggle for "show unhoused tenants" and enable the toggle by default.
- [ ] When the property column is sorted in ascending mode (and unhoused tenants are showing), tenants without an assigned property are displayed first
- [ ] Add functionality to show an alert icon in the row of tenant information. This icon displays for tenants with missing data fields.
- [ ] Add the following property to the React BootstrapTable component: `defaultSortDirection="asc"`

**Please make sure you've attempted to meet the following coding standards**
- [ ] Code builds successfully
- [ ] Code has been tested and does not produce errors
- [ ] Code is readable and formatted
- [ ] There isn't any unnecessary commented-out code
- [ ] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

**Mockup Screenshot or Page Number**
See page 8 of the [FIGMA designs](https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view)

**Comment by Protopaco** [comment]
I self-assigned this issue, and made a little bit of progress:

- repaired search bar functionality
- added JOIN staff to the table

still to do:

- add Property information to the table
     - It appears that .get /tenant/ doesn't currently return propertyId / lease info.  I want to check in about this at tomorow.
- JOIN Staff links should point to staff pages
     - It appears that staff doesn't currently have their own pages, I'm happy to tackle that next if that is helpful
- Toggle 'show unhoused tenants' switch needed
     - Will need propertyId attribute to add this
- Alert bell for tenants with missing information fields

**Comment by DaveTrost** [comment]
@NickSchimek @aedwardg 
This ticket is on hold because the payload for `GET /tenants` does not include lease information (at least not with the current development branch). Is there any active work to change this?

**Comment by aedwardg** [comment]
@DaveTrost it does include the lease information for each tenant.  A recently merged frontend PR makes use of it here in the TenantView:
https://github.com/codeforpdx/dwellingly-app/blob/b58c2f1dc7c33545f6544f293e8943d95906125c/src/views/Tenant/TenantView.jsx#L142-L158

**Comment by aedwardg** [comment]
Looks like @Protopaco fixed it himself a few days after commenting on this issue 😂 
https://github.com/codeforpdx/dwellinglybackend/pull/195

**Comment by Protopaco** [comment]
Thank you for the reminder about this ticket.  I did go and update the tenant / lease return issue.  I'll try and get this moving in the next couple of days!

**Comment by DaveTrost** [comment]
Thank you for the updates @aedwardg and @Protopaco. I think I need a sign on my comments that says "student ~~driver~~ reviewer" 🤦

**Comment by NickSchimek** [comment]
> Thank you for the updates @aedwardg and @Protopaco. I think I need a sign on my comments that says "student ~~driver~~ reviewer" 🤦 

If you need that. Then we all need it.

To be Human is to make mistakes.
Life is a learning adventure. Eh simulation.
