### ISSUE TITLE
Update db for Tenant Model

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#438]
**Purpose**
The following fields should be required:
`firstName`
`lastName`
`phone`

**Proposed Solution**
add `nullable=False` to the three fields

**Comment by aedwardg** [comment]
I can do this.  What's the best way to test it to make sure those fields can't be empty after the change?
Re-seed the db and then use the front-end UI?  Or is it better to test through the API?

**Comment by NickSchimek** [comment]
Sorry for the late response @aedwardg - I usually get back sooner, but I've been really busy this past week. Creating an automated test would be the best way to test this. You probably can't manually test this through the frontend UI. They may have front-end validations already in place that would prevent that, of course if you modify the front-end code to manually test it then that would be a possibility. However, I would still require an automated test to be put in place.

On a side note: I generally don't test database level configurations. However, the way things are being setup it is easy to test this.

We are currently in the process of moving to marshmallow for all input validation. Validations will take place in the marshmallow schema files. For the tenant you can find that here: 

https://github.com/codeforpdx/dwellinglybackend/blob/development/schemas/tenant.py

These are AutoSchemas (to some extent). What that means is that after you add the `nullable=False` to the fields on the Tenant Model then the Tenant Schema will automatically check that those fields are present when we create a resource.

We should create some validation tests that will verify this. You'll need to create a test file for the schema since one does not exist as of this writing. The file name could/should be: `tests/schemas/test_tenant_schema.py`. There is an example in the `test_lease_schema.py` file for the tests that you will need to setup. https://github.com/codeforpdx/dwellinglybackend/blob/development/tests/schemas/test_lease_schema.py#L20

Let me know if you have any questions or run into any trouble. Thanks for taking this on, and thanks for asking about testing.

**Comment by aedwardg** [comment]
@NickSchimek, 

It looks like the Marshmallow schema for the Tenant model has a DateTime field called `addedOn`, which doesn't exist in the actual database.  Should I remove this, or does it serve a purpose?

![image](https://user-images.githubusercontent.com/44326005/101268134-b924c380-3714-11eb-95c3-baf347b902ae.png)

**Comment by NickSchimek** [comment]
Yes, please remove that. We used to have an added_on field. If there are
any more remnants of that lying around then they can also be removed. Good
catch. Thanks for asking

**Comment by aedwardg** [comment]
Cool, will do.
