### ISSUE TITLE
New page: View/Edit Property

### ISSUE THREAD

**Issue by DaveTrost** [codeforpdx/dwellingly-app#441]
**Purpose**
Build a new page for the View/Edit Property view. The existing Manage -> Property Manager page can be a good point of reference for the new functionality (and please extend the use of any reusable components)

**Proposed Solution**
- [ ] Implement the view following pages 49 and 50 of the [FIGMA designs](https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view)
- [ ] Request detailed property information from the following API endpoint: `GET /properties/<int:property_id>`
- [ ] Implement a View mode and and an Edit mode. The "edit" (aka: pen) icon acts to toggle between modes. 
- [ ] In Edit mode, the "Save" button is not enabled until a change has been made. 
- [ ] When Save is clicked, send a request with the updated information to the following API endpoint: `PUT /properties/<int:property_id>`.
- [ ] After the Save request is complete, refresh the view with the information returned from the PUT request and switch to View mode
- [ ] The backend has the functionality to archive a property to cover situations where rental properties go in and out of use. But the Figma does not give any direction for the UI to archive/unarchive a property. Please bring your creativity to bear on this point and share a screenshot of what you come up with!

**Please make sure you've attempted to meet the following coding standards**
- [ ] Code builds successfully
- [ ] Code has been tested and does not produce errors
- [ ] Code is readable and formatted
- [ ] There isn't any unnecessary commented-out code
- [ ] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

**Mockup Screenshot or Page Number**
Reference pages 49 and 50 of the [FIGMA designs](https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view)

**Comment by Chris-Boe** [comment]
Yahya is going to leave this one for someone else to pickup for now

**Comment by Protopaco** [comment]
I can give this a shot.  I'll plan on using the /manage/tenants/:id  page
