### ISSUE TITLE
Show/Hide Archived Property Managers

### ISSUE THREAD

**Issue by DaveTrost** [codeforpdx/dwellingly-app#442]
**Purpose**
Spit and Polish the Manage Property Managers page

The page has a search capability that works to reduce the active items in the table, but there is no way to go back to the complete list. This bug is in-process to be fixed by #334. To check the continued existence of the problem:
1. Search for a property manager and press enter
2. Note that the list of property managers shrinks
3. Click the "X" in the search bar or delete all search text and press enter again
4. The list of property managers **should** return to its original length

The page has a missing toggle function for showing or hiding "archived" property managers. See page 37 of the [FIGMA designs](https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view)

Add a way to get to an edit property manager page. There are intersecting issues here:
1. Page 37 of the [FIGMA designs](https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view) shows a page for editing a Property Manager, yet there is no way shown to get to that view from the Manage Property Managers page
2. The Invite button has unknown functionality. Page 36 has a vague clue about bulk edit for Property Managers, however it has something to do with property managers awaiting approval (ie. not connected to the Invite button!). Discussion is needed.
3. Page 16 of the [FIGMA designs](https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view) seems to show a blue  highlight (indicating a hyperlink to the edit view?) on the property manager under the mouse cursor

**Proposed Solution**
- [x] When the search bar is used, it should filter the rows based on all visible properties that contain the search criteria.
- [x] The search bar needs an onChange event while typing so the results are filtered in real-time. When the user erases their search criteria (or clicks the "X" on the right hand side of the search bar), it should reset to the original unfiltered data set.
- [ ] Add the toggle for show/hide archived property managers and set it to "hide" archived managers by default.
- [ ] Make a pitch to the project maintainers (Hugh and co.) about how to address the intersecting issues listed above. 
- [ ] Update this issue with the plan of record and go get it!

**Please make sure you've attempted to meet the following coding standards**
- [ ] Code builds successfully
- [ ] Code has been tested and does not produce errors
- [ ] Code is readable and formatted
- [ ] There isn't any unnecessary commented-out code
- [ ] There aren't any unnecessary commits or files changed (shouldn't touch the /stashed folder unless the issue requests it)

**Mockup Screenshot or Page Number**
Pages 16 and 37 of the [FIGMA designs](https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view)

**Comment by Chris-Boe** [comment]
Everything I see in the description of this issue has been resolved or is not applicable (I don't see a Toggle button on the manage Property Managers page for showing/hiding archived property managers)
