### ISSUE TITLE
created_at and updated_at fields should be dump only

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#446]
**Describe the bug**
The created_at and updated_at validation tests located here: https://github.com/codeforpdx/dwellinglybackend/blob/development/tests/schemas/test_lease_schema.py#L58

currently returns a validation error that has the current value `{'created_at': ['Not a valid datetime.']} - it suggests that if a valid datetime format is supplied then the schema would allow setting the created_at field on the model. 
The schema should NOT allow this since the created_at and updated_at fields should not be manually set. 

Update the tests so that we have more confidence that the test is correct, and update the application code as/if necessary.

**Comment by htharker42** [comment]
To clarify: ignore all created_at and updated_at requests - make them dump only

**Comment by NickSchimek** [comment]
@htharker42 Are you working on this?

**Comment by NickSchimek** [comment]
Replaced by #642
