### ISSUE TITLE
Create unhoused tenant fixture

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#460]
**Purpose**
Create an unhoused tenant fixture to use in the lease Schema test

**Comment by aedwardg** [comment]
@NickSchimek can we close this issue?

To me it looks like as of [backend PR 182](https://github.com/codeforpdx/dwellinglybackend/pull/182) (which removes the tenant-property connection) the tenant fixture creates an unhoused tenant.

Just wanted to double-check with you first before closing it.

**Comment by NickSchimek** [comment]
Yes, that makes sense. I think we can close it out

**Comment by aedwardg** [comment]
Closed by [backend PR 182](https://github.com/codeforpdx/dwellinglybackend/pull/182).
