### ISSUE TITLE
Rename tenant, sender, assignedUser arguments to tickets 

### ISSUE THREAD

**Issue by cecillesalazar** [codeforpdx/dwellingly-app#465]
**Purpose**

Coordinate merging https://github.com/codeforpdx/dwellinglybackend/pull/164 along with this issue.

Refactoring and test improvements in the ticket model for the backend resulted in more explicit naming for the following args:

1. tenant -> tenantID
2. sender -> senderID
3. assignedUser -> assignedUserID

These will have to be changed in the FE as well so the backend will receive properly.

**Proposed Solution**

Just grep all the refs for the 3 args and change em~

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] All refs for 3 args are changed
- [ ] Existing api calls to tickets with the new args are successful

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

**Additional context**

**Comment by Chris-Boe** [comment]
I have looked through the frontend and I don't believe any work will need to be done to support the backend's name changes! Looks like we are sending back the sender/assignee/tenant names along with the ticket info and only referencing those in the frontend. The ID's are also already named appropriately in the returned JSON from the API, and I don't see ticket info being referenced anywhere else in the frontend.

Let me know if I missed anything! @cecillesalazar , I'll let you close this if there aren't any concerns on your end

**Comment by NickSchimek** [comment]
Thanks @Chris-Boe ! Based on your comment I went ahead and merged @cecillesalazar PR. If there is anything that does need to be changed then I'm sure we'll find out soon. I will close this, and we can re-open it if need be.
