### ISSUE TITLE
tests and implementation of  cascade="all, delete-orphan"  managers field of property model

### ISSUE THREAD

**Issue by whiletrace** [codeforpdx/dwellingly-app#468]
**Purpose**
   cascade="all, delete-orphan" option should be added to managers field on model.property  behavior of flag should be verified by unit tests
 1. relationship between manager and property is severed
 2. No objects are deleted do to unintended behavior of flag
 **Proposed Solution**
 create fixture and Unit tests to verify behavior of flag
**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] unit test should all pass 
   [ ] cascade="all, delete-orphan" flag should be added to managers field on model.property if behavior of option is as 
      intended 

   
**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

**Additional context**

**Comment by yunnie** [comment]
This would imply that if the manager is deleted, then the property would be deleted as well. Is this the correct behaviour?
