### ISSUE TITLE
/manage/manager/{id} fails to render due to calendarState prop in toggleEditTable

### ISSUE THREAD

**Issue by dbridenbeck** [codeforpdx/dwellingly-app#482]
**Describe the bug**
Attempting to view an individual property manager page produces a TypeError and does not render the view.

**To Reproduce**
1. Go to the dwellingly homepage
2. Click on 'property managers' in the left navbar
3. Click on a property manager name to view the individual property manager page

**Expected behavior**
Individual property manager pages should load successfully.

**Desktop (please complete the following information):**
 - OS: mac catalina
 - Browser: chrome
 - Version: 87.0.4280.88

**Additional context**
I think this can be solved by editing toggleEditTable to have some conditional logic that only attempts to destructure the calendarState variables if calendarState is truthy

**Comment by ccbass** [comment]
I think I found a fix, let me get it cleaned up.
