### ISSUE TITLE
Rename Property "unit" field in backend

### ISSUE THREAD

**Issue by aedwardg** [codeforpdx/dwellingly-app#487]
### **Description**
Currently, there is a "unit" field in the property model and resources.  Looking at the [Figma](https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view), in particular on pages 12, 15, 49 and 50, properties shouldn't have a field called "Unit" (which sounds like the unit number in leases/tenants), but should instead have "Units" to represent the total number of units (or maybe available units??) in that property.

Because the frontend POSTs this form field data as "units", but the backend is looking for "unit", the Add New Property function does not fill in the number of units for that record in the database. (Note: editing a property -- PUT request -- has not been implemented on the front end yet -- see #441)

This was discussed in part in [dwellinglybackend PR 175](https://github.com/codeforpdx/dwellinglybackend/pull/175)

### **To Reproduce**
1. Start both backend and frontend
2. Sign in as an admin
3. Go to Manage Properties
4. Click ADD NEW
5. Fill in the Property Information, including the "Units" field and click SAVE
6. Open database or use CURL GET request on the properties API endpoint to see no number of units recorded for the new property

### **Expected behavior**
Hitting ADD NEW should properly update the db.

### **Proposed Solution**
Change all references to a property's `unit` to either `units` or `num_units` to avoid confusion.  `num_units` would be clearer. 

**Backend files that will need to be changed**:
- [ ] `data/seedData.py`
- [ ] `models/property.py`
- [ ] `resources/property.py`
- [ ] `tests/factory_fixtures/property.py`
- [ ] `tests/integration/properties.py`
- [ ] `tests/schemas/test_property_schema.py`
- [ ] `tests/serializers/property/test_property_serializer.py`
- [ ] The [API Usage](https://github.com/codeforpdx/dwellinglybackend/blob/development/doc/using_the_api.md) page

**Frontend integration:**

Currently, the frontend is referencing this field as `units` in the [addProperty view](https://github.com/codeforpdx/dwellingly-app/blob/development/src/views/addProperty/addProperty.js).
To solve this, we could:

- match the name between the frontend and backend (set both to either `units` or `num_units`); or
- keep `units` on frontend, `num_units` on backend and make sure the backend parses the request data for `units`
  - Note: `resources/property.py` is still using the deprecated `RequestParser`

**Comment by NickSchimek** [comment]
Let's not have dual labels on this. This is more of a backend issue so I'm dropping the frontend label. We can create a specific issue to update the frontend if need be, and reference this issue in there.

**Comment by NickSchimek** [comment]
I just realized there is the Frontend integration proposed solution section. Let's move that to its own issue. Since we can't update both frontend and backend repo in the same PR then it is more ideal to have separate issues; otherwise we could do it in the same issue.
