### ISSUE TITLE
Properties/:id won't remove all property managers

### ISSUE THREAD

**Issue by Protopaco** [codeforpdx/dwellingly-app#489]
**Describe the bug**
When the frontend sends a .put request to /properties/:id with data.propertyManagerIDs as an empty array, indicating that all property managers have been removed, the backend does not remove the remaining property managers.  The frontend receives a response that includes the final property manager.

On line 135 of resources/property.py, the following code deals with this instance:

```
        if data.propertyManagerIDs:
            rentalProperty.managers = PropertyModel.set_property_managers(data.propertyManagerIDs)

```
I believe that if we change the line to:

```
        if data.propertyManagerIDs != []:
            rentalProperty.managers = PropertyModel.set_property_managers(data.propertyManagerIDs)

```
it will recognize the empty array and work the way it is intended.  

If this is an expected response, i.e. the user shouldn't be able to remove all of a property's property manager, than we can add notices on the front end side.

**To Reproduce**
1. Go to '/manage/properties/2'
2. Click on 'edit button'
3. Click on 'remove property manager icon (top right of property manager box)'

**Expected behavior**
User should be able to remove all property managers.

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.7
 - Browser: Chrome
 - Version: 87
 

**Additional context**
Please let me know if this is the correct way to be doing this.  I want to work within the established workflows.  

Thank you!
Paul

**Comment by NickSchimek** [comment]
High five @Protopaco ! Finally, someone has noticed this! I've been aware of issues with the way we are assigning/updating property managers. 

The way you suggested.
```
        if data.propertyManagerIDs != []:
            rentalProperty.managers = PropertyModel.set_property_managers(data.propertyManagerIDs)
```
might work, however it would not solve the overall issue which is the way we are assigning property managers in the model is not ideal, and there could be more than one bug associated with the current implementation. Ultimately, the `set_property_managers` method does not need to exist. Of course, that depends on how we expect the frontend to communicate with the backend. I think we should probably discuss this a bit more. I have a preferred way of implementing this, but that might not align with how others want to do it. Let's chat about this more. For now I'm going to place an on-hold and needs discussion label on this issue.

**Comment by NickSchimek** [comment]
oops, I'm terrible at reading @Protopaco 

> When the frontend sends a .put request to /properties/:id with data.propertyManagerIDs as an empty array

So a Property must have at least one Property Manager assigned to it. 

I just submitted a PR codeforpdx/dwellinglybackend/pull/181 to address validation issues with assigning/de-assigning property managers. With this new PR if you try to send an empty array as a request to the backend, then it should not make any changes and respond with a 400 response status along with a message containing the validation error.
