### ISSUE TITLE
Properties/:id and Tenants/:id don't return lease information

### ISSUE THREAD

**Issue by Protopaco** [codeforpdx/dwellingly-app#490]
**Describe the bug**

.Get calls to tenants/:id don't return lease information.  On the Property View/Edit page, the FIGMA asks for tenant unit numbers to be displayed.   The unit information is associated with the leases, but I haven't found an endpoint directly related to the lease information.  It would be helpful if the lease information, or at least the unit number could be included in responses to tenants/:id. 

**To Reproduce**
1. Hit: http://localhost:3000/manage/properties/2 with a .get request
2. check out the response

**Expected behavior**

Response tenant JSON should include lease or unit information.

**Desktop (please complete the following information):**
• OS: Catalina 10.15.7
• Browser: Chrome
• Version: 87

**Additional context**
I haven't been here for the larger design and functionality discussions.  I am just working from the current  architecture and trying to reproduce what is in the FIGMA.  If there are reasons to not include this information, or another way for the frontend to access it, please let me know and I'll be happy to make adjustments.

Thank you!
Paul

**Comment by NickSchimek** [comment]
@Protopaco Thanks for the issue! There is still a lot of work to be done in the backend. All the endpoint information and what they should be sending back can be found here -> https://github.com/codeforpdx/dwellinglybackend/blob/development/doc/using_the_api.md

If you take a look at the tenant endpoint https://github.com/codeforpdx/dwellinglybackend/blob/development/doc/using_the_api.md#endpoint-tenants
Then it is shown to not send lease data back.

There is a lease endpoint where you can get lease information, but we will be removing that. 

I'd say we can certainly create an issue to supply lease information with the tenant, I believe this was already on the roadmap to do, but I don't think I've gotten around to creating an issue for it yet.

**Comment by NickSchimek** [comment]
I don't think there is a reason to not include lease information with a tenant. A lot of us weren't here for the initial discussions and the figma designs were completed by another organization. So working with the designs have proven difficult. Feel free to create a backend issue to get this behavior implemented.

**Comment by ccbass** [comment]
@NickSchimek I also agree that lease information should be included with a tenant.  Having lease information linked is critical, especially as missing lease dates/deadlines can lead to more housing issues down the line.

**Comment by NickSchimek** [comment]
It all depends what the UI requires. The tenant already has a relationship with lease in the backend. If the UI needs lease info with a tenant request then that is easy to do.

**Comment by aedwardg** [comment]
Closed by [backend PR 195](https://github.com/codeforpdx/dwellinglybackend/pull/195)
