### ISSUE TITLE
User Schema requires a string for a Role instead of an int

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#491]
**Describe the bug**
The marshmallow auto schema validations need to be overridden for the Role. Using the schema this way we would need to pass the string values; however it has been decided to use ints. Update the schema role validations to validate on int values.

**Comment by yunnie** [comment]
If we want to pass and receive integer values for the Role, do we also want to store the Role as an integer value in the database?

**Comment by NickSchimek** [comment]
No, it is stored as an enum. The model is good. The way the schema is deserializing the role data needs to change. Does that make sense?
