### ISSUE TITLE
JWT is stored in localStorage

### ISSUE THREAD

**Issue by ccbass** [codeforpdx/dwellingly-app#495]
Noticed when trying to learn about the front end that the JWT is stored locally in `window.localStorage`.   The backend is obviously setup for development (`config.py`) and allows for infinite refresh token duration.

Is there a proposed long-term/production goal for the application as a whole to be moved to a different auth system (#73 and #74 are mentioned, but on hold.) since storing locally is ill-advised?

Is there a plan to move to server-side sessions or a more secure platform like Auth0?

For those of us new to JWT and auth, see: https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#storage-apis

**Comment by ghost** [comment]
In my experience the standard of authentication involves using http only cookies for managing the hey/refresh tokens on the front end. Note that safari (and eventually chrome) doesn't support third party cookies, which means the front and back ends will need to be served from the same domain.

**Comment by NickSchimek** [comment]
Thanks for all this input. @htharker42 @Chris-Boe @DaveTrost Y'all probably familiar with the JWT setup that was implemented. I haven't really taken a look at it. Do you see things here that will need to be changed/fixed/improved?
