### ISSUE TITLE
Add validation to check that admin (current user) cannot delete themselves

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#496]
**Purpose**
Per [figma](https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view) designs on page 18 the admin is not allowed to delete themselves.

**Proposed Solution**
Use marshmallow for validation

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Tests are created to check that an admin (the current_user) cannot delete themselves

**Comment by NickSchimek** [comment]
Might have to create a current_user method, if one does not already exist, to grab the session's current_user.

**Comment by ccbass** [comment]
While not exactly the issue, but is there a process in place to delete or archive JOIN staff that are no longer part of the program?

**Comment by NickSchimek** [comment]
> While not exactly the issue, but is there a process in place to delete or archive JOIN staff that are no longer part of the program?

Yes, an admin can archive any type of user via the following endpoint `/user/archive/:uid` see [api usage](https://github.com/codeforpdx/dwellinglybackend/blob/development/doc/using_the_api.md#endpoint-user-model)
