### ISSUE TITLE
Missing validation check on ticket schema

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#499]
**Describe the bug**
Currently anyone of User can be assigned a ticket, however only Join Staff are allowed to be assigned tickets.

Add the validation check in the Ticket Schema to check that the incoming `assignedUserID` is a valid Staff ID.

**Comment by yunnie** [comment]
Can an Admin be assigned a ticket? Or is it strictly staff?

**Comment by NickSchimek** [comment]
From what I'm told it is strictly staff.

**Comment by yunnie** [comment]
This is done. I must have screwed up the reference in the pull request.
