### ISSUE TITLE
Add ability to query all users who have no role

### ISSUE THREAD

**Issue by aedwardg** [codeforpdx/dwellingly-app#502]
**Purpose**
Step 2 of 4 in transitioning away from the `PENDING` user role.

In preparation for `PENDING` role to be removed, we need a way to access all users who have not been assigned a role.

Currently, the frontend grabs these "pending" users through the `UsersRole` endpoint, by providing a `userrole` with the Enum value for the `PENDING` role.

**Proposed Solution**
A new endpoint should probably be created to handle this, since there will no longer be a role to pass to the `UsersRole` endpoint.

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Implement a way to access a list of all users who have no role.
- [ ] Create appropriate integration tests for this functionality

**Comment by gussmith23** [comment]
I started poking at this, and then realized that #501 needs to be done first. Still, I ran in to some questions. Such as: currently, the "role" column has a default set for it (it defaults to the `PENDING` role). To test a query that gets all users without roles, I need to be able to add users without roles -- as long as the default is there, I don't know if that's possible. Is there a way to get users w/o roles in the database, without removing the default? Should we just not test? Or should we remove the column default?

**Comment by aedwardg** [comment]
Hey @gussmith23, sorry it took me a while to get back to you.

There are a couple ways you can go about this.  

- The role field is nullable, so you can always create a new user in the DB, passing in `None` for the `role` field. 
- If you're using pytest rather than manual testing, in `conftest.py` there is a pytest fixture called `new_user`.  Change the value for `role` to `None` for that fixture and you can use it in your tests.
- Finally, I think it would be fine to change the default role value in the `UserModel` to `None` if you wanted to go that route.
  - Currently, when the db is seeded, the new "pending" users are being explicitly given the role `RoleEnum.PENDING` in the `seed_data.py` file. This means, changing the default in the model shouldn't affect anything that uses that data.  The only thing that would break is the `test_create_unauthorized_user` unit test, where you'd have to change the assertion to assert the role as `None`

Any of those options should work fine, so go with whichever one you're most comfortable. Also, it looks like there's now a PR in for #501, so no worries about proceeding with this one.

**Comment by gussmith23** [comment]
@ovsyankimo @russellneville let me know if you need help on this one!
