### ISSUE TITLE
Pending users should no longer be queried by role

### ISSUE THREAD

**Issue by aedwardg** [codeforpdx/dwellingly-app#503]
**Purpose**
Step 3 of 4 in transitioning away from the PENDING user role.

After #501 and #502 have been implemented, there will no longer be any reason for the frontend to get pending users by role.
Pending users should instead be retrieved through the endpoint in #502.

Currently, the frontend grabs these "pending" users through the `UsersRole` endpoint. This should be updated to reflected the changes mentioned in those two issues.

**Proposed Solution**
If the backend has a new endpoint to retrieve users with no roles, the frontend should use that instead of `UsersRole`.

~~If we instead decide it is best to continue using (an altered version of) the `UsersRole` endpoint, change any necessary `userrole` values to comply with the changes on the backend.~~

**We will be using a new endpoint for this. See comment below** 👇 

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [x] Issues 501 and 502 must be closed already
- [x] Any and all functions that interact with pending users should look for users with no role instead of the `PENDING` role
- [x] Remove `PENDING` role from the RoleEnum

**Comment by aedwardg** [comment]
In case Issue 502 isn't merged by the time this is started, the new API endpoint to grab the "pending" users will be 
`/api/users/pending`

**Comment by beekman** [comment]
Thanks! This is super helpful, I was just trying to determine this endpoint.
