### ISSUE TITLE
Remove PENDING role from backend

### ISSUE THREAD

**Issue by aedwardg** [codeforpdx/dwellingly-app#504]
**Purpose**
Step 4 of 4 in transitioning away from the PENDING user role.

Once issues #501, #502 and #503 are completed, there will no longer be any need for a `PENDING` role.

**Proposed Solution**
- Remove all references to the `PENDING` role and remove the role from RoleEnum.

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Issues 501-503 must be closed
- [ ] There should be no lingering remnants of the `PENDING` role in any code, including tests and seed data.

**Comment by ghost** [comment]
A more durable solution to this problem would be to store the user roles in the database instead of an enum and have the front end query the backend to build a list of roles. This prevents the two being out of sync (which this issue seems to address).

**Comment by aedwardg** [comment]
@lexi-drake, thanks for the input!

This issue actually isn't about syncing the frontend and backend roles, but rather removing the dedicated `PENDING` role that we've been assigning to users who are waiting to be assigned a "real" role.  Instead of having a dedicated role for them, we want them to have _no role_ until a role is assigned to them by admin/staff members.

Because `RoleEnum.PENDING` permeates far and wide throughout both the front and back ends of the app, I separated this into 4 distinct issues to a) not overwhelm contributors; b) provide streamlined checklist for what to do and how to do it; and c) break as little of the app as possible at each step.  

For this issue in particular, my hope is that the only thing left will be to clean up any remaining pieces of `RoleEnum.PENDING` in the backend that haven't been taken care of by parts 1 & 2, and refactor anything added by those PRs if it wasn't done before they were merged.

---

As for your suggestion, I do like the idea of keeping everything in sync by only having one enum in the back end rather than one in the front and one in the back.  This would mean if a role gets added, it would only need to be added in one place, which is ideal.

We already have the enum in the users.role column in the database, so the backend could provide the roles directly from there if we wanted to:

![image](https://user-images.githubusercontent.com/44326005/105636758-9ebabc80-5e1e-11eb-913d-05a605451a9a.png)

Setting up an endpoint for the frontend to retrieve this would be very simple, but it's something I'd want to bring up with the group at our next meeting.  I don't work on the frontend much and those who do might have a better idea if we'd want/need this.

**Comment by aedwardg** [comment]
> 
> 
> A more durable solution to this problem would be to store the user roles in the database instead of an enum and have the front end query the backend to build a list of roles.

Although there's a good chance we won't change things up at this point (especially since we currently plan on only having 3 roles), I'd be interested in hearing how you'd suggest implementing your proposed solution @lexi-drake.  If we find ourselves adding more and more roles after launch, it could well be something for us to look into.

**Comment by ghost** [comment]
@aedwardg Typically, the way I've handled this is to have a table specifically for roles, with columns for the role-name and whether or not it should be offered as a sign-up option (like you may want to allow users to identify themselves as property managers or tenants, but not as admins, which are presumably more restricted). When the front end asks for which roles to display (if that's a use-case), then the roles table can be queried with a `WHERE` clause for that flag. I'm not a database wizard, but this call is presumably significantly cheaper than a `distinct()` call to a table that's (and I don't know the intended size of the user-base) potentially orders of magnitude larger.

In my experience, the front-end really doesn't need to know what the available roles are, just whether or not a user belongs to any one of them (to determine, like, what options should be rendered in a menu or dashboard), so for the most part the front-end can be naive to what roles exist until specific functionality for a role is introduced.

**Comment by aedwardg** [comment]
@lexi-drake, you bring up some great points and I tend to agree with you.  
While I don't think such a change would be high on the priority list given the state of the app and its limited need for roles, we'll definitely keep that in mind as we move forward.

Thanks again, and if you're at all interested in contributing we'd be glad to have you on board.  Just join our slack channel if you haven't already and introduce yourself (you can find the link [here](https://github.com/codeforpdx/dwellingly-app/blob/development/contributing.md) under "First Steps")
