### ISSUE TITLE
add .gitignore  to project

### ISSUE THREAD

**Issue by deric4** [codeforpdx/dwellingly-app#51]
Please add a project gitignore to limit noise in Pull Requests :D 

standard node and python ignore files. Example set:

See GitHub help page on gitignore files: https://help.github.com/en/github/using-git/ignoring-files
```gitignore
.DS_STORE
node_modules
scripts/flow/*/.flowconfig
*~
*.pyc
```

**Comment by skrabacher** [comment]
I updated the gitignore file: 
https://github.com/codeforpdx/dwellingly-app/commit/361b87ae8bdba8e16640255ea679d4409bd9662c
Hopefully that eliminates some noise :) - Sarah

**Comment by skrabacher** [comment]
I updated the gitignore file:
https://github.com/codeforpdx/dwellingly-app/commit/361b87ae8bdba8e16640255ea679d4409bd9662c
Hopefully that eliminates some noise :) - Sarah
