### ISSUE TITLE
Resource `tenants/<int:tenant_id>` should only include current/active lease info

### ISSUE THREAD

**Issue by aedwardg** [codeforpdx/dwellingly-app#512]
## Purpose
When retrieving a tenant's JSON information, the lease provided to the front end should only be the currently active lease. Right now, there is a many-to-one relationship (tenants are able to have multiple leases). It makes sense to keep it this way if we want to retain previous leases, but the endpoint should only return the current lease unless specifically asked for all the leases.

This was discussed to some extent [here](https://github.com/codeforpdx/dwellingly-app/pull/509).

It looks like most of the groundwork for this was completed in [backend PR 195](https://github.com/codeforpdx/dwellinglybackend/pull/195).  **However**, [this line](https://github.com/codeforpdx/dwellinglybackend/blob/3246d1d7b40620e147d17768107242f91a9914d5/models/tenant.py#L28) only returns the first lease in the list.  If a newer lease gets added for this tenant, there is no guarantee it will be at index 0, so we should instead be filtering the tenant's leases to only the current one.

**NOTE: this is assuming one tenant cannot be on two active leases at once. If we later decide this should be possible (e.g., if a family needs two units and the head of household is on both leases) we'll need to re-think this.**

## Proposed Solution
Filter the tenant's leases and return the lease where datetime.now() falls between the lease start and end dates*
*_Note the assumption above_

## Acceptance Criteria

- [ ] Include appropriate tests (when in doubt, consult the [Project Components doc](https://github.com/codeforpdx/dwellinglybackend/blob/development/CONTRIBUTING.md#project-components) for where to test each component)
- [ ] If a tenant has multiple leases, _only_ the currently active one should be returned

## Mockup Screenshot & Page Number
This will provide the correct property and unit information for the frontend's `TenantView`, as seen on [Figma pg. 10](https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view):

![image](https://user-images.githubusercontent.com/44326005/105643706-3da6df00-5e46-11eb-9ac7-adb84e4f70fc.png)

**Comment by aedwardg** [comment]
@NickSchimek I wonder if the best solution for this would be to add an `Active` field to the lease that autoupdates daily based on the current date?  I think we might be able to do something of the sort with [SQLAlchemy's event hooks](https://docs.sqlalchemy.org/en/13/orm/events.html#).  

If so, we could just check whether leases are marked as `Active` for both the Tenants endpoint and the Property endpoint (see #520)

**Comment by gussmith23** [comment]
Started taking a look at this one, but some of the design decisions might be over my head. As I understand it, it seems like the decision could be between:
- **Having an `Active` field as @aedwardg suggests,** and running a daily script to make sure things get updated, and
- **Forcing the active check to be done elsewhere.** Then, the question is, where do we calculate the "active" value? In the backend logic that reads from the database, or in the frontend logic?

Having not dealt with databases much in a real-world setting, I guess my sense is that the first option is easier, but requires the daily check to be run.

I'm mostly just talking to myself here, haha. Trying to make sure I understand!

**Comment by NickSchimek** [comment]
> I wonder if the best solution for this would be to add an Active field to the lease that autoupdates daily based on the current date?

Yeah. that is one way, but I don't think it should be a database field. We can have a logical field do that for us in the model. It's less complex and more accurate.

in `models/lease.py` -> create a public method or attribute method that returns a boolean for us.
```
def active
  current_date_time > self.startDateTime && current_date_time < self.EndDateTime
```

And to get the active lease out of a list of leases. probably something like this where necessary.

```
tenant.leases.filter(active)
```
Probably not correct python code, but something along those lines should work.

**Comment by NickSchimek** [comment]
I think hooks would be a good solution when there are certain events that are triggered where we need to input data to the db. 

If a db field was absolutely necessary for the scenario of the active field then I would run a cron job that updated the db nightly. However, a logical field probably works best in this situation, and we can be sure that when we need the data that it will be accurate.

**Comment by aedwardg** [comment]
Sounds good! @gussmith23 is this something you'll want to tackle?
