### ISSUE TITLE
Seed data should be validated by schemas

### ISSUE THREAD

**Issue by aedwardg** [codeforpdx/dwellingly-app#515]
## Describe the bug
Much of the current seed data is not being validated by the schemas when it's being seeded.  This means there is no guarantee the data in our development and test databases is data that could actually be added to the db through normal use of the app.  

Entries that are not validated with the schemas can contain anything that is allowed by the database constraints (which are far more permissive than our schema constraints and do not enforce formatting of any kind).

## Proposed solution 
For an example of a properly validated entry, check out the [property entries](https://github.com/codeforpdx/dwellinglybackend/blob/3eff729e212ac2039d1c3e1ac84978db8bedc7d2/data/seedData.py#L143-L154).  Everything in the `seedData` file should follow this format.

Specifically, the following entry types need to be updated to use schemas:

- Users
- Tickets
- Notes
- Emergency Contacts
- Contact Numbers
- Leases

## To Reproduce
**Steps to reproduce the behavior:**
1. Go to `seedData.py`
2. Change the `ticket_id` in one of the notes to 42 and save the file (there is no ticket with an id of 42)
3. Reseed the database with `pipenv run flask db recreate`
4. DB is successfully reseeded even though the linked ticket does not exist

## Expected behavior
Nothing should be seeded into the database that would otherwise raise a `ValidationError`.

## Screenshots
![image](https://user-images.githubusercontent.com/44326005/105660268-85962800-5e7f-11eb-9143-f5e99d58dfda.png)

**Comment by NickSchimek** [comment]
hey @cecillesalazar how is it going? Do you still want to work on this?

**Comment by cecillesalazar** [comment]
Successfully reproduced the error 😅 Looking into it this week~

**Comment by NickSchimek** [comment]
@cecillesalazar Is there anything we can do to help get this wrapped up? This is becoming a high priority to finish up.

**Comment by cecillesalazar** [comment]
Hey - sorry I’ve been pretty sparse. Been dealing with some record high
attrition at work and everyone’s doing the work of 3 people. It would
probably be best if this work was reassigned - though I am happy to push up
my branch as I’ve been able to make some progress on it.

Cecille

**Comment by NickSchimek** [comment]
Ok. No worries. Thanks for letting us know. I will unassign you so that someone else can pick it up. Feel free to push up your branch and let us know where to find it. Thanks!
