### ISSUE TITLE
change default branch from develop -> development

### ISSUE THREAD

**Issue by deric4** [codeforpdx/dwellingly-app#52]
Please set the default branch to https://github.com/codeforpdx/dwellingly-app/tree/development

On GitHub, navigate to the main page of the repository:

- Under your repository name, click **Settings**.

- In the left menu, click **Branches**.

- In the default branch sidebar, choose the new default branch.

**Comment by mhunterak** [comment]
I think only @htharker42 has permission to do this. bump please!

**Comment by deric4** [comment]
Looks like this has been implemented by @htharker42
