### ISSUE TITLE
Property Schema requires unique name for PUT request

### ISSUE THREAD

**Issue by Protopaco** [codeforpdx/dwellingly-app#521]
**Describe the bug**
Property Schema returns "A property with this name already exists" error in response to PUT requests where property name hasn't changed.  Error encountered on "edit properties" page (ticket #441).  User can update any and all property fields, so long as name has also changed.  If user attempts to change other attributes (address, num of units, etc) when not changing the name, the error occurs.

This functionality makes sense for creating a page, but seems like a bug when updating certain fields.

The backend code that I believe to be involved is at /schemas/property.py (lines 27:30)

```
    @validates("name")
    def validates_uniqueness_of_name(self, value):
        if PropertyModel.find_by_name(value):
            raise ValidationError("A property with this name already exists")
```

Is it possible to have this test only run when creating new property?

**Expected behavior**
User should be able to update property info without changing the property name.

**Screenshots**
![Screen Shot 2021-02-01 at 6 12 26 PM](https://user-images.githubusercontent.com/66223664/106542977-b26ac080-64b9-11eb-91a6-6e565fd642f2.png)

**Desktop (please complete the following information):**
 - OS: Catalina 10.15
 - Browser: Chrome
 - Version 88

**Additional context**

**Comment by aedwardg** [comment]
Good catch @Protopaco! It looks like the `test_update_property_by_id` test doesn't even test the PUT functionality of that endpoint.

Any PR looking to close this issue should include an updated test in `tests/integration/test_properties.py` that properly tests the PUT request.
