### ISSUE TITLE
FE unit tests have multiple failures

### ISSUE THREAD

**Issue by keppel2** [codeforpdx/dwellingly-app#523]
**Describe the bug**
Test Suites: 5 failed, 5 passed, 10 total
Tests:       8 failed, 2 skipped, 18 passed, 28 total
Snapshots:   0 total
Time:        8.416s, estimated 15s
Ran all test suites.

**To Reproduce**
`npm test`

**Comment by yunnie** [comment]
Is the issue to fix the errors so that the test suite passes?

**Comment by keppel2** [comment]
Yes. Fix or delete the tests.
