### ISSUE TITLE
Create new tickets in Frontend

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#526]
**Purpose**
What will this feature provide?
The ability to create new tickets in Dwellingly

**Proposed Solution**
If you have an idea on how to implement this feature, please share!
* Create an "Add New" button to the Tickets page, similar to the Properties page
* New page with a Formik form to fill out with the following fields and a header of "Add a New Ticket" similar to the Add a New Tenant" page
* Move Tickets link in the Left nav to be below the "Manage" section
* Add a Tickets link underneath the "Add New" section in the left nav to go to the Add a New Ticket page

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] A new ticket should be created (Must be merged/tested with the backend work)

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

**Additional context**

**Comment by strangetimes** [comment]
This screenshot shows 3 of the 4 items for this issue: 

- Create an "Add New" button to the Tickets page, similar to the Properties page
- Move Tickets link in the Left nav to be below the "Manage" section
- Add a Tickets link underneath the "Add New" section in the left nav to go to the Add a New Ticket page

Let me know if you have any questions or would like anything changed/added/removed! 

![screenshot issue 526a](https://user-images.githubusercontent.com/77747585/108608801-4b388180-737e-11eb-9b7c-43ec61844873.png)

**Comment by strangetimes** [comment]
For the remaining item in this issue (_New page with a Formik form to fill out with the following fields and a header of "Add a New Ticket" similar to the Add a New Tenant" page_), I started a page + just need a little input on what else you would like to see on this form! I can play around with the layout once I have all the info accounted for. Thanks! 

![screenshot issue 526b](https://user-images.githubusercontent.com/77747585/108608891-e4679800-737e-11eb-83da-fb5f7ad0436a.png)

**Comment by Chris-Boe** [comment]
After a group discussion on 4/28, we're going to replace the Issues choice list with a text input so the user can put whatever they want as the Issue for the ticket. We are also going to replace the Property search and Unit details for a Tenant search, which then the user can select one or more tenants from and it will automatically have the tenant's lease and property info populated.
