### ISSUE TITLE
Archived properties should not be able to be archived again

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#529]
**Describe the bug**
Currently, on the Properties page, Archived and non-archived properties look the same and can be "archived again", even though nothing changes in the database.

**To Reproduce**
1. Go to Properties
2. Click on a property checkbox and click Archive Properties
3. Toggle the Show Archived to SHOW
4. Repeat the process to the same property

**Expected behavior**
* Disable the checkbox on already-archived properties so it can't be clicked
* Gray out the other column texts on already-archived properties but NOT the name field so it still looks clickable

**Screenshots**

**Additional context**

**Comment by GOusignu** [comment]
Hey! I would like to work on this

**Comment by michelangelo17** [comment]
Can't seem to assign myself, but I think I've got this done.
