### ISSUE TITLE
remove legacy branches

### ISSUE THREAD

**Issue by deric4** [codeforpdx/dwellingly-app#53]
As of now, the only branches we've discussed using are *master* and *development*. The other ones need to be removed.

**Comment by sternmd** [comment]
Heads up, just created branch `fe-test-branch` off development (see task #55 ). This branch is for setting up frontend testing. Not to be removed, thx!

**Comment by mhunterak** [comment]
Blockers: Depends on https://github.com/codeforpdx/dwellingly-app/issues/52 before can proceed

**Comment by deric4** [comment]
unblocking since #52 has been completed

**Comment by Chris-Boe** [comment]
Verified old branches are gone
