### ISSUE TITLE
Add ability to add notes to a ticket

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#530]
**Purpose**
What will this feature provide?
Ability to add notes to a ticket in the Ticket modal screen and see them show up in the list in real time.

**Proposed Solution**
If you have an idea on how to implement this feature, please share!
* Add a Plus sign button to the right of the Notes header
* Clicking the plus sign shows an input text box above the topmost existing note (and if they're scrolled down in the notes section, this will scroll them back up). Clicking the plus button also hides it from view until they add the note
* An "Add" button is displayed under the bottom right of the input box that saves the note to the backend. When this is clicked, the input box and Add button disappears and the Plus button shows up again.

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] New Plus button displays input text box
- [ ] Clicking Save under the input box will save the new note to the backend

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.
![image](https://user-images.githubusercontent.com/8600792/107602493-9adcb780-6bde-11eb-8213-c26e398c6945.png)

**Additional context**

**Comment by Protopaco** [comment]
I would be happy to make an attempt at this.
My plan is: 
1. Create an AddNote component that returns a text input and "add" button
2. add handleAddNote that will send PUT request to server with updated Note information
3. add "plus" button that changes a "showAddNote" state boolean
4. add turnery to display AddNote when plus button is pushed

**Comment by Chris-Boe** [comment]
We'll probably need to make some updates to the backend too so lmk if you have any questions!

**Comment by Protopaco** [comment]
> We'll probably need to make some updates to the backend too so lmk if you have any questions!

It looked like I could send a PUT request on the ticket with an updated array of notes with the current backend functionality.  I haven't tested it yet however.  Does that work or should I try a different approach?

**Comment by Chris-Boe** [comment]
> > We'll probably need to make some updates to the backend too so lmk if you have any questions!
> 
> It looked like I could send a PUT request on the ticket with an updated array of notes with the current backend functionality. I haven't tested it yet however. Does that work or should I try a different approach?

Ah yep that looks like it'll work! It looks like we might need to update the "senderID" code though, since the person making the note might not always be the initial sender of the ticket. So with the request to add a note, we'll need to make sure there is an "authorID" or something that is only getting applied to the note model, not to the ticket model's SenderID

**Comment by Protopaco** [comment]
> Ah yep that looks like it'll work! It looks like we might need to update the "senderID" code though, since the person making the note might not always be the initial sender of the ticket. So with the request to add a note, we'll need to make sure there is an "authorID" or something that is only getting applied to the note model, not to the ticket model's SenderID

I'm seeing the same thing.  I can send an "authorID" with the PUT request, then I can create a new ticket to update the endpoint in the back.

**Comment by Protopaco** [comment]
I swear this is my last new branch on the issue. ;)

In the current development there isn't a mechanism to view the ticket details.  I am assuming that will be updated at some point.  I'll bring it up at the meeting tonight.
