### ISSUE TITLE
Modify Lease information from View/Edit Tenant

### ISSUE THREAD

**Issue by DaveTrost** [codeforpdx/dwellingly-app#534]
**Purpose**
View/edit tenant needs to be functional for an unhoused tenant (aka: tenant has no lease)
- How to replicate the problem:
  - Create a new tenant, and leave the lease section blank
  - Manage Tenants --> click on the newly created tenant

View/edit tenant needs to allow edit mode for lease information
- Lease dates and Lease unit should be easy to change from the edit tenant page.

**Proposed Solution**
If you have an idea on how to implement this feature, please share!

Tenant view/edit page needs to more cleanly align with the way the Add Tenant page presents information. Property information can be changed via SearchPanel and property information displayed in a chip. Lease information can display Number, Occupants and Lease dates. 

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Tenants without property information assigned can be viewed and lease details can be added for them.
- [ ] Changes to lease information are updated in the backend using `PUT /api/lease/<int:id>`

**Mockup Screenshot or Page Number**
Please follow the organizational structure of the "add tenant" page. Perhaps some of that code is useful in this work.

**Additional context**

User story provided by @pogorobot :
I have three tenants in The Magnolia, Unit 12. I just added a new tenant to Unit 13, but when I was creating the record, I accidentally clicked on the existing Unit 12. Now I need to edit my newest tenant to add him to Unit 13, which may or may not have an existing record in the database. It should be easy to change this tenant's unit number, but hard to change the address of The Magnolia.

**Comment by DaveTrost** [comment]
Some of the comments from https://github.com/codeforpdx/dwellingly-app/issues/477 are applicable to this issue

**Comment by DaveTrost** [comment]
This issue is blocking https://github.com/codeforpdx/dwellingly-app/pull/533

**Comment by Chris-Boe** [comment]
Getting handled by issue #714
