### ISSUE TITLE
Border spacing for property manager view/edit page

### ISSUE THREAD

**Issue by DaveTrost** [codeforpdx/dwellingly-app#535]
**Describe the bug**
the property manager view/edit page has styling inconsistency as compared to the tenant view/edit page and the property view/edit page. It seems some spacing around the form is missing. 

**To Reproduce**
1. Go to manage property managers
2. Click on an individual property manager
3. Compare to the view for tenant view/edit

**Expected behavior**
The frame of white space around the form should match visually and in the implementation with the view/edit tenant page. The CSS should be consistent across all three pages - property manager view/edit, tenant view/edit page and property view/edit.

**Comment by Protopaco** [comment]
I created a new branch, put made the changes, pushed it up, and mysteriously four other commits from Issue #437 got added to the branch.  I'm at a total loss.  I'm too tired to figure it out tonight.  I'll tackle it first thing in the morning.  Sorry!
