### ISSUE TITLE
Implement testing framework for python (api)

### ISSUE THREAD

**Issue by deric4** [codeforpdx/dwellingly-app#54]
Consensus so far has been to use pytest. Also, there is interest in the coverage tool that works alongside pytest

- [x] Install and setup pytest and coverage tools
- [x] write basic unit and integration tests
- [x] use the coverage tool to get to 100% code coverage from the tests for user routes

**Comment by deric4** [comment]
I've done some digging around on what the best way to implement testing for The API application, there's some design/refactoring that may or may not be needed due to the repository directory/file layout and use of flask app factory pattern expected by the pytest maintained flask plugin

https://github.com/pytest-dev/pytest-flask

**Comment by DaveTrost** [comment]
Hi @deric4, can I work on this issue?

I'm hoping to make some progress with the API testing methodologies. I will start by reviewing the information you provided here and I will confirm your findings before proceeding. Is there any more information you can provide on this task?

**Comment by DaveTrost** [comment]
Update: I was able to muck with the create_app function and it follows a bit more closely to the application factory model that pytest-flask is expecting. After getting this set up, it seems that basic integration tests and unit tests on the models are straightforward to set up. So, I believe the API testing is feasible with pytest and pytest-flask.
I'm currently stuck on a underlying detail. I need to include the bearer token in the request for integration testing on routes with JWT requirements. I haven't seen an implementation yet that I'm happy with ... will have to keep searching.

**Comment by DaveTrost** [comment]
When this issue is closed, #80 should also be marked as complete
