### ISSUE TITLE
UserModel serialization should include properties & tenants for PMs

### ISSUE THREAD

**Issue by aedwardg** [codeforpdx/dwellingly-app#543]
## Purpose

Right now, PM information includes a list of assigned properties and tenants when retrieved through the User endpoint, but not anywhere else. So that we don't have to re-implement that logic every place we want to serialize a PM, it should be moved from the User endpoint (resource) to the UserModel.

## Proposed Solution

Move the serialization of a PM's assigned properties and tenants to the UserModel `json` method.
The corresponding test should be moved out of the integration tests and into the unit tests.

## Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] The UserModel `json` method should include assigned properties and tenants if the user is a Property Manager.
- [ ] The serialization logic should no longer be in the endpoint
- [ ] The corresponding test should be under the unit tests for the UserModel
- [ ] If any additional methods are created, there should be unit tests for those as well

## Additional context

The serialization logic is here:

https://github.com/codeforpdx/dwellinglybackend/blob/985561ecbe21d0d38b0abbf852c1776bee482863/resources/user.py#L43-L48

And the test that should become a unit test is here:
https://github.com/codeforpdx/dwellinglybackend/blob/985561ecbe21d0d38b0abbf852c1776bee482863/tests/integration/test_users.py#L126-L130

**Comment by aedwardg** [comment]
@yunnie it looks like you can access the user's associated properties through `user.properties` (or `self.properties` inside the UserModel class itself), but we can't serialize them with the same logic as the endpoint inside the UserModel `json()` method.  If we do 
```python
property_list = self.properties
properties = [p.json() for p in property_list]
```
inside the UserModel `json()` method, we get a RecursionError since the PropertyModel `json()` method has this line:
```python
return {
...
"propertyManager": [user.json() for user in self.managers]
...
```

More circles.  

It makes me wonder if we even need to include this information in the UserModel `json()` method, or if it's best to just have separate UserModel methods to get a PM's properties and tenants when we need them.  Alternatively, I wonder if this would all be solved by using Marshmallow serialization instead of these `json()` methods....

**Comment by yunnie** [comment]
@aedwardg I'll look into a few different options. One possible approach is to include a default parameter in the `json()` methods, something like `json(includeProperties=False)` But I'll definitely check out using Marshamallow for the serialization.

**Comment by yunnie** [comment]
@NickSchimek @aedwardg Is the plan to eventually refactor the `json()` methods in the model classes to wrap Marshmallow serialization?

**Comment by NickSchimek** [comment]
I'm not sure the issue your discussing above, but a quick answer is, yes- I would like to, but I put it on hold because it was being slowly adopted, not everyone was comfortable with marshmallow. So I believe that there is only one object that is serialized that way. Feel free to move this to marshmallow, I figured we would eventually have to for some more sophisticated serializations that would be needed for the user object.
