### ISSUE TITLE
Separate authorization tests from endpoint logic tests

### ISSUE THREAD

**Issue by aedwardg** [codeforpdx/dwellingly-app#545]
### Purpose
Step 1 of 3 in moving away from using `auth_headers` in the integration tests

Currently, most of our integration tests use the `auth_headers` fixture to provide the needed headers for API interaction.
The problem is, `auth_headers` hits the login endpoint with a specific role's credentials every time it is used.  This means that each test that uses `auth_headers` is simultaneously testing 
- authentication (_can this type of user log in?_);
- authorization (_once logged in, can this user perform this action?_); **and**
- controller/model logic (_does this action work?_)

This means that if we change anything about how we authenticate or authorize users, most of the integration tests break.  It also means these tests are significantly slower than they need to be.

### Proposed Solution

For this first step, separate out all tests that focus on **authorization** into their own directory (e.g., `tests/integration/auth`) and away from the tests that are testing logic.

### Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] All integration tests that test whether a certain type of user can perform an action should be moved to the new directory.
- [ ] All integration tests that test _logic_ (i.e., checks if the action functions as intended) should remain in the current files.
- [ ] All tests should still pass.

**Comment by gussmith23** [comment]
Taking a look at this PR. How does this strategy sound:
1. create `tests/integration/test_authentication.py`
2. search through tests in `tests/integration/test_*.py` for tests (or parts of tests) that seem to be testing authentication
3. move those tests (or parts of tests) to the file created in 1.

I my main question is, from a cursory look, it seems like some tests mix tests of authentication w/ tests of other functionality. (I guess that's the point of the issue!) E.g. in test_emergency_contacts.py:
https://github.com/codeforpdx/dwellinglybackend/blob/87cd36203cbd4033caf64aa86b8be39ccfb589e5/tests/integration/test_emergency_contacts.py#L68-L89
Here we test that POSTing with an invalid datatype fails, then we do two tests of unauthorized POSTs, and then we finally do a successful test. Here, we'd just want to separate out the two middle tests, correct?

**Comment by gussmith23** [comment]
Talking to Nick, he proposes that we convert to class-based tests at the same time we separate out the auth tests from the functionality tests.

**Comment by aedwardg** [comment]
That sounds like a great idea.  I think class-based tests are best here because of the encapsulation they provide.  Also, it makes it _way_ easier to use the `empty_test_db` in all the tests (one decorator per class -- rather than a separate parameter in each function)

**Comment by aedwardg** [comment]
> https://github.com/codeforpdx/dwellinglybackend/blob/87cd36203cbd4033caf64aa86b8be39ccfb589e5/tests/integration/test_emergency_contacts.py#L68-L89
> Here we test that POSTing with an invalid datatype fails, then we do two tests of unauthorized POSTs, and then we finally do a successful test. Here, we'd just want to separate out the two middle tests, correct?

Yes, that's correct. Those two middle tests (lines 78-83) are the ones that should be moved over to a separate file in the auth tests directory.

**Comment by gussmith23** [comment]
Are all of the tests moved? I have a few PRs for moving tests, but I'm not sure if I actually got to all of them!

**Comment by NickSchimek** [comment]
ah, that's alright. I will be auditing all the tests soon.
