### ISSUE TITLE
Integration tests should use valid_header if not testing authorization

### ISSUE THREAD

**Issue by aedwardg** [codeforpdx/dwellingly-app#546]
### Purpose
**Step 2 of 3** in moving away from using `auth_headers` in the integration tests
This should take place **after** #545

Tests that are testing endpoint logic shouldn't be testing authentication or authorization at the same time.  Instead, they should be isolated to only testing model/controller logic.  For more information, see #545 

### Proposed Solution
Replace the `auth_headers` fixture with `valid_header` in all integration tests that are testing logic.  
NOTE: This may require altering the tests to use `empty_test_db` as well if the test doesn't already.

### Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] All integration tests that test _logic_ (i.e., checks if the action functions as intended) should use the `valid_header` fixture instead of `auth_headers`.
- [ ] All tests should still pass.

**Comment by NickSchimek** [comment]
This could be broken out into smaller chunks. One issue for each test file

**Comment by aedwardg** [comment]
Sure, I can split this up into issues for each of the following files in `tests/integration`:
- test_emergency_contacts.py (#594)
- test_properties.py (#595)
- test_tenants.py (#596)
- test_tickets.py (#597)
- test_users.py (#598)

**Comment by aedwardg** [comment]
Closing in favor of issues 594-598, which cover refactoring a single test file each.
