### ISSUE TITLE
Remove the Reports Card and Link in Menu

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#558]
**Purpose**
Remove and un-used feature

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Report Card is no longer on Admin Screen
- [ ] Report Link is no longer in SideNav panel
- [ ] Code Builds Correctly
**Mockup Screenshot or Page Number**

![image](https://user-images.githubusercontent.com/32914953/112412958-9aa30200-8cdc-11eb-8b41-3ce9bfbbea51.png)

**Comment by jabinx92** [comment]
can i work on this issue?

**Comment by Chris-Boe** [comment]
> can i work on this issue?

@jabinx92 I've assigned it to you! You should have gotten an email to join the CodeforPDX github group, once you're in you can assign yourself to issues and create branches and PR's for your work! Let us know if you have any questions, the dwellingly-app Readme is a great place to start. Thanks for your help!

**Comment by jabinx92** [comment]
@Chris-Boe hey I was able to get my environment set up, but i am unable to sign into dwelling.ly. is there a guest account i can use to log in? or another way around this?
