### ISSUE TITLE
Implement CSS Framework With React (frontend)

### ISSUE THREAD

**Issue by sternmd** [codeforpdx/dwellingly-app#56]
CSS frameworks provide a basic structure for designing consistent solutions to tackle common recurring issues across front end web development. We should think about which framework we want to implement, especially if there is no design for this app.

I did some research and found some CSS frameworks for React:
 
- [Bulma](Bulma) - my personal fav 😎
- [Material UI](https://material-ui.com/)
- [React Strap](https://reactstrap.github.io/) 
- [Semantic UI](https://semantic-ui.com/)
- [Foundation](https://foundation.zurb.com/sites.html)

**Comment by dbmzzo** [comment]
👍 for Bulma, which seems appropriately lightweight for a smaller project like this. I've also been curious about giving https://tailwindcss.com a shot, but know that utility classes are controversial.

**Comment by chrisandrewca** [comment]
I'm pretty sure Semantic UI is dead after checking out the github issues. Fomantic UI is a fork but seems to be getting stale as well.

+1 for Bulma too. It seems to strike the right balance.

**Comment by sternmd** [comment]
Sounds good everyone, lets go with Bulma. Should we implement pure [bulma/node-sass](https://medium.com/@thexap/how-to-setup-bulma-css-framework-with-react-under-5-minutes-a3d8c2c33a87) or something like [react-bulma-components](https://www.npmjs.com/package/react-bulma-components)? The former may be easier to customize/override styles, the latter is more modular/component-driven. Thoughts?

**Comment by chrisandrewca** [comment]
Node-sass let’s us import only what we need and customize it to fit the brand. I vote for that one.

**Comment by sternmd** [comment]
Ok, I am adding this issue to Sprint 1 2020 & will implement bulma/node-sass via branch: `fe-test-branch`

**Comment by sternmd** [comment]
Merged -> closing
