### ISSUE TITLE
Add spinner icon to tables while data is being fetched

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#561]
**Purpose**
What will this feature provide?
Tables on the /manage/properties, /manage/tenants, and /manage/managers pages appear empty while data is being fetched, making the user believe there isn't any data on the page at all at first glance. We should add some "Loading..." text or a spinner icon to show that data is being retrieved.

**Proposed Solution**
If you have an idea on how to implement this feature, please share!
* Add a spinner icon like one of these (https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons) to pages with longer load times, like each of the Manage pages. Could be applied to the table itself or the entire page (but make sure the left nav and header buttons are all still interactable while the spinner is present).

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [x] Spinner icon appears when data is first being fetched on the Manage pages

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

**Additional context**

**Comment by devon-wolf** [comment]
Any preference on the icon that's used/the source? I have a test version of this working with plain "Loading..." text on the manage tenants page, should be pretty straightforward to put it on all those routes that fetch a whole bunch of data.
