### ISSUE TITLE
Bump flask-sqlalchemy to version 2.5.1

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#565]
**Describe the bug**
MacOS BigSur conflicts with flask-sqlalchemy version 2.4.1. 
Bumping to 2.5.1 resolves the issue. 

**Desktop (please complete the following information):**
 - OS: MacOS BigSur 11.2.3

**Additional context**

**Comment by aedwardg** [comment]
Closed by Nick in [Backend pr 232](https://github.com/codeforpdx/dwellinglybackend/pull/232)
