### ISSUE TITLE
Add lots of test data

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#569]
**Purpose**
What will this feature provide?
We should start adding more test data to the populate db script in the backend so that we can start testing the limits of the app's performance, UI layouts, grid paging/sorting/filtering, etc.

**Proposed Solution**
If you have an idea on how to implement this feature, please share!
Add about 30-100+ additional items of each model (users with differing roles, tickets, properties, tenants both housed and unhoused, emergency contacts)

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [x] Db script adds 30+ **tickets** with various settings
- [x] Db script adds 30+ **users** with various settings
- [x] Db script adds 30+ **tenants** with various settings
- [x] Db script adds 30+ **properties** with various settings
- [x] Db script adds 30+ **emergency contacts** with various settings

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

**Additional context**

**Comment by NickSchimek** [comment]
This should be fairly simple to do with the faker library. I think the best place to do this is in the seedData file, but our tests need to be disconnected from that file, and that file needs to finish its refactoring so that we can ensure the data added is accurate.

**Comment by NickSchimek** [comment]
blocked by #515
