### ISSUE TITLE
Fix failing test

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#571]
The following test is failing. It was traced back to this PR codeforpdx/dwellinglybackend/pull/217
I added a skip decorator on it for now.

Please fix me. 

```python
    def test_delete_can_unarchive_tenant(self, valid_header, create_tenant):
        tenant = create_tenant()
        tenant.archived = True

        response = self.client.delete(f"{endpoint}/{tenant.id}", headers=valid_header)

        assert response == 200
>       assert not tenant.archived
E       AssertionError: assert not True
E        +  where True = <'TenantModel' {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x104d52460>, 'lastName': 'Dillon'...56), 'firstName': 'Tristan', 'phone': '513.933.2871', 'updated_at': datetime.datetime(2021, 4, 4, 11, 29, 41, 374372)}>.archived

tests/integration/test_tenants.py:138: AssertionError
```

**Comment by aedwardg** [comment]
@NickSchimek [backend PR 226](https://github.com/codeforpdx/dwellinglybackend/pull/226) closes this.  It's just a single call to `save_to_db()`.  This test didn't fail at the time the PR was made, but after I upgraded Flask-SQLAlchemy to 2.5.1, it started failing without that line so I just included it in that PR.
