### ISSUE TITLE
Unable to create an account on localhost:3000 dwelling.ly app

### ISSUE THREAD

**Issue by jabinx92** [codeforpdx/dwellingly-app#572]
**Describe the bug**
After running npm start, I am unable to login to dwelling.ly app. Is there like a guest login in of some sort? Or is the feature to create an account not yet configured?

**To Reproduce**
1. Go to 'login page'
2. Click on 'Create account'
3. Fill in the information
4. Click "Sign up"
5. Error logged - "[HPM] Error occurred while trying to proxy request /api/register from localhost:3000 to http://localhost:5000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)"

**Comment by aedwardg** [comment]
@jabinx92,

This is actually not a bug.  The system is built so that when a user signs up for an account, they must later be assigned a role and given access by Admin or Join Staff.

For development purposes, go ahead and sign in with one of the 3 default users found here: https://github.com/codeforpdx/dwellinglybackend/blob/development/doc/using_the_api.md#the-database-is-seeded-with-3-default-users

NOTE: Both the back end and the front end will need to be running for the authentication to work.

**Comment by jabinx92** [comment]
noted, thanks for your help!

**Comment by jabinx92** [comment]
"NOTE: Both the back end and the front end will need to be running for the authentication to work."

@aedwardg Do I just follow these steps to setup the backend? https://github.com/codeforpdx/dwellinglybackend/blob/development/CONTRIBUTING.md#installation

**Comment by aedwardg** [comment]
> @aedwardg Do I just follow these steps to setup the backend? https://github.com/codeforpdx/dwellinglybackend/blob/development/CONTRIBUTING.md#installation

@jabinx92 Yep, those are the ones!

**Comment by jabinx92** [comment]
@aedwardg Am I able to suggest an edit on the readme doc for https://github.com/codeforpdx/dwellinglybackend/blob/development/CONTRIBUTING.md#installation?

As a windows user yesterday I kept getting an error where "python/pip/pip3 is not recognized as an internal or external command | python command error"

I got it to resolve with this youtube video with changing my environment variables. https://www.youtube.com/watch?v=dj5oOPaeIqI

**Comment by aedwardg** [comment]
@jabinx92 

Feel free to make a PR to the `dwellinglybackend` repo and we'll review it.

Also, if you have any other questions, please reach out in the [Code for PDX Slack](https://join.slack.com/t/codeforpdx/shared_invite/zt-4msr5np3-n5qBye3GG~4hA_7XZkczgA) (in the #dwellingly-join channel) as there are many people involved in the project who can help you out if I am unavailable. 

Plus, if you're having trouble with the project, someone else might be having the same problem and we can help everyone out at once 🙂
