### ISSUE TITLE
Cannot view unhoused tenant details

### ISSUE THREAD

**Issue by aedwardg** [codeforpdx/dwellingly-app#578]
**Describe the bug**
When trying to view an unhoused tenant's info in the TenantView, it results in a TypeError.

The issue is that the code to display property info doesn't check for the existence of the property assignment before trying to access it (`property` is `undefined` if the tenant has no lease):
https://github.com/codeforpdx/dwellingly-app/blob/5c11ab10a48ebad91bd792b1f67f5eeca0f88ae6/src/views/Tenant/TenantView.jsx#L192-L199

**To Reproduce**
1. Sign in to the app with an Admin account
2. Click on 'Add New Tenant'
3. Create a new tenant with no property or lease information
4. Go to 'Manage Tenants' and toggle to show Unhoused Tenants
5. Click on your new unhoused tenant.
6. See error.

**Expected behavior**
TenantView should allow user to see a tenant's info even if they have no lease/property.

**Screenshots**

**Additional context**
Other code that prevents this from working is the broken calendar code which tries to access `dateTimeStart` and `dateTimeEnd` through the property instead of the lease (see #580):
https://github.com/codeforpdx/dwellingly-app/blob/5c11ab10a48ebad91bd792b1f67f5eeca0f88ae6/src/views/Tenant/TenantView.jsx#L212-L213

**Comment by yunnie** [comment]
The address, unit number and lease information will be empty for unhoused tenants. Will use "Not Housed" as a default value.

**Comment by yunnie** [comment]
If there is no lease, then to display a "Not Applicable" in the lease section of the table, we need to make the `inputType` conditional, if there is a valid lease, use `calendar`, otherwise use `text`.
