### ISSUE TITLE
Tenants should not be created with incomplete lease/property info

### ISSUE THREAD

**Issue by aedwardg** [codeforpdx/dwellingly-app#579]
**Describe the bug**
Right now you can add a tenant with: 
- incomplete lease info (filled in unit num and/or occupants, but missing dates), and no property info; or 
- property info but no lease info

The issue is that a tenant's property information is accessed through their lease to that property. 

Either of the above scenarios results in a successful tenant creation, but no lease creation (to make a lease though the `tenants` endpoint, a property ID and lease start and end dates must be included in the payload). 

Rather than having the lease creation fail silently, I propose we add a little more validation to the front end.
The current validation requires a property to be selected if the lease start and end dates don't match.  Instead, if _any_ lease/property info is filled out, the user should be notified that lease start/end dates and a property selection are required.

**To Reproduce**
1. Sign in as Admin
2. Go to 'Add New Tenant'
3. Add tenant info and select a property but include no lease info
4. Hit 'Save' and see successful tenant creation
5. Repeat, but this time, fill in the unit num and occupants, but no lease dates or property info

**Expected behavior**
User should be notified of required fields when property/lease info is added

**Additional context**
Right now, due to the problem described in #578, you cannot view tenant details for a tenant created this way because they won't have any lease/property info saved in the db

**Comment by yunnie** [comment]
The add tenant view is found in `src/views/AddTenant/addTeant.jsx`

**Comment by yunnie** [comment]
It looks like there is a form validation function `validateForm`

**Comment by yunnie** [comment]
This is done and can be closed.
