### ISSUE TITLE
Tenant info does not show correct lease dates

### ISSUE THREAD

**Issue by aedwardg** [codeforpdx/dwellingly-app#580]
**Describe the bug**
In the TenantView, the lease start and end dates always show today's current date, regardless of the actual dates saved in the database.

**To Reproduce**
1. Sign in as Admin
2. Click on 'Manage Tenants'
3. Select a tenant that has a lease
4. See the improper dates

This is due to this code, which improperly tries to access `dateTimeStart` and `dateTimeEnd` through the tenant's property and ends up creating a new `Date` instance:
https://github.com/codeforpdx/dwellingly-app/blob/5c11ab10a48ebad91bd792b1f67f5eeca0f88ae6/src/views/Tenant/TenantView.jsx#L212-L213

**Expected behavior**
The lease start and end dates should reflect what is actually saved in the database.

**Screenshots**
![image](https://user-images.githubusercontent.com/44326005/113984277-c2778700-97ff-11eb-8757-9cc4420f4d5b.png)

**Comment by yunnie** [comment]
The lease model has a start and end date, so the `property.dateTimeStart` needs to be changed to `tenant.lease.dateTimeStart`

**Comment by yunnie** [comment]
Turns out that we need to convert `tenant.lease.dateTimeStart` to a date object (`new Date(tenant.lease.dateTimeStart)`)
