### ISSUE TITLE
Separate Tenant resource out into two separate classes

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#592]
**Purpose**
Endpoints that require an id should be in the class Tenant For example the update and get action
Endpoints that do not require an id should be in the class Tenants for example the POST and GET action

See the app.py file for other resources that follow this style. The actual routes and behavior will not change. Only the code organization. So this is more of a refactor which will remove the conditional in the get action when its done.

**Comment by aedwardg** [comment]
Does this mean we're going to hold off on switching over to `MethodView` for now? Because I thought you already took care of this in [backend pr 249](https://github.com/codeforpdx/dwellinglybackend/pull/249)

**Comment by NickSchimek** [comment]
oh yeah, that's right, I did do this already. I guess I will assign this to myself, and extract that out of that PR. Yeah, I'm holding off for now.
