### ISSUE TITLE
Creates delete Note endpoint & tests

### ISSUE THREAD

**Issue by Protopaco** [codeforpdx/dwellingly-app#600]
**Purpose**
Adds new Notes endpoint /tickets/:id/notes for deleting notes.

**Proposed Solution**

Using new backend code style endpoint should confirm that the note's userid is the same at the request's userid.  Using the NotesModel delete the note based on the id passed.  Create a class test on empty database to ensure notes are deleting successfully.

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Create DELETE /tickets/:id/notes endpoint
- [ ] Uses NotesModel to delete ticket from database
- [ ] Tests that note was deleted properly
- [ ] Code builds successfully

**Comment by aedwardg** [comment]
> Using new backend code style endpoint should confirm that the note's userid is the same at the request's userid.

I don't think we should restrict deleting notes to the user who created the note. Any admin should be able to delete the note, perhaps Join staff also.  Plus, what if the person who wrote the note is no longer an active user and is archived? Then nobody could delete the note. 

Restricting this action with the `@pm_level_required` decorator should be enough, unless we want to make it so only Admin, Staff and PMs from _that property_ can delete notes.

**Comment by Protopaco** [comment]
> Restricting this action with the `@pm_level_required` decorator should be enough, unless we want to make it so only Admin, Staff and PMs from _that property_ can delete notes.

That makes sense to me. Currently `@pm_level_required` is used when creating a note, so it would be consistent to use the same criteria for deleting the note.

**Comment by NickSchimek** [comment]
FYI: This should have the endpoint `/tickets/:id/notes`

**Comment by NickSchimek** [comment]
@Protopaco I'm not sure what I was thinking. This issue is for deleting a note so the endpoint needs the note id too. The endpoint we will want should be of this construct: `/tickets/:ticket_id/notes/:id`.

The delete method can go in the `Note` class since it is acting on a single Note resource.
