### ISSUE TITLE
Tickets can be assigned to multiple Join Staff and Tenants

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#606]
**Purpose**
What will this feature provide?
Allows users to assign multiple staff and tenants to a ticket

**Proposed Solution**
If you have an idea on how to implement this feature, please share!
Currently the ticket model has two properties: assignedUserID and tenantID. This should be changed so that Tickets can be assigned to multiple tenants and multiple JOIN staff members. A common way to do this is a linking table in the db, with TenantId and TicketId properties, both as foreign keys.

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Tickets can have multiple tenants assigned to them
- [ ] Tickets can have multiple JOIN Staff members assigned to them

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

**Additional context**

**Comment by NickSchimek** [comment]
@Chris-Boe I'm curious what the reasoning is behind this? I don't quite understand the logic behind assigning a ticket to multiple tenants, and join staff for that matter. Being someone who has worked in the property management business before, we had never had a ticket assigned to more than one tenant before. So I am very curious as to why this is needed. Can you also link the figma designs where it shows we need this feature? Thanks!

**Comment by Chris-Boe** [comment]
> @Chris-Boe I'm curious what the reasoning is behind this? I don't quite understand the logic behind assigning a ticket to multiple tenants, and join staff for that matter. Being someone who has worked in the property management business before, we had never had a ticket assigned to more than one tenant before. So I am very curious as to why this is needed. Can you also link the figma designs where it shows we need this feature? Thanks!

Hey @NickSchimek , we talked one or two weeks ago to go over the mockups and it was a request. The multiple tenants is because we moved away from assigning a property. And the multiple join staff is so multiple people can be assigned to handle it or stay in the loop easily. We can bring it up in this week's meeting if you like.
Mockups are on issue #526

**Comment by NickSchimek** [comment]
Ok. Multiple staff - check
Multiple tenants - I don't understand the need for this still.

> The multiple tenants is because we moved away from assigning a property

There are housed and unhoused tenants. unhoused tenants have yet not been assigned a property. housed tenants have been assigned a property through a lease. 

Can you please explain why a ticket would be assigned to multiple tenants, as the explanation you gave does not make sense.

**Comment by Chris-Boe** [comment]
> Ok. Multiple staff - check
> Multiple tenants - I don't understand the need for this still.
> 
> > The multiple tenants is because we moved away from assigning a property
> 
> There are housed and unhoused tenants. unhoused tenants have yet not been assigned a property. housed tenants have been assigned a property through a lease.
> 
> Can you please explain why a ticket would be assigned to multiple tenants, as the explanation you gave does not make sense.

i.e. There are 5 individuals in a property's unit. Tenant A and Tenant B are constantly yelling and neighbors have reported noise complaints involving these individuals. This involves Tenant A and Tenant B but not Tenants C, D, and E who also live in the unit.

Also, unless we have a good reason to restrict how the user should use the app's features, we shouldn't be placing arbitrary rules like that on what the user can and cannot do. "we had never had a ticket assigned to more than one tenant before" is not such a reason 😉

**Comment by NickSchimek** [comment]
> Also, unless we have a good reason to restrict how the user should use the app's features, we shouldn't be placing arbitrary rules like that on what the user can and cannot do. "we had never had a ticket assigned to more than one tenant before" is not such a reason

I'm not sure what you mean by arbitrary rule when it sounds like arbitrary features are being requested.

I'm not trying to restrict how the user will use the app. I'm trying to build what the user wants. If the user hasn't explicitly requested this then I don't think we should do it because it is more work and costs more and we should focus on getting the MVP out and then iterate based on feedback.

**Comment by NickSchimek** [comment]
Based on our discussion, this isn't something that was requested, and @htharker42 mentioned that tickets will be assigned to the staff through the tenant. Tenant's are already assigned to multiple staff, and those are the same staff that will be responsible for the ticket.

Created issue #614 to remove the unnecessary fields in the ticket model. Thanks.
