### ISSUE TITLE
Update ticket model/schema

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#614]
The ticket model accepts an `assignedUserID`, `senderID`, and a `notelog` along with other fields. These two fields `assignedUserID`, and `notelog` can be removed from the model as they're not needed. The note model contains any notes for the ticket and it is not clear what the notelog is to contain when we have a table dedicated for notes. The `assignedUserID` can be removed, because tenants are already assigned to staff. Hence, the staff responsible for the ticket will be the same staff as the ticket.tenant assignment. In other words, a ticket is assigned to staff through the tenant. The senderID can be better named to `creator_id`, which would be the current_user at the time the ticket was created. 

The ticket model will need to have the following fields:
```
    tenant_id
    issue
    urgency ( Currently a string, but looks like it should be an enum. Keep it as a string though unless confirmed by FE )
    status ( This is an enum and should default to the active/open status )
    creator_id ( current_user )
```

 - tasks:
Update the ticket model to include the following fields above.
Update the schema as necessary
The json method will need to be updated necessary
May need to update the ticket factories and seed file.

**Comment by aedwardg** [comment]
Are tenants always assigned to a staff member? Because if not, then a ticket would not be assigned to anybody if no staff-tenant relationship exists for a given tenant. Is that what we want here?

**Comment by Chris-Boe** [comment]
> Are tenants always assigned to a staff member? Because if not, then a ticket would not be assigned to anybody if no staff-tenant relationship exists for a given tenant. Is that what we want here?

I asked Hugh and he said it was a safe assumption, since the non-profit focuses on the work between the JOIN social workers and the tenants. If a ticket is created without a staff member linked to the tenant, we'll still allow them to add one later
