### ISSUE TITLE
Change to iso format when serializing a note object for created_at/updated_at fields

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#615]
## Description

The frontend would like to order the notes by the created_at date. That is a bit difficult to do with the current format that it is being sent in. Update the format to use the iso date format from the Time class.

**Comment by yunnie** [comment]
I changed the `.json()` method in the `NotesModel` class to use output iso format. Changing both output and input is probably a bigger task, and should be coordinated with the front end.

**Comment by NickSchimek** [comment]
yeah, we need to plan that to do across the app.
