### ISSUE TITLE
Tickets assigned to Tenant should be listed on Tenant page

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#623]
**Purpose**
What will this feature provide?
Tickets assigned to the viewed Tenant should be listed under the "Ongoing" and "Closed" tabs on the ViewTenant page

**Proposed Solution**
If you have an idea on how to implement this feature, please share!
Styling should be clean and match the appearance of the app

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Tickets should be listed with relevant info: Issue, Urgency, Last Updated
- [ ] Tickets should be separated into Ongoing (New & In Progress tickets) and Closed (Closed tickets)
- [ ] Ticket should be clickable to open up the Ticket Modal as seen from the main Tickets page

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.
Current implementation:
![image](https://user-images.githubusercontent.com/8600792/118871158-2760db00-b89c-11eb-9f71-772543e42f4f.png)

Mockup: (page 10)
![image](https://user-images.githubusercontent.com/8600792/118920750-d7116980-b8eb-11eb-8ff9-ea0688768c5f.png)

**Additional context**

**Comment by yunnie** [comment]
@Chris-Boe The backend has three states for tickets: ```New```, ```In Progress```, and ```Closed```. Does it make sense to change the labels on the front end to match? And add a tab for ```New```?

**Comment by Chris-Boe** [comment]
> @Chris-Boe The backend has three states for tickets: ```New```, ```In Progress```, and ```Closed```. Does it make sense to change the labels on the front end to match? And add a tab for ```New```?

"Ongoing" represents both new and in progress tickets. From a UX perspective I think it's fine! If they change their minds it'd be a simple update

**Comment by yunnie** [comment]
I'll be on vacation in the wilderness for a week. So I'm going to un-assign myself. If no one picks up the ticket in my absence, I'll re-assign myself when I get back on August 30th.
