### ISSUE TITLE
Remove `ArchiveProperty` class and associated code

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#638]
## Description
This can be done through the update action. No additional code should be needed.

**Comment by yunnie** [comment]
@NickSchimek When you say that archiving the property can be done through the update action, do you mean the ```put``` method in the ```Property``` resource? I ask so that I can update the tests.

**Comment by NickSchimek** [comment]
Yes, the put action

**Comment by yunnie** [comment]
@NickSchimek Do we want to keep the bulk archive function via the ```ArchiveProperties``` class? In other words, delete ```ArchiveProperty``` class (and associated routes), but keep the ```ArchiveProperties``` class?

**Comment by NickSchimek** [comment]
> Do we want to keep the bulk archive function via the ArchiveProperties class?

Yes. Let's keep that. I believe its used in the frontend? And I don't see another bulk update action available to replace it. So lets keep it.
Unless there is a good reason to remove it.
