### ISSUE TITLE
Remove POST from Email Resource (easy win... if you need it) 

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#644]
**Purpose**
Update Email resource. Remove ancillary endpoint methods

**Proposed Solution**
Remove the Post method from the Email resource as well as in the app.py

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Code compiles correctly 
- [ ] Post endpoint is no longer active in Email Resource 

**Additional context**
This will clean up the email resource and make its implementation more obvious. The resource should be used in support of other resources, not as a primary endpoint.

**Comment by rajdama** [comment]
I can do it

**Comment by NickSchimek** [comment]
@htharker42 Is this being removed because it is not being used by the frontend?

**Comment by NickSchimek** [comment]
I assigned you to the issue @rajdama

**Comment by rajdama** [comment]
> I assigned you to the issue @rajdama 

@NickSchimek 👍

**Comment by rajdama** [comment]
@NickSchimek  Hey I am unable to find app.py can you help me?

**Comment by NickSchimek** [comment]
The routes are defined in config/routes. Do a global search for Email. That should bring up any place that may need to be removed.

**Comment by rajdama** [comment]
@NickSchimek ok

**Comment by aedwardg** [comment]
@rajdama are you still working on this?
