### ISSUE TITLE
Attempting to create an Emergency Contact Fails

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#645]
**Describe the bug**
Attempting to create an Emergency Contact fails with this response
```marshmallow.exceptions.RegistryError
marshmallow.exceptions.RegistryError: Class with name 'ContactNumberSchema' was not found. You may need to import the class.
```
from the endpoint
POST `api/emergencycontacts`

**To Reproduce**
1. Go to Emergency Numbers
2. Click on Create Emergency Number
3. Fill out the form and click submit
4. See the page break and an error in the API logs

**Expected behavior**
An Emergency Number record should be created successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/8600792/120583208-9ed95300-c3e2-11eb-995d-be40c3c02f5c.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
If possible, let's look at fixing the error handling on this page too

**Comment by NickSchimek** [comment]
It's interesting our test doesn't fail. Then again it is python 😏 

If whoever takes this on and you find yourself spinning. Reach out and I'll point you in the right direction.
