### ISSUE TITLE
Refactor get action on the `class Users(Resource)` class

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#646]
## Description

Serializing a user should not be handled in the endpoint. It should call a method that serializes the object. Please remove the duplicate code in UsersRole class and remove all special serialization code in the Users class get method. The details for serializing a user will be handled by the json method which will be updated in a different issue.

I don't think there is any need to find a user by role_and_name. So that behavior (which is defined in the UsersRole class) is ok to be deleted and does not need to be replaced. @Chris-Boe correct me if I'm wrong here.

### Tasks

1. Remove the entire `class UsersRole(Resource)` class.
2. Remove special user serialization in get action in the `class Users(Resource):` class
3. Should be able to simply do something like this: `UserModel.query.filter_by(role=role).json()`
     - Notice the query param is changed from `r` to `role` ^^^

**Comment by Chris-Boe** [comment]
@NickSchimek I wanted to get your thoughts on this, it looks to me that we have two endpoints that query users by role:
https://github.com/codeforpdx/dwellinglybackend/blob/acc9a65fbdb9b9d3b43250170f6f30b250f3db57/resources/user.py#L193

and 

https://github.com/codeforpdx/dwellinglybackend/blob/acc9a65fbdb9b9d3b43250170f6f30b250f3db57/resources/user.py#L234

I'm guessing we can just delete the incomplete second one listed here and update the first with the tickets and tenants, like the properties population is setup already?

**Comment by NickSchimek** [comment]
Thanks Chris. Let's remove this `class UsersRole(Resource):`  entire class and will build our search function in one endpoint.

What is the primary need? Return a list of all join_staff ? Or are there other filters that can be applied?

And yes I have a proposed solution. I know how I would like this implemented

**Comment by NickSchimek** [comment]
So the get endpoint here is also serializing the objects returned. I don't want the endpoint to know how to serialize the object returned, because it doesn't belong in the endpoint and we wouldn't be able to reuse that logic anywhere.
