### ISSUE TITLE
Update tenants query in PropertyModel to not hit the database multiple times

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#647]
## Description

This should use a db query that does not hit the database multiple times to retrieve all the tenants from the leases scope. 

https://github.com/codeforpdx/dwellinglybackend/blob/78864616ced10939dc296f135928885df53997fd/models/property.py#L52

Relevant docs https://docs.sqlalchemy.org/en/14/orm/loading_objects.html

**Comment by gussmith23** [comment]
I was looking into this. Does the lease's `relationship` being lazy make a difference here? I'm still very new to SQLAlchemy, but it seems like we're going to have at least one additional SELECT to get the leases, and then more SELECTs to get each tenant from each lease.

I'm going to assign this to myself, but I might make slow progress -- if this is critical, someone can take it from me!

**Comment by NickSchimek** [comment]
Nope. Not urgent. I think what we may want is specified in the doc I linked above under the Relationship Loading with Loader Options.

**Comment by NickSchimek** [comment]
The doc also explains what different values can be applied to lazy. It looks like we may need to specify something else

**Comment by NickSchimek** [comment]
Yeah, It can be done with two Select statements. I don't this we would need to change the Property model.
Rather change where we are executing the query to get the property.
We probably have quite a few places in the code where we can improve our queries so that we don't hit the database unnecessary, but in the grand scheme of things it is not that very important to work on that right now.

So while this ticket isn't a priority it would lay some ground work to show how this can be done in sql alchemy.

https://github.com/codeforpdx/dwellinglybackend/blob/6976df8ae6a98d87debaa12ac1e204cffe6ce18b/resources/property.py#L59-L62

```python
class Property(Resource):
    @admin_required
    def get(self, id):
        return PropertyModel.find(id).json(include_tenants=True)
```

^^^ I believe this is where we would want to make the changes. 

`PropertyModel.find(id)` <- this wouldn't change. I think we would do something like.

```python
property = PropertyModel.find(id)
property = property.{ magical code here that pulls in all the leases and tenants  :-) }
property.json(include_tenants=True)
```

**Comment by gussmith23** [comment]
Nick posted this helpful message in Slack:

> hey all, I often like to go into the flask shell and issue commands to try things out. Up until now I didn’t know how to see the sql that is generated to make requests. As we build more complex commands that make a database request it is sometimes nice to see the sql that is being generated by framework to confirm that it will do what is expected. There is a get_debug_queries method that Flask-Sqlalchemy provides that does just that. You can read more about it here: https://flask-sqlalchemy.palletsprojects.com/en/2.x/api/#flask_sqlalchemy.get_debug_queries
And you can use it like so:
```
➜  dwellinglybackend git:(development) pipenv run flask shell
Python 3.8.0 (default, Aug  9 2020, 14:48:15)
>>> from flask_sqlalchemy import get_debug_queries
>>> from models.tenant import TenantModel
>>> get_debug_queries()
[]
>>> TenantModel.query.all()
[<'TenantModel' {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState .... # Truncated to save room.]
>>> get_debug_queries()
[<query statement="SELECT tenants.created_at AS tenants_created_at, tenants.updated_at AS tenants_updated_at, tenants.id AS tenants_id, tenants."firstName" AS "tenants_firstName", tenants."lastName" AS "tenants_lastName", tenants.phone AS tenants_phone, tenants.archived AS tenants_archived
FROM tenants" parameters=() duration=0.000>]
>>> exit()
```
>Every query made in the shell is logged. If you do get_debug_queries()[-1] it will return the last sql query made

**Comment by gussmith23** [comment]
I'm going to use this debugging tool to figure out when exactly the multiple queries get launched. Thanks for the pointers above Nick. The lines you pointed to eventually call through to the lines you linked:
https://github.com/codeforpdx/dwellinglybackend/blob/b3c6dcee918c52ab597affb12af4394b066feb22/models/property.py#L55-L60
Do you think the change will also be here? Or are things already too far gone at this point? I.e. what if we replaced the for loop with some other single query?

**Comment by gussmith23** [comment]
Some notes:

```
>>> from models.property import PropertyModel
>>> p = PropertyModel.query.all()[0]
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT properties.created_at AS properties_created_at, properties.updated_at AS properties_updated_at, properties.id AS properties_id, properties.name AS properties_name, properties.address AS properties_address, properties.num_units AS properties_num_units, properties.city AS properties_city, properties.state AS properties_state, properties.zipcode AS properties_zipcode, properties.archived AS properties_archived 
FROM properties
INFO:sqlalchemy.engine.Engine:[generated in 0.00020s] ()
>>> p
<'PropertyModel' {'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x104861be0>, 'created_at': datetime.datetime(2021, 8, 5, 2, 36, 0, 853517), 'id': 1, 'address': '123 NE FLanders St', 'num_units': 5, 'state': 'OR', 'archived': False, 'updated_at': datetime.datetime(2021, 8, 5, 2, 36, 0, 853524), 'name': 'test1', 'city': 'Portland', 'zipcode': '97207'}>
>>> from flask_sqlalchemy import get_debug_queries
>>> p.json()
INFO:sqlalchemy.engine.Engine:SELECT lease.created_at AS lease_created_at, lease.updated_at AS lease_updated_at, lease.id AS lease_id, lease."propertyID" AS "lease_propertyID", lease."tenantID" AS "lease_tenantID", lease.occupants AS lease_occupants, lease."dateTimeStart" AS "lease_dateTimeStart", lease."dateTimeEnd" AS "lease_dateTimeEnd", lease."unitNum" AS "lease_unitNum" 
FROM lease 
WHERE ? = lease."propertyID"
INFO:sqlalchemy.engine.Engine:[generated in 0.00018s] (1,)
INFO:sqlalchemy.engine.Engine:SELECT users.password AS users_password, users.created_at AS users_created_at, users.updated_at AS users_updated_at, users.id AS users_id, users.type AS users_type, users.email AS users_email, users.role AS users_role, users."firstName" AS "users_firstName", users."lastName" AS "users_lastName", users.phone AS users_phone, users.archived AS users_archived, users."lastActive" AS "users_lastActive" 
FROM users, property_assignments 
WHERE ? = property_assignments.property_id AND users.id = property_assignments.manager_id AND users.type IN (?)
INFO:sqlalchemy.engine.Engine:[generated in 0.00060s] (1, 'property_manager')
INFO:sqlalchemy.engine.Engine:SELECT properties.created_at AS properties_created_at, properties.updated_at AS properties_updated_at, properties.id AS properties_id, properties.name AS properties_name, properties.address AS properties_address, properties.num_units AS properties_num_units, properties.city AS properties_city, properties.state AS properties_state, properties.zipcode AS properties_zipcode, properties.archived AS properties_archived 
FROM properties, property_assignments 
WHERE ? = property_assignments.manager_id AND properties.id = property_assignments.property_id
INFO:sqlalchemy.engine.Engine:[generated in 0.00030s] (5,)
INFO:sqlalchemy.engine.Engine:SELECT lease.created_at AS lease_created_at, lease.updated_at AS lease_updated_at, lease.id AS lease_id, lease."propertyID" AS "lease_propertyID", lease."tenantID" AS "lease_tenantID", lease.occupants AS lease_occupants, lease."dateTimeStart" AS "lease_dateTimeStart", lease."dateTimeEnd" AS "lease_dateTimeEnd", lease."unitNum" AS "lease_unitNum" 
FROM lease 
WHERE ? = lease."propertyID"
INFO:sqlalchemy.engine.Engine:[cached since 0.0115s ago] (3,)
{'id': 1, 'name': 'test1', 'address': '123 NE FLanders St', 'num_units': 5, 'city': 'Portland', 'state': 'OR', 'zipcode': '97207', 'leases': [{'id': 1, 'propertyID': 1, 'tenantID': 1, 'occupants': 3, 'dateTimeStart': '08/05/2021 02:35:57', 'dateTimeEnd': '08/05/2022 02:35:57', 'unitNum': '123'}], 'archived': False, 'propertyManagers': [{'id': 5, 'firstName': 'Gray', 'lastName': 'Pouponn', 'email': 'GrayPouponn@dwellingly.org', 'phone': '555-555-5555', 'role': 2, 'archived': False, 'lastActive': '08/05/2021 02:35:59', 'created_at': '08/05/2021 02:35:59', 'updated_at': '08/05/2021 02:35:59', 'properties': [{'id': 1, 'name': 'test1', 'address': '123 NE FLanders St', 'num_units': 5, 'city': 'Portland', 'state': 'OR', 'zipcode': '97207', 'leases': [{'id': 1, 'propertyID': 1, 'tenantID': 1, 'occupants': 3, 'dateTimeStart': '08/05/2021 02:35:57', 'dateTimeEnd': '08/05/2022 02:35:57', 'unitNum': '123'}], 'archived': False}, {'id': 3, 'name': 'The Reginald', 'address': 'Aristocrat Avenue', 'num_units': 3, 'city': 'Portland', 'state': 'OR', 'zipcode': '97207', 'leases': [{'id': 3, 'propertyID': 3, 'tenantID': 3, 'occupants': 1, 'dateTimeStart': '08/05/2021 02:35:57', 'dateTimeEnd': '08/05/2022 02:35:57', 'unitNum': 'D2'}], 'archived': False}]}]}
```

So we can see that a bunch of queries are made after we call the `json()` method.

**Comment by gussmith23** [comment]
The furthest I've gotten on this is that I'm fairly certain we need to change the `lazy` setting of the lease relationship. As far as I currently understand, the current setting of `True` means that the relationship is lazy, and thus, we lazily load each lease as it is accessed. (I think this is shown in the notes above. We see two SELECTs to the lease table.)

What we want instead (I think) is to have a single access that gets all leases (and presumably also gets the tenants of the active leases). I'm not sure how to implement this quite yet, but I'll keep digging.

**Comment by NickSchimek** [comment]
hey @gussmith23 We'll be switching to a new architecture. It will make these sort of issues a lot easier to implement a fix for.

For now I'm going to close this. Hope all is well, and hope to see you back again.
