### ISSUE TITLE
Update implementation to retrieve users from backend

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#652]
There are currently multiple different ways to ask the backend for a list of users. We're removing all of this complexity and will only have one route that the api supports to return a list of users.

Update the frontend to remove all requests that are hitting the `users/role` endpoint
Replace this request with one that hits the `user` endpoint using a get request and a query with the keyword `role`
So something like this: `client.get("/api/users?role=admin" <- but please use string interpolation and pass in the enum.

The backend does not yet support this keyword, so this is blocked unless you create your own test.

@Chris-Boe I'm not sure if you already created an issue for this. Please close if one exists.

This is related to backend issue #646

Here is a potential list of places that will need to be updated.
<img width="468" alt="Screen Shot 2021-06-14 at 12 30 26 PM" src="https://user-images.githubusercontent.com/19519317/121835971-7a984300-cd0d-11eb-9495-fa5f3cca1b7a.png">

**Comment by Chris-Boe** [comment]
Already completed: https://github.com/codeforpdx/dwellingly-app/pull/661
