### ISSUE TITLE
Replace roles get request with RoleEnum

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#653]
## Description
The backend is removing the `roles` endpoint. The frontend has an Enum that is maintained to map roles to values. Update the code to use the enum instead of hitting the backend to get a list of roles and then modifying the return result to suit display needs. It's quicker easier to create display and map to specified values using the enum.

relevant code location:

https://github.com/codeforpdx/dwellingly-app/blob/432888bcac2ef5362719ed668bd11f00732ef63d/src/views/requestAccess/requestAccess.jsx#L70-L80

Replace this by reading the RoleEnum located here:

https://github.com/codeforpdx/dwellingly-app/blob/432888bcac2ef5362719ed668bd11f00732ef63d/src/Enums/RoleEnum.js#L1-L7

**Comment by aedwardg** [comment]
Looks like this was closed by #658 

Closing, but can re-open it if I'm mistaken.
