### ISSUE TITLE
Remove backend call to get list of roles

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#658]
**Purpose**
Remove the backend call to request a list of roles. This information is readily available in the frontend code and an ajax request is not needed here.

The frontend has a RoleEnum that can be used to get a list of roles. The following ajax requests should be replaced with a method call to the FE RoleEnum.

The following needs to be updated:

https://github.com/codeforpdx/dwellingly-app/blob/432888bcac2ef5362719ed668bd11f00732ef63d/src/views/requestAccess/requestAccess.jsx#L71

<img width="483" alt="Screen Shot 2021-07-07 at 9 30 44 AM" src="https://user-images.githubusercontent.com/19519317/124682702-6a3b4880-df06-11eb-9f8f-211e52a48de0.png">

**Comment by Chris-Boe** [comment]
There are also a couple pages attempting to get users by role using an old endpoint. This issue will track the fix for those.
