### ISSUE TITLE
Properties table is not showing "Property Managers" or "Tenants"

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#670]
**Describe the bug**

**To Reproduce**
1. Go to the Properties page
2. See missing column data

**Expected behavior**
We want to map the appropriate data to the columns and match it to the mockups here:
![image](https://user-images.githubusercontent.com/8600792/128285373-66344011-3b6e-499f-9669-610171095fd4.png)

**To do**
Implement the expected behavior
Write system test that creates a property and then views the index page.

**Comment by Chris-Boe** [comment]
https://github.com/codeforpdx/dwellingly-app/issues/671 fixes the missing Added On date information

**Comment by NickSchimek** [comment]
@Chris-Boe I reverted the PR that closed this issue since it was breaking the Property page. See https://github.com/codeforpdx/dwellingly-app/pull/690 for details.
