### ISSUE TITLE
Widgets resource is broken when using postgres db

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#680]
Widget resource is not working with a postgres database.

There are no tests for the widget resource so this is not being caught by the CI

The information needed on the frontend fails to load. 
<img width="1056" alt="Screen Shot 2021-08-23 at 9 27 38 AM" src="https://user-images.githubusercontent.com/19519317/130375349-858f91e2-ba61-487b-ba74-2a7c760f96bc.png">

- Debug, write a test that captures the failure, and implement fix.

**Comment by aedwardg** [comment]
@NickSchimek Have we tracked down what the exact issue is, or only that it happens when using postgres?

**Comment by NickSchimek** [comment]
No, I haven’t looked into it

**Comment by aedwardg** [comment]
Alright, if I have the time I'll try to figure it out 🙂
