### ISSUE TITLE
Creating a property without a property manager should NOT result in a validation error

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#689]

**Comment by gussmith23** [comment]
Taking a look at this. I'm wondering if this is as simple as
1. Deleting [this code](https://github.com/codeforpdx/dwellinglybackend/blob/3376720578ca7e03670c516ccdb40ad8ef20c2e4/schemas/property.py#L17-L25)
2. Adding a test to ensure that there's no validation error.

(mostly just leaving this as a note to myself)
