### ISSUE TITLE
500 error displays when token is invalid instead of displaying login screen

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#695]
**Describe the bug**
When the user needs to login in again the frontend displays a toast message saying a 500 error has occurred. Instead it should redirect to the login screen.

**To Reproduce**
1. Log in
2. obtain a that has expired or is invalid
3. Click on any link that requires a valid token dashboard properties. tenants. etc...

**Expected behavior**
Should be redirected to login screen

**Comment by htharker42** [comment]
To resolve this issue we need to build a common module/wrapper to handle our API calls. 
The module would process the API request and if an error (500, 404, ect...) is caught it would redirect the user to the appropriate error page. 

Once the module is built, all api calls will need to be reconfigured to leverage the module rather than calling the API call themselves.

**Comment by NickSchimek** [comment]
This might be a backend issue and a frontend issue. Technically the backend should respond with a 4xx error when there is a invalid/expired token. If it really is responding with a 5xx error then there is something that needs to be fixed in the backend.

**Comment by Chris-Boe** [comment]
There are two issues here, and we can split the common API wrapper into a new one. This bug describes a backend issue, it should be returning a 401/403 instead of a 500 when an invalid/expired token is sent

**Comment by Chris-Boe** [comment]
@langstonBS let me know if you want to focus on the backend issue here or the frontend, I'll create a separate issue soon for that API wrapper

**Comment by Chris-Boe** [comment]
Created https://github.com/codeforpdx/dwellingly-app/issues/705 for the common API wrapper which should handle 403's, 401's and 500's. The backend should still be updated in this issue to return the correct response for invalid/expired JWT's

**Comment by NickSchimek** [comment]
@langstonBS we're changing the architecture a bit, and with the new architecture the backend will automatically return 401s. 

It looks like this might still be an issue with the new architecture, and there are a few things contributing to this. 

@langstonBS Let me know if your interested in working on this and I will create a new issue assigned to you that is more narrowly scoped to deal with this when we role out the new architecture in the coming week's.

For now, I am going to close this until we can verify it is still an issue with the new architecture.
