### ISSUE TITLE
Add ability to change status of tickets

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#700]
**Purpose**
What will this feature provide?
A workflow to update the status of a ticket and change it between New, In Progress, and Closed.
For now, no restrictions on status changes.

**Proposed Solution**
If you have an idea on how to implement this feature, please share!
* Make use of the existing edit functionality to also allow editing of the status

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Add a dropdown to select a status when the ticket is in Edit mode (the pencil has been clicked)
- [ ] When the user clicks save, add the status to the PUT request to the backend with the ticket ID to update the status in the database.

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.
![image](https://user-images.githubusercontent.com/8600792/135378035-58f61027-fdf0-4afa-bdc1-bcba9dc63c07.png)

**Additional context**

**Comment by htharker42** [comment]
![2021-09-29_19-45](https://user-images.githubusercontent.com/32914953/135377636-630568e8-3afe-4dc8-8fe3-3e41665d9848.png)
