### ISSUE TITLE
Allow editing of Property, Unit, Lease, and JOIN Staff for existing tenants

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#714]
**Purpose**
What will this feature provide?
Allows admins to edit the property, lease, and unit for existing tenants from the Manage -> Tenant screen

**Proposed Solution**
If you have an idea on how to implement this feature, please share!

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [x] Property should be able to be picked from a populated dropdown when in Edit mode
- [x] Unit should be editable
- [ ] Lease should be editable
- [x] When Save is clicked, these fields are also sent to the backend and the frontend reflects the update
- [x] JOIN Staff should only be editable when in Edit mode and should be saved when Save is clicked (should we move Save button down so it looks like it encapsulates both sections?)

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

**Additional context**

**Comment by Chris-Boe** [comment]
Can do something like the Property Managers list on the Edit Property page for the list of JOIN staff in non-edit mode on this page 
![image](https://user-images.githubusercontent.com/8600792/155456307-3ddf5763-2a6f-49e9-9654-f68942523ba9.png)

**Comment by Chris-Boe** [comment]
Need to figure out the API for editing a lease for a tenant

**Comment by NickSchimek** [comment]
@Chris-Boe  Not sure if you still need the answer for this.

> Need to figure out the API for editing a lease for a tenant

To update a lease for a tenant. You can use the update tenant resource and pass an the new lease fields within the tenant.

So something like:

```json
{
  'tenant': {
    'lease': {
      'unitNum': '3',
      'occupants': '3',
      ...
    }
}
```

https://github.com/codeforpdx/dwellingly-app/blob/83ecddfed4eec99ed29eca69d83ba6d4c19b12d6/app/controllers/tenants_controller.rb#L47-L52

**Comment by Chris-Boe** [comment]
> @Chris-Boe  Not sure if you still need the answer for this.
> 
> > Need to figure out the API for editing a lease for a tenant
> 
> To update a lease for a tenant. You can use the update tenant resource and pass an the new lease fields within the tenant.
> 
> So something like:
> 
> ```json
> {
>   'tenant': {
>     'lease': {
>       'unitNum': '3',
>       'occupants': '3',
>       ...
>     }
> }
> ```
> 
> https://github.com/codeforpdx/dwellingly-app/blob/83ecddfed4eec99ed29eca69d83ba6d4c19b12d6/app/controllers/tenants_controller.rb#L47-L52

Yep I got it 😄 just fixing the calendar pop-up
