### ISSUE TITLE
Words overlap on Dashboard manager section

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#724]
**Describe the bug**
Yesterday overlaps into the managers name on the dashboard display

<img width="415" alt="Screen Shot 2021-10-24 at 7 35 08 PM" src="https://user-images.githubusercontent.com/19519317/138590228-7ce1385f-08ce-461b-8f89-9f5b005ce5dc.png">

**To Reproduce**
1. Create a most recent manager with a created_at timestamp of yesterday
2. Go to dashboard

**Comment by Chris-Boe** [comment]
Fixed by https://github.com/codeforpdx/dwellingly-app/pull/698
