### ISSUE TITLE
Create reports dashboard element as shown in figma design

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#729]
**Purpose**
Looks like this will get the number of closed tickets within the last week.
and number of compliments within the last week.

<img width="767" alt="Screen Shot 2021-10-31 at 5 54 49 PM" src="https://user-images.githubusercontent.com/19519317/139575338-12448901-74bb-4603-a460-150b215eb70d.png">

**Comment by Chris-Boe** [comment]
@NickSchimek we got rid of this component a few months ago after speaking with Join and the designers. We don't need the Reports feature or dashboard component anymore 👍
