### ISSUE TITLE
Creating property with a name that already exists does not display the error message

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#740]
**Describe the bug**
A property name is unique.
When creating a property with a name that already exists. The error message is not displayed. Instead the user sees that response status code, instead of the responses error message.

**To Reproduce**
1. Go to add property
2. fill in the form and provide a property name with one that already exists in the system
3. submit form

**Expected behavior**
I'd expect an error message that says the property name already exists.

**Screenshots**
<img width="1584" alt="Screen Shot 2021-11-14 at 8 44 43 AM" src="https://user-images.githubusercontent.com/19519317/141662247-d10c506c-07d1-4bb4-8c34-12b6d84db065.png">

**Comment by yunnie** [comment]
When I tried the replicate the error, I got a different response message: ```PropertiesController#create
SQLite3::ConstraintException: UNIQUE constraint failed: properties.name``` However I didn't get a Json message back. 

I tried to add validation to the `model/property.rb` Specifically: `validates :name, uniqueness: { case_sensitivity: false}` then I get a different error:
```
NoMethodError in PropertiesController#create
undefined method 'errors' for nil:NilClass
``` 
which then points me to line 25 in `controllers/properties_controller.rb` which is 
```
format.json { render json: @api_property.errors, status: :unprocessable_entity }
```
 But I'm not sure where `@api_property` comes from. 

What am I missing?

FYI The console running the local host shows: `Not notifying due to an invalid api_key`

**Comment by NickSchimek** [comment]
whoops `@api_property` should be `@property`

This is an older issue prior to be the backend change. And since we haven't implemented any validations then the error you originally got would be correct.

It should work after updating the api_property to the correct variable.

**Comment by NickSchimek** [comment]
originally I incorrectly generated a bunch of files with api_mode_name. I fixed it, but had to go back to the already created files and fix the variables/naming.  I thought I got them all, but I must of missed this one.

**Comment by NickSchimek** [comment]
And in case you don't already know. An instance variable will return `nil` when it is not instantiated. That's why you get the No method error for nil class.

**Comment by NickSchimek** [comment]
@yunnie You can add the gem https://rubygems.org/gems/shoulda-matchers which makes it easy to test validations, and other other things.

It'd be something like:

```ruby
it { is_expected.to validate_uniqueness_of(:name) }
```

https://matchers.shoulda.io/docs/v5.1.0/Shoulda/Matchers/ActiveRecord.html#validate_uniqueness_of-instance_method

`is_expected.to` and `should` mean the same thing. I just prefer to use `is_expected.to` and I think it's more widely used.

**Comment by NickSchimek** [comment]
or I will add it when I get around to it.

**Comment by yunnie** [comment]
I added the `shoulda-matchers` gem and added a test to `spec/models/property_spec.rb`. I then tried to run the tests `>bin/rails test ./spec/models/property_spec.rb`, but got `0 runs, 0 assertions, 0 failures, 0 errors, 0 skips` 

I get the same result if I try `>bin/rails test`. Where am I going wrong?

**Comment by NickSchimek** [comment]
I think it's "bin/rspec" to run the tests

**Comment by yunnie** [comment]
Thanks! That did the trick.
