### ISSUE TITLE
Unable to search and assign property manager when creating a property via the create manager page

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#745]
**Describe the bug**
Assigning a property manager on the Add Property Modal within the the add Property Manager page does not allow the user to filter the results, and does not allow the user to scroll through the list of results.

**To Reproduce**

Prior data needed:
There must be a lot of property managers in the system, enough to fill your screen height with results.

1. Go to `/add/manager` endpoint
2. Click on `Create New Property`
3. Click in the Search Property Managers search panel
4. Notice it does not allow to search and immediately displays the entire list without the ability to scroll.

**Expected behavior**

**Screenshots**
<img width="999" alt="Screen Shot 2021-11-15 at 3 03 20 PM" src="https://user-images.githubusercontent.com/19519317/141730650-baf4ec23-c21a-4819-90ea-3ba152b2b60c.png">

**Desktop (please complete the following information):**
 - OS: macos
 - Browser Chrome
 - Version 94

# Follow up Question

Should the assign property manager even be visible within this context?

If your creating a manager, and find yourself needing to create a new property, then I would assume you don't need to add existing managers to this property. If that's the case they can probably create the property first or add after creating the current PM?

I checked the figma docs, but I couldn't find the page where we add a property manager, and it has this modal open. 

<img width="1259" alt="Screen Shot 2021-11-15 at 3 13 15 PM" src="https://user-images.githubusercontent.com/19519317/141732633-f8689c9b-41d6-4ed6-ab69-bd024bc7cb4d.png">

**Comment by yunnie** [comment]
Nick said, that Hugh said to remove the button.

**Comment by yunnie** [comment]
My plan is to remove the Assign Property Managers option from the "Add Property Modal". Since the modal re-uses the AddProperty component, I plan on adding a parameter to include or exclude the "Assign Property Managers".
