### ISSUE TITLE
Unable to search multiple fields on the ticket index page

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#756]
**Describe the bug**
Unable to find a ticket when searching for the tenant and name of ticket

**To Reproduce**

Prior setup:
Given create a ticket `leaky faucet` or something, and assign it to a tenant who already has more than 5 tickets

1. Go to `manage/tickets`
2. In the search bar type the name of tenant in the prior setup and the name of the issue

**Expected behavior**
I would expect the search results to filter by both the name of the tenant and the issue name.

**Comment by Chris-Boe** [comment]
@NickSchimek I can search by tenant name OR issue description
![image](https://user-images.githubusercontent.com/8600792/143671118-9cfbf1e0-a066-4923-8751-9423dcce6548.png)

![image](https://user-images.githubusercontent.com/8600792/143671128-4a787254-6ccf-4560-879b-7e774aed84f1.png)

But you are expecting to be able to type something like "Kimberly Conley Put staff one party" and have the ticket with both that tenant name and issue description returned in the list?

**Comment by NickSchimek** [comment]
Yeah, that was my expectation. It's probably not something that needs to be done, but I was expecting to be able to do that. Might be useful if the tenant has a lot of open tickets.

**Comment by yunnie** [comment]
The ticket index page uses the  `search` component in `app/javascript/components/src/views/components/Search/index.jsx` to implement the ticket search. So any modification to how the search functionality works will change how the search function across the application will work. I assume this is OK, as I think most people would expect the search function to work as Nick describes.

**Comment by NickSchimek** [comment]
oh? It's not using the SearchPanel component? All of the search functionality I've seen so far has been using the SearchPanel (react-search-panel) - I didn't know we had another search component. 

Then this change wont impact search across the app. It looks like it will impact the PropertyList page and the TenantList page, which I think is okay if we allow the search to include any field. 🤷
