### ISSUE TITLE
Archived managers do not have correct status in Property Manager List

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#765]
**Describe the bug**
https://github.com/codeforpdx/dwellingly-app/blob/253a96bb0e2061055cece637e4c69eabc1fd1125/src/views/PropertyManagerList/index.jsx#L25-L32

I believe the logic here should be `&&` instead of `||` on line 25

Additionally the function that is used to format the data will return a string of Invalid Date which is truthy if it cannot format the date.

It would be good to extract this logic out to a function and unit test it in isolation to ensure the correct description is returned for the possible inputs.

**To Reproduce**
1. Create an archived property manager that has a last active time stamp
2. Go to manage/managers

**Expected behavior**
Should see archived status

**Comment by jumperck** [comment]
I started working on this item
