### ISSUE TITLE
Create a unit_number field on the Tickets table

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#785]
**Purpose**
We can infer which unit number a ticket belongs to at anytime, but it may be good to record this data at the time of create incase the lease info changes after the ticket is created. Perhaps there may need to be some additional business logic when a lease is updated, but for now it is probably good to record which unit number the tenant belongs to at the time the ticket is created.

**Comment by Chris-Boe** [comment]
@NickSchimek I'm thinking we don't really need this since we have the related Unit on the Tenant object, and the app is mainly for managing tickets relating to Tenants and not things like maintenance requests. Maybe a Milestone 2 upgrade if we are asked for it?

**Comment by NickSchimek** [comment]
> and the app is mainly for managing tickets relating to Tenants and not things like maintenance requests.

That makes sense. Let's close this then.
