### ISSUE TITLE
Update Left Nav and page functionalities based on user permissions

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#793]
**Purpose**
What will this feature provide?
Limit the pages offered to the user based on what they are allowed to do in the app

**Proposed Solution**
If you have an idea on how to implement this feature, please share!
Create a permissions hook or method from the UserContext (or use one that might exist by this point) that will give the permissions the user has. Show the different menu sections based on those permissions. Add permission checks on every page in case they come in directly from a URL, redirect them to the Dashboard if they don't have access to the page.

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Redirects from each page to the Dashboard if the user does not have the correct permissions
- [ ] Left nav is limited to what the user has access to

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

**Additional context**

**Comment by Chris-Boe** [comment]
@NickSchimek when I sign in with a fresh local database to admin@dwellingly .org I get a null "role" back from the sign_in API. Is there an API we need to call to get the role/permissions for the user or something else I need to set for the account? 
![image](https://user-images.githubusercontent.com/8600792/182312245-02172638-6a27-4436-a7bb-c6c81f586799.png)

**Comment by NickSchimek** [comment]
The role has been removed. Need to clean that up so we are not sending it
anymore. There should be a type field that can be used instead. See
UserType js file and the type field in the user model.

**Comment by NickSchimek** [comment]
> Is there an API we need to call to get the role/permissions for the user or something else I need to set for the account?

It looks like we need to send back the `type` field with that endpoint, and update `App.jsx` methods `getCurrentState` and `login`. 

Alternatively you can send back booleans as well for fields `admin`, `staff`, `project_manager`.  <-- I'd probably lean towards this.

Let me know if you'd like me to make that update. Then you can focus on the more important things.

**Comment by Chris-Boe** [comment]
@NickSchimek yeah if you want to make the update to send back the booleans, I can update the frontend to consume them. If you're planning on adding them to the sign_in API response then I can start updating the frontend to expect that!

**Comment by Chris-Boe** [comment]
Following rules setup here: https://github.com/codeforpdx/dwellingly-app/blob/development/docs/User_authorization.pdf

- AdminRoute exact path='/' component={() => Redirect to="/dashboard" } 
  - Admin only, with redirect to proper dashboard if not admin
- AdminRoute exact path='/dashboard' component={DashboardAdmin} 
  - Admin only, with redirect to proper dashboard if not admin
- AdminRoute exact path='/home' component={() => Redirect to="/dashboard" } 
  - Admin only, with redirect to proper dashboard if not admin
- StaffRoute exact path='/add/tenant' component={AddTenant} 
  - Staff+ only
- StaffRoute exact path='/add/property' component={() => AddProperty } 
  - Staff+ only
- StaffRoute exact path='/add/manager' component={AddPropertyManager} 
  - Staff+ only
- PropertyManagerRoute exact path='/add/ticket' component={AddTicket} 
  - PM+ only
- PropertyManagerRoute exact path='/manage/tenants' component={Tenants} 
  - PM+ only, list restricted on the backend based on relation to PM, no restriction for staff and admin
  - @NickSchimek Is this restriction in place?
- StaffRoute exact path='/manage/tenants/:id' component={EditTenant} 
  - Staff+ only
- StaffRoute exact path='/add/emergencycontact' component={AddEmergencyContact} 
  - Staff+ only
- StaffRoute exact path='/edit/emergencycontact/:id' component={AddEmergencyContact} 
  - Staff+ only
- PropertyManagerRoute exact path='/manage/properties' component={Properties} 
  - PM+ only, list restricted on the backend based on relation to PM, no restriction for staff and admin
  - @NickSchimek Is this restriction in place?
- PropertyManagerRoute exact path='/manage/properties/:id' component={EditProperty} 
  - PM+ only, restricted on the backend based on relation to PM, no restriction for staff and admin
  - @NickSchimek Is this restriction in place?
- StaffRoute exact path='/manage/managers' component={PropertyManagerList} 
  - Staff+ only
- StaffRoute exact path='/manage/managers/:id' component={EditPropertyManager} 
  - Staff+ only
- PropertyManagerRoute exact path='/manage/tickets' component={TicketList} 
  - PM+ only, access based on association with their related properties, no restriction for staff and admin
- StaffRoute exact path='/staff' component={JoinStaffList} 
  - Admin only
- StaffRoute exact path='/staff/add' component={AddStaffMember} 
  - Admin only
- StaffRoute exact path='/manage/staff/:id' component={EditStaff} 
  - Admin only
- PropertyManagerRoute exact path='/emergency' component={EmergencyContacts} 
  - PM+ only
- PrivateRoute exact path='/settings' component={Settings} 
  - just authenticated
- PrivateRoute exact path='/changePassword' component={ChangePassword} 
  - just authenticated
- StaffRoute exact path='/request-access/:id' component={RequestAccess} 
  - Staff+ only
- PropertyManagerRoute exact path='/testpm' component={DashboardPropertyManager} 
  - PM only
- StaffRoute exact path='/teststaff' component={DashboardStaff} 
  - Staff only
- PropertyManagerRoute exact path='/m/testpm' component={DashboardPropertyManagerMobile} 
  - PM only
- StaffRoute exact path='/m/teststaff' component={DashboardStaffMobile} 
  - Staff only

All the dashboards will have routing done by a single controller which will take into account the user type and the screen size.

Might need some help in getting different users seeded at the start and able to login

**Comment by NickSchimek** [comment]
Okay, PR #836 adds the user info requested.

And Yes, all scopes have been created.
