### ISSUE TITLE
Unable to accept invitation in email

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#799]
**Describe the bug**

**To Reproduce**
1. Go to Add PropertyManager
2. Fill in details and submit
3. Grab the invitation token either from the db or from the server log

You might be able to use this to see the error

```
http://localhost:3000/api/users/invitation/accept?invitation_token=BJvxUbgDqgwesobk5yWi
```

<img width="583" alt="Screen Shot 2022-02-21 at 1 23 27 PM" src="https://user-images.githubusercontent.com/19519317/154888942-ab31673f-ddbf-4470-820e-ea621d403074.png">

I'd expect the invitation to be accepted and automatically logged in.

**Comment by aedwardg** [comment]
@NickSchimek I looked into this and it's because of the Devise method we're overwriting in the invitations controller.
https://github.com/codeforpdx/dwellingly-app/blob/c99a750843411e42aefc4a10e248eb547d2d3697/app/controllers/invitations_controller.rb#L37-L40

It turns out `resource_class` is used for tons of different things in the Devise source code, so changing it here has a bunch of unintended consequences.

**Comment by yunnie** [comment]
@aedwardg How did you figure this out???? I usually read the imports to trace through issues like this, but Rails just automagically imports stuff. So I'm really curious how you diagnosed this.

**Comment by aedwardg** [comment]
@yunnie It took a little bit of Rails knowledge and a lot of digging. 
Sorry in advance for my long-winded explanation, but hopefully this will help you and/or anyone else who runs into a similarly tricky bug.

Looking at the error, I can see that in the InvitationsController we are trying to [dig](https://ruby-doc.org/core-3.1.0/Hash.html#method-i-dig) through the params hash to find a nested key called `:type`.  The value for that key should be a string that can be [constantized](https://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-constantize), but instead we're getting `nil`. This controller is a sub-class of the `Devise::InvitationsController`, which we use to handle inviting all our user types by marking the `User` model as `:invitable`:
 https://github.com/codeforpdx/dwellingly-app/blob/c99a750843411e42aefc4a10e248eb547d2d3697/app/models/user.rb#L1-L5

So what's in the params hash that we're receiving?
We define what is required and permitted here:
https://github.com/codeforpdx/dwellingly-app/blob/c99a750843411e42aefc4a10e248eb547d2d3697/app/controllers/invitations_controller.rb#L20-L35
And we send those values to the controller here (notice the `type` param):
https://github.com/codeforpdx/dwellingly-app/blob/c99a750843411e42aefc4a10e248eb547d2d3697/app/javascript/components/src/views/AddPropertyManager/index.jsx#L71-L81

Great, so this all looks fine...so why are we getting this error?
A good way to check is by putting in a byebug breakpoint inside `resource_class` like so (this project is using the byebug gem for interactive debugging):
```ruby
def resource_class
  byebug
  params.dig(:invitation, :type).constantize
end
```
With that in there, start up your server, sign in and try to invite a new property manager.
When do, your console should show the breakpoint with `(byebug)` as the prompt.  If you type `params`, we can see that the "type" key is there, just like it should be:

![image](https://user-images.githubusercontent.com/44326005/165689284-6d4a0797-a537-49aa-8465-91a468140d62.png)

After typing `continue` (it might take a few times), you should get the invitation link, which means everything went just fine.
BUT, when we open up that link, we hit the breakpoint again. Why? We only have a create action in our controller, but byebug is telling us that it is being processed by `InvitationsController#edit`:

![image](https://user-images.githubusercontent.com/44326005/165690012-41207718-9ed8-44e6-aeaf-c52256d8d516.png)

And, if we check the params now, we can see there is no "invitation" or "type" keys in the hash:

![image](https://user-images.githubusercontent.com/44326005/165690219-4ca625a1-a9c0-4c40-b623-c6ace2f2e55a.png)

As you might expect, running `continue` will make us hit the expected bug and crash.  This is when I realized there must be lot that is inherited from Devise that we messed up by overriding `resource_class`, so I looked at the source code.

In the `devise_invitable` source code, we can find a small `edit` action in the `Devise::InvitationsController`:
https://github.com/scambra/devise_invitable/blob/7c4b1f6d19135b2cfed4685735a646a28bbc5191/app/controllers/devise/invitations_controller.rb#L39-L43

At first glance, it doesn't seem to call `resource_class`, but if you scroll to the top of the file, you'll find a [before_action](https://github.com/scambra/devise_invitable/blob/7c4b1f6d19135b2cfed4685735a646a28bbc5191/app/controllers/devise/invitations_controller.rb#L5) that calls [another method](https://github.com/scambra/devise_invitable/blob/7c4b1f6d19135b2cfed4685735a646a28bbc5191/app/controllers/devise/invitations_controller.rb#L99-L104) that in turn calls `resource_class`. In fact, the `resource_class` method is called in 5 different places in this controller so it appears that tailoring it to a param that will only be sent in the `create` action is likely to break a lot of stuff under the hood.

If you're interested in going down another rabbit hole, you can find the original `resource_class` definition in the Devise code itself (devise_invitable inherits it from that): see [here](https://github.com/heartcombo/devise/blob/f8d1ea90bc328012f178b8a6616a89b73f2546a4/app/controllers/devise_controller.rb#L49-L51) and [here](https://github.com/heartcombo/devise/blob/f8d1ea90bc328012f178b8a6616a89b73f2546a4/lib/devise/mapping.rb#L82-L84) for starters.

**Comment by NickSchimek** [comment]
hey @aedwardg Sorry, I didn't see you were assigned and started to look into this and realized what the issue is.
I have a fix, but its not 100% done yet.

Here is the branch I started on: [799_user_can_accept_invitation](https://github.com/codeforpdx/dwellingly-app/compare/799_user_can_accept_invitation)

Do you want to continue with this branch and finish it up? It still needs a couple things. Feel free to ping me if you have any questions. I put details in the commit message. Thanks!

**Comment by NickSchimek** [comment]
@aedwardg I don't remember why I overrode that method. I think it had to do with ensuring the correct type of user is created. I don't mind keeping the override like in the solution I provided above, but I think it would be better if we didn't have to override that method. I think rather than overriding the method we need to tell devise invitable which params to allow through.

**Comment by aedwardg** [comment]
@NickSchimek if you've got something working, feel free to take over. I assigned myself after last meet because I was poking around at it, but I didn't continue after it told me there was a missing `invitations/edit` view.
Do you think it might make more sense to make each of the user types explicitly invitable and then invite via `{user_type}/invitation` instead of trying to do all types through the generic `user/invitation` route?

**Comment by NickSchimek** [comment]
> but I didn't continue after it told me there was a missing invitations/edit view.

haha. That's the state I left the above solution in. So that's not finished either.

> Do you think it might make more sense to make each of the user types explicitly invitable and then invite via {user_type}/invitation instead of trying to do all types through the generic user/invitation route?

I had thought about that, and that's one possible way to do it. I believe that would require a change in the javascript code as well. 

I think we can create all the various users with the same resource_class `User`, as long as the type field is set. I think I overrode that method because it wasn't allowing the type param to come through for some reason ( maybe I was missing something or wasn't doing it right ) so I quickly overrode that method rather than figuring out what I was doing wrong.

Either way its done it doesn't matter to me as long it works. And either way we do it we will still have to tell it how to render the view. I think there is already a page created on the react app for setting the password after confirming the invite. Just need to render that page.

**Comment by NickSchimek** [comment]
> if you've got something working, feel free to take over.

Okay, I can take this over.
