### ISSUE TITLE
Backend: initialization of DB needs to be moved into the initialization function 

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#80]
in app.py

if __name__ == '__main__':
   db.init_app(app)  <--- this needs to work 
    app.run(port=5000, debug=True)

**Comment by DaveTrost** [comment]
Documenting some information sources ...
- [The Application Factory Method for Flask](https://hackersandslackers.com/flask-application-factory)
- [Flask database migrations](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iv-database-legacy/page/9)

**Comment by DaveTrost** [comment]
I think this is not an issue (anymore?). Especially with the changes made to app.py for the pytest infrastructure branch. The create_app() function now looks roughly as follows - note how **all** required setup is now inside of create_app:
```
def create_app():
    app = Flask(__name__)
    config_app(app)
    create_routes(app)
    #...
    db.init_app(app)
    return app

app = create_app()

if __name__ == '__main__':
    app.run(port=5000, debug=True)
```

Also, based on the following resources, the pattern we are using appears to be one of the preferred/best practice approaches:
- [Flask SQL-Alchemy API setup](https://flask-sqlalchemy.palletsprojects.com/en/2.x/api/)
- [Flask Application Factory Pattern](https://hackersandslackers.com/flask-application-factory/) (see the section at the end called "Our App's Entry Point")
