### ISSUE TITLE
Assigning a property to a user requesting access does not save the property assignment

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#817]
**Describe the bug**
When you assign a property to a new user requesting access (and set them to Property Manager), the property selection is not saved in the database.

**To Reproduce**
1. Go to the dashboard and click "Add" on a user requesting access
2. Set them to PROPERTY_MANAGER role
3. Select a property to assign to them
4. Click on Save (have network tab open to see the property ID getting sent to the backend
5. Look up this user on the Property Manager list page
6. Click on the user from the list
7. Notice the property selected in step 3 is not shown on the page nor returned from the network request

**Expected behavior**
New Property Manager should have property assigned 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NickSchimek** [comment]
I'm not seeing a place to enter a property. Looks like there might be two issues here?
<img width="723" alt="Screen Shot 2022-07-18 at 0 24 27" src="https://user-images.githubusercontent.com/19519317/179405240-bf28a668-dc17-45a5-a988-2152dd1164a1.png">

**Comment by Chris-Boe** [comment]
@NickSchimek ~~Looks like you might be looking at an old version of the app, when you select Property_Manager it should show a SearchPanel for Properties~~ I think I was able to fix the Search Panel not showing up on my current branch and that's when I noticed the backend wasn't saving the update we're sending it. I'm almost done with my branch so once it's merged we can repro this and investigate!
