### ISSUE TITLE
Fix Staging and Production deployments on Heroku

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#820]
**Purpose**
What will this feature provide?

**Proposed Solution**
If you have an idea on how to implement this feature, please share!

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ]

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

**Additional context**

**Comment by NickSchimek** [comment]
I pushed the button to reconnect the deployment.  All pushes to development branch will be automatically deployed to -> https://dwellingly-app.herokuapp.com/login
