### ISSUE TITLE
Create Postman file and share

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#83]
create postman file with all current valid backend calls 
create both localhost and to live database

**Comment by Chris-Boe** [comment]
# | method | route                | action                     |
# | :----- | :------------------- | :---------------- |
- [x] | POST   | `login`                | Login and returns a token    |
- [x] | POST   | `register`            | Creates a new user   |
# | :----- | :------------------- | :------------------ |
- [x] | GET    | `user/:userId`       | Gets a user details       |
- [x] | DEL    | `user/:userId`       | Deletes a user     |
# | :----- | :------------------- | :------------------ |
- [x] | POST   | `properties`         | Creates a new property     |
- [x] | GET    | `properties`          | Gets all properties        |
- [x] | GET    | `property/:name`  | Gets a single property     |
- [x] | PUT    | `property/:name`  | Updates a single property  |
- [x] | DELETE | `property/:name`  | Deletes a single property  |
# | :----- | :------------------- | :----------------- |
- [x] | GET    | `tickets`          | Gets all tickets      |
- [x] | GET    | `ticket/:id`  | Gets a single ticket     |
- [ ] | POST   | `ticket/:id`  | Creates a single ticket  |
- [x] | DELETE   | `ticket/:id`  | Deletes a single ticket  |
# | :----- | :------------------- | :---------------- |
- [x] | GET    | `leases`  | Gets all leases     |
- [x] | GET    | `lease/:id`  | Gets a single lease     |
- [ ] | POST   | `lease/:id`  | Creates a single lease  |
- [x] | DELETE   | `lease/:id`  | Deletes a single lease  |
# | :----- | :------------------- | :----------------- |
- [x] | GET    | `emergencyNumbers/:id`  | Gets an emergency number   |
- [ ] | PATCH    | `emergencyNumbers/:id`  | Updates an emergency number     |
- [x] | DELETE   | `emergencyNumbers/:id`  | Deletes a single emergency number  |
- [x] | GET    | `emergency/:id`  | Gets an emergency   |
- [ ] | POST    | `emergency/:id`  | Creates an emergency     |
