### ISSUE TITLE
Frontend: Create Terms & Conditions View

### ISSUE THREAD

**Issue by sternmd** [codeforpdx/dwellingly-app#84]
Page view for signing up. See branch: `terms-view`

See figma designs for details:
https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view

**Comment by sternmd** [comment]
@htharker42 we will eventually need terms body copy from Join, though wouldn't consider this to be a complete blocker. If it's alright with you, I will create a separate issue for adding the legal copy later, which would perfect as a "good first issue" for someone.

**Comment by ThomasShetler** [comment]
Is there a slack? I want to get involved
