### ISSUE TITLE
Application - Unit Tests

### ISSUE THREAD

**Issue by dougmakingstuff** [codeforpdx/dwellingly-app#9]
As a developer, I would love to test that my redux files and other programmatic elements are working as intended.

Create unit tests for dux files and components so we can see if they do what they say.

**Comment by dougmakingstuff** [comment]
There's a PR that we need to merge that does a lot of these

**Comment by bobbymart1n** [comment]
Unit tests from the private repo are now in this repo on the `feature/unit-tests` branch
